readme.md
I think the first example should just include `github.com/xxx` so people aren't typing in one word project names.
=> Make `starport app` section less confusing

Makefile, readme.md
* Continue building if Node.js is not found (welcome screen won't show up)
* Added Node.js as an optional requirement in the readme.
close https://github.com/tendermint/starport/issues/4
=> Continue building without Node

cmd/root.go, cmd/serve.go, cmd/typed.go, scripts/dev
-p option enables serving apps on a different path other than current
directory. (for serve and type commands)
it is also useful when serving apps in Docker containers with starport since
they persist in different paths. devs no longer need to `cd` first to
the app.
also useful during development of starport. currently using starport cli
in the development mode requires to run `make`. this is a long running
task that makes a bunch of long configuration including `npm install`. instead of `make` we can
directly run `go run main.go` in development which is faster. but using starport
this way requires the ability of setting a path to the application
because we can no longer `cd` into the app. `cd`ing into the app and
running `go run path/to/main.go` is also possible but not convenient.
e.g.: …
=> cmd: add -p option targeting custom app path

.github/workflows/npm-publish.yml, .npm/bin/index, .npm/lib/conf.js, .npm/lib/install.js, .npm/lib/starport.js, .npm/package.json, scripts/npm-publish
after each release.
starport can be installed globally by using: `npm i -g
@tendermint/starport`.
while being installed, it automatically dedects current platform and
downloads the Go binary with the release's version on the fly and installs it.
NOTE: only covers x64 architectures.
NOTE: fix TODO above before merging.
closes #31
=> publish starport to npm

interface/cli/starport/cmd/cmd.go, interface/cli/starport/cmd/serve.go
* reconstructed organization of serve command.
a part of https://github.com/tendermint/starport/issues/56.
=> interface/cli/starport/cmd: made serve command newable

.github/workflows/lint.yml
we are in a refactoring period and it is safe to ignore linter errors at this stage since some of the related code will be changed.
=> ci: disable linter for PRs

interface/cli/starport/cmd/app.go, interface/cli/starport/cmd/cmd.go
* reconstructed organization of app command.
solves a part of #56,
depends on https://github.com/tendermint/starport/pull/64.
=> interface/cli/starport/cmd: made app command newable

interface/cli/starport/cmd/add.go, interface/cli/starport/cmd/cmd.go
* reconstructed organization of add command.
solves a part of #56.
=> interface/cli/starport/cmd: made add command newable

interface/cli/starport/cmd/cmd.go, interface/cli/starport/cmd/type.go, interface/cli/starport/cmd/typed.go
* reconstructed organization of `type` command.
solves a part of #56.
=> interface/cli/starport/cmd: made type command newable

go.mod, go.sum, interface/cli/starport/cmd/serve.go, pkg/cmdrunner/cmdrunner.go, pkg/cmdrunner/step/step.go
_trying out the [previously proposed](https://github.com/tendermint/starport/pull/14) command runner API to refactor serve._
solves a part of https://github.com/tendermint/starport/issues/81.
=> interface/cli/starport/cmd: refactor `serve` short-running cmd exec

go.mod, interface/cli/starport/cmd/serve.go, pkg/cmdrunner/cmdrunner.go, pkg/cmdrunner/step/step.go
* some refactoring related to `pkg/cmdrunner` and `starport/cmd`.
solves a part of https://github.com/tendermint/starport/issues/81.
=> starport/cmd: use cmdrunner to start cli servers

starport/services/serve/dev.go, starport/services/serve/serve.go
as a starting point to refactor development server.
=> services/serve: split dev handler

starport/pkg/httpstatuschecker/httpstatuschecker.go, starport/pkg/httpstatuschecker/httpstatuschecker_test.go, starport/pkg/xhttp/response.go, starport/pkg/xhttp/response_test.go, starport/services/serve/dev.go, starport/services/serve/serve.go, starport/ui/src/views/Start.vue
* updated frontend bindings.
* added new `pkg/xhttp` helper.
* added new `pkg/httpstatuschecker` helper.
=> services/serve: refactor dev server handler

starport/pkg/fswatcher/fswatcher.go, starport/services/serve/serve.go
* services/serve now uses pkg/fswatcher to watch for changes on user's app.
=> pkg/fswatcher: added and refactored its callers

go.mod, go.sum, starport/interface/cli/starport/cmd/serve.go, starport/pkg/fswatcher/fswatcher.go, starport/services/serve/serve.go
* add graceful shutdown to dev server
* handle all async errors
* exclude hidden files from watch list
* stabilize cancelation for serve and other async tasks
note that, all tasks that needs to run concurrently is now ensured to run concurrently. thus, dev server immediately started and its address printed at the top of the logs as a side effect.
=> services/serve: stabilize serve

go.mod, go.sum, starport/interface/cli/starport/cmd/app.go, starport/templates/app/new.go, starport/templates/app/options.go, starport/templates/app/templates/Makefile.plush, starport/templates/app/templates/app/prefix.go.plush, starport/templates/app/templates/cmd/{{binaryNamePrefix}}cli/main.go.plush, starport/templates/app/templates/cmd/{{binaryNamePrefix}}d/main.go.plush, starport/templates/app/templates/frontend/src/store/index.js.plush
Adds a `--address-prefix` flag to `starport app`.
```
starport app github.com/dundermifflin/scranton --address-prefix office --denom schrutebuck
```
Also, fixes custom `denom` in `Makefile`.
close https://github.com/tendermint/starport/issues/93
=> Added custom bech32 address prefixes

starport/services/serve/serve.go
* cleanup.
* fix git version retrieval.
related to #81.
=> services/serve: simplify concurrency

go.mod, go.sum, starport/services/serve/serve.go
instead of aborting the serve on an error related to building the app's backend, wait for a fix and try to rebuild.
resolves #107.
=> services/serve: wait for a fix on build error

starport/pkg/cmdrunner/cmdrunner.go, starport/services/serve/serve.go
previously when user just started to `serve`, during the process of building the user's app;
and if there is a cancellation made by sending a ^C signal during that period, `serve` was thinking that app failed to build and printing an empty build error log before aborting the serving process.
this commit fixes that.
before:
```
📦 Installing dependencies...
^Ccannot build app:
waiting for a fix before retrying...
aborted
```
after:
```
📦 Installing dependencies...
^Caborted
```
related to #81.
=> services/serve: omit build error on cancellation

starport/services/serve/serve.go
otherwise it looks for the conf file where `starport` command is executed so `-p` (custom app path) won't work.
=> services/serve: use the app path while searching conf file

.github/workflows/test-e2e.yml, e2e/README.md, e2e/package-lock.json, e2e/package.json, e2e/test/app.ts, e2e/tsconfig.json, scripts/test-e2e
* added first e2e test to check app command.
related to https://github.com/tendermint/starport/issues/28.
=> start e2e testing

starport/templates/typed/new.go
`type` silently failed, because it tried to generate frontend files in `./frontend` (and we've replaced it with `./vue`)
fix https://github.com/tendermint/starport/issues/178
He gotta write a test for this :smile:
=> Replace frontend dir name with vue

starport/templates/app/templates/app/prefix.go.plush
related to https://github.com/tendermint/starport/issues/181.
there seems to be no strightforward way of configuring the prefix by a single constant that can be applied to both backend and frontend. so both needs to be updated individually.
=> simplify configuring account prefix

changelog.md, starport/interface/cli/starport/cmd/app.go, starport/templates/app/new.go, starport/templates/app/options.go
it is previously moved as a prop to the `config.yml`.
resolves #159.
=> cmd/app: rm unused denom flag

changelog.md, starport/templates/typed/templates/x/{{appName}}/client/cli/tx{{TypeName}}.go.plush
=> appcli checks min. args for create-x cmd

.gitignore, scripts/build
compatible with [repl.it](https://repl.it)
it needs to be ran as following on _repl.it_ in order to `starport` command to be available.
```
$ . ./scripts/build 
```
=> added scripts/build

go.mod, go.sum, starport/services/scaffolder/module.go, starport/templates/app/launchpad/app/app.go.plush, starport/templates/app/launchpad/app/export.go.plush, starport/templates/module/new_import.go
Update templates for CosmWasm 0.11
Add `distr` module along with `wasm` module
Keep a fixed commit hash for the CosmWasm version to avoid an incompatible version
I arbitrarily took shortcuts for the placeholder names in the templates, this should be refactored: #319
=> Fix templates for CosmWasm 0.11

changelog.md, integration/cmd_type_test.go, starport/services/scaffolder/type.go
`starport type user email email` shows an error
=> fix: prevent duplicated fields in type command

integration/cmd_type_test.go
with the recent changes, env.Exec() and env.Serve() needs to be covered
by a env.Must() in the main goroutine of the test.
=> integration: fail tests on failed assertions

integration/cmd_type_test.go, starport/services/scaffolder/type.go
Prevent using Go reserved word for type name or field name in the command `starport type` as it would generate a code with errors
=> fix: prevent using reserved word as type name or field name

starport/services/chain/plugin-launchpad.go, starport/services/chain/plugin-stargate.go
Tendermint uses `pprof_laddr` in config.toml.
https://github.com/tendermint/tendermint/blob/6e16df854780f8c50911fdc400843c13ab1b480b/config/config.go#L384
=> prof_laddr ==> pprof_laddr

changelog.md, starport/interface/cli/starport/cmd/app.go
=> feat(cmd/app): point to Stargate as default sdk version

changelog.md, go.mod, go.sum, integration/config_test.go, integration/env_test.go, starport/pkg/confile/confile.go, starport/pkg/confile/confile_test.go, starport/pkg/confile/encoding.go, starport/services/chain/chain.go, starport/services/chain/conf/config.go, starport/services/chain/plugin-launchpad.go, starport/services/chain/plugin-stargate.go, starport/services/chain/plugin.go, starport/services/chain/serve.go
through Starport's config.yml.
* added chain id configurability by `chain_id` prop in the top level of `config.yml`.
* added `config/app.toml` and `config/config.toml` configurability for appd under new `init.app` and `init.config` sections of `config.yml`.
* made some refactoring.
closes #337.
=> feat(config.yml): make sdk configs configurable 

changelog.md, docs/1 Introduction/2 Install.md
When building from source we need a gopath, and this has thrown off some friends of mine.  I've added GOPATH to the build from source directions including a simple example.
=> docs: gopath for build from source

changelog.md, go.mod, go.sum, starport/templates/typed/launchpad/x/{{moduleName}}/handlerMsgCreate{{TypeName}}.go.plush, starport/templates/typed/launchpad/x/{{moduleName}}/keeper/{{typeName}}.go.plush, starport/templates/typed/launchpad/x/{{moduleName}}/types/MsgCreate{{TypeName}}.go.plush, starport/templates/typed/new_launchpad.go, starport/templates/typed/new_stargate.go, starport/templates/typed/stargate/x/{{moduleName}}/handler_{{typeName}}.go.plush, starport/templates/typed/stargate/x/{{moduleName}}/keeper/{{typeName}}.go.plush
For both Stargate and Launchpad, use a deterministic way to generate the ID of types on-chain (auto-incremented number)
=> fix(template): non-deterministic id for scaffolded types

go.mod, go.sum, starport/interface/cli/starport/cmd/network_proposal_approve.go, starport/interface/cli/starport/cmd/network_proposal_reject.go, starport/pkg/numbers/numbers.go, starport/pkg/numbers/numbers_test.go
network proposal approve/reject now can accept comma separeted proposal
ids.
resolves #453.
=> feat(cmd/network): add support for batch reviewals

go.mod, go.sum, starport/interface/cli/starport/cmd/build.go, starport/interface/cli/starport/cmd/network_chain_create.go, starport/interface/cli/starport/cmd/network_chain_join.go, starport/interface/cli/starport/cmd/relayer.go, starport/interface/cli/starport/cmd/serve.go, starport/pkg/spn/spn.go, starport/services/chain/chain.go, starport/services/chain/init.go, starport/services/chain/serve.go, starport/services/networkbuilder/blockchain.go, starport/services/networkbuilder/networkbuilder.go
* updated to latest SPN.
* removed the required of a source code for `network chain start` by
making `chain.New()` to not depend on a source code.
* fixed add-genesis-account for `network chain start` by not failing if
it is already added(it is already added by `network chain join`).
* move away add genesis account logic from `chain.CreateAccount()`.
solves #457.
tested with single validator.
=> refactor(network): to match with the latest workflow +fixes

.gitpod.yml, go.mod, go.sum, starport/interface/cli/starport/cmd/network_chain_join.go, starport/pkg/xchisel/xchisel.go, starport/services/networkbuilder/blockchain.go, starport/services/networkbuilder/config.go, starport/services/networkbuilder/networkbuilder.go
it is enabled automatically when CHISEL_ADDR env variable is set.
solves #455.
note:
I tested this on Gitpod with two validators and it worked as expected. Only thing, I had to copy one of the validator's Genesis to other one's before running `chain start`. Otherwise I receive some errors during start. This might be due to different timestamps (I remember seeing a related error) and/or disorder in the accounts array(need to overwrite with initial Genesis as discussed). cc/ @ltacker @fadeev
=> feat(network): optionally enable Chisel proxy

starport/services/networkbuilder/networkbuilder.go
fixes #475.
a: self validator
b: other validators
we run a Chisel client for each (b) in the same host where we run (a).
while doing so, every (b) gets same(127.0.0.1) ip address -but with a
unique port number.
this PR enables allowing to use same ip address for each (b).
=> fix(chisel): allow same ip address for p2p conns

starport/interface/cli/starport/cmd/network_chain_create.go, starport/pkg/xurl/xurl.go, starport/services/networkbuilder/networkbuilder.go
resolves #484.
following supported:
- network chain create https://github.com/org/repo
- network chain create git@github.com:org/repo.git
following not interpreted as a Git url because it can point to a local path in the fs:
- network chain create github.com/org/repo
=> feat(network/chain/create): support Git urls

.goreleaser.yml
This PR changes `snapcraft` configuration to use the `classic` confinement. Manual approval is still required though.
=> ci: update snapcraft config in goreleaser

starport/interface/cli/starport/cmd/network.go
=> fix(network): always require spn account name on account creation

.docker/Dockerfile.amd64, .pi/Dockerfile, changelog.md
Previously, the Dockerfile was copying a starport binary from my own personal fork of starport. It now copies the binary from our Docker image.
Closes #532
=> fix(pi): Dockerfile

.github/workflows/test-integration.yml, go.mod, go.sum, integration/cmd_serve_test.go, integration/tx_test.go, starport/services/chain/build.go
- Fix proto generation:
The proto generation step was performed with Launchpad version, `starport serve` was not working anymore for Launchpad version
- Add an integration test for `starport server` for Stargate version
- Fix `tx_test.go `:
`TestGetTxViaGRPCGateway` sends a message to get the tx of the grpc server and retry until it succeed. We didn't handle the server error therefore it was directly considered as successful and performed checks on incorrect retrieved data
=> fix: fix tx_test.go and proto generation for Launchpad version

.pi/build.sh
Makes line 87 always return true since it doesn't matter in a CI enviroment, and will always work on metal because for metal the build script is a loop.
=> fix(pi): target is busy

starport/templates/app/stargate/vue/package-lock.json, starport/templates/app/stargate/vue/package.json
On the current version of `@tendermint/vue` web scaffold doesn't work on Gitpod, because API URL is not properly constructed. This fixes the problem.
=> fix: web scaffold working on Gitpod

go.mod, go.sum, starport/pkg/gomodulepath/gomodulepath.go
=> fix: determining version number in go paths

starport/pkg/gomodulepath/gomodulepath.go, starport/pkg/gomodulepath/gomodulepath_test.go
Now, if you try to run `starport app github.com/alice/voter --sdk-version="launchpad"`, you will get project named "alice", not "voter".
=> feat(pkg/gomodulepath): add tests for paths with versions

integration/env_test.go
Remove the home directories created for blockchains in integration tests
=> test: cleanup blockchain home directories for integration tests

readme.md
develop branch tends to change a lot, and it is expected have some temporary bugs before each release. it would be nice to have docs to use the stable version by default.
=> refactor: use stable version of Starport in docs

.github/workflows/devices.yml
Each platform gets its own docker manifest so the :arm64 and :amd64 on the image tags are superfluous, as are having different names for the places where the cache lives.
Basically this will ensure that users do not need to use the :arm64 or :amd64 tag when pulling the container image, no matter which platform they're using.
=> fix: Use the platform flag correctly

go.mod, go.sum, starport/services/networkbuilder/networkbuilder.go
Use `[tmp]/spn-[chain-id]` for the directory of the source of the chain
The directory is overwrite if it already exist
This allows having less directories created and is convenient for Starport Network integration tests to modify the `config.yml` because the source path is deterministic
=> refactor: use a fixed-name dir for Starport Network chain sources

starport/templates/app/stargate/app/app.go.plush
Remove the fixed home directory we use in the workaround
Removing the workaround need to update the Cosmos SDK version https://github.com/tendermint/starport/pull/622, this is not possible now because the command line interface of the blockchain daemon has changed so we need to be able to support different command line interface depending on the Cosmos SDK version. I create an issue for this.
=> fix(template): use HomeDir from clientCtx RegisterTxService

docs/1 Introduction/1 Introduction.md, docs/1 Introduction/2 Install.md, docs/1 Introduction/3 Quickstart.md, docs/1 Introduction/4 Configuration.md, docs/2 Architecture/1 Introduction.md, docs/2 Architecture/5 Configuration.md
Added more info about how to configure a chain with `config.yml` and about `--sdk-version` flag. Some of the properties of `config.yml` are omitted on purpose (like server ports), because I don't think they should be considered "public" yet.
close https://github.com/tendermint/starport/issues/644
=> docs: config.yml and --sdk-version

go.mod, go.sum, starport/services/scaffolder/init.go, starport/services/scaffolder/module.go, starport/services/scaffolder/scaffolder.go, starport/services/scaffolder/type.go
The scaffolded generate code sometimes badly indented and on `starport app` we have a badly intended code that is automatically committed.
We run `go fmt` on the project so that the source is always well formatted.
=> feat(scaffolder): run fmt on scaffolder commands

.gitpod.yml, go.mod, go.sum, starport/interface/cli/starport/cmd/build.go, starport/interface/cli/starport/cmd/relayer.go, starport/interface/cli/starport/cmd/serve.go, starport/pkg/chaincmd/chaincmd.go, starport/pkg/chaincmd/runner/account.go, starport/pkg/chaincmd/runner/chain.go, starport/pkg/chaincmd/runner/runner.go, starport/pkg/cosmoscoin/coin.go, starport/pkg/cosmoscoin/coin_test.go, starport/pkg/cosmosfaucet/cosmosfaucet.go, starport/pkg/cosmosfaucet/http.go, starport/pkg/cosmosfaucet/transfer.go, starport/pkg/fswatcher/fswatcher.go, starport/pkg/xhttp/server.go, starport/services/chain/chain.go, starport/services/chain/conf/config.go, starport/services/chain/dev.go, starport/services/chain/serve.go, starport/services/networkbuilder/blockchain.go, starport/services/networkbuilder/networkbuilder.go, starport/services/networkbuilder/simulation.go
to transfer tokens from the faucet account to the requester account.
refactoring code from the original implementation: https://github.com/allinbits/cosmos-faucet.
related to https://github.com/tendermint/starport/issues/570.
the faucet server runs via Starport's Dev server and it is reachable through `/faucet` endpoint.
usage:
```yaml
...
faucet:
name: user1
...
```
And then make a _JSON_ `POST` req with following payload:
_http://localhost:12345/faucet_
```
{
"address": "..."
}
```
=> feat: add cosmosfaucet

docs/1 Introduction/1 Introduction.md, docs/1 Introduction/5 Genesis File.md, docs/1 Introduction/6 Starport IBC.md, docs/2 Architecture/2 Directory Structure.md, docs/2 Architecture/3 Standard Modules.md, docs/2 Architecture/4 Writing Custom Modules.md
Update more details for current default stargate version in the docs
=> docs: update docs stargate

docs/README.md
Quick fix to appropriate **Introduction.md** file under "3 - Starport" package
=> fix: starport-docs-tutorials fix reference to Introduction.md file

starport/templates/app/stargate/.gitignore
We used to have `frontend`, but now it's `vue`.
=> fix: change "frontend" to "vue" in gitignore

go.mod, starport/services/chain/build.go
Seems like standalone `starport build` command wasn't building proto. This PR solves that.
=> feat(cmd): build proto in build cmd

.pi/Dockerfile
Closes #677
I changed some edging some things in the image build process, and it left the binary in a different place and now that is fixed.
=> fix: Rpi ci

go.mod, go.sum, starport/interface/cli/starport/cmd/cmd.go, starport/interface/cli/starport/cmd/faucet.go, starport/pkg/chaincmd/runner/account.go, starport/services/chain/faucet.go, starport/services/chain/serve.go
to transfer coins from the configured faucet in the app's `config.yml` to the target account.
In order `starport faucet` to work, chain needs to be served first via `starport serve`.
Sample usage:
```
$ starport faucet -p ./mars [to-account-address] 100token,10stake
```
=> feat(cmd): add faucet command

starport/templates/app/launchpad/.github/workflows/pages.yml, starport/templates/app/launchpad/readme.md.plush, starport/templates/app/stargate/.github/workflows/pages.yml, starport/templates/app/stargate/readme.md.plush
This ad get hub pages automation to both the Stargate and launchpad templates.
It's fully auto, the user does not need to click a thing.
Also adds an addendum to readme.md in generated chains telling users how to turn on github pages
=> feat: gh pages automation

starport/services/chain/serve.go
Change `If the new code is no longer compatible with the saved state, you can reset the database by launching: starport serve --force-reset`
to:
`If the new code is no longer compatible with the saved state, you can reset the database by launching: starport serve --reset-once`
Because the user might not want to reset the state everytime if they just want to make the code compatible with the new dataformat
=> fix(serve): change printed start error message

starport/pkg/chaincmd/chaincmd.go
Remove the `keyring-backend` value provided in the `add-genesis-account` command to be compatible with old scaffolded chain interface.
This option is only used when you want to add a genesis account from a key name. This is a feature that is for now not used by the CLI (and I don't it will) therefore we can simply remove the option.
=> fix: starport network join not compatible with old scaffolded chain

docs/2 Architecture/5 Configuration.md, docs/6 Extra/CI.md, docs/6 Extra/Web UI on Github Pages.md, readme.md, starport/templates/app/stargate/readme.md.plush
* Moved non-essential information from readme in `docs/Extras`
* Added faucet, build, etc. into the config reference (some properties, like server ports, are omitted, because we may reconsider their location in the future, let's consider them "private" for now)
=> docs: readme in scaffold and config reference

starport/pkg/dirchange/dirchange.go, starport/pkg/dirchange/dirchange_test.go, starport/services/chain/serve.go
Remove from`HasDirChecksumChanged` from `dirchange` the side effects, it doesn't save the checksum anymore.
Checksums of the source and config are only saved once the app is built and initialized
=> fix: no rebuild on second serve

starport/templates/typed/new_launchpad.go, starport/templates/typed/new_stargate.go
Skip the frontend modification if the required path is not found instead of returning an error
=> fix: type scaffolding fails if there is no vue dir

starport/pkg/chaincmd/runner/chain.go, starport/pkg/chaincmd/runner/runner.go, starport/pkg/truncatedbuffer/truncatedbuffer.go, starport/pkg/truncatedbuffer/truncatedbuffer_test.go, starport/services/chain/serve.go
The error logs from Cosmos SDK apps are too extensive, we cannot print them directly
When the app fails to start on `starport serve`:
- Parse the error log output
- Check for specific pattern
- If the error is recognized, print the error details
- If not, the error may be caused by an incompatible previous saved state
=> fix: give a more descriptive error when the app fails to start with a known error

.pi/Dockerfile, .pi/build.sh
This fixes the build of the raspberry pi development environment.
Made the loopback device into a variable so that if there is a loopback device in use, there will not be any problems building. 
closes #726
=> fix: starport rpi dev env

Dockerfile
This needed some alpine air; changed the image from arch to alpine.  It should work identically.
=> fix: alpine-Dockerfile

starport/templates/app/stargate/x/{{appName}}/types/codec.go.plush, starport/templates/module/create/stargate/x/{{moduleName}}/types/codec.go.plush
Add `RegisterMsgServiceDesc` in `RegisterInterfaces` of the module codec to register all type_urls from the messages into the registry
=> fix: register Msg Service Desc in module codec

starport/interface/cli/starport/cmd/serve.go
There is one unnecessary dash character in the serve command line.
=> docs: rm unnecessary dash for cli flag description

starport/pkg/chaincmd/chaincmd.go
This PR fixes tx send command on launchpad versions
=> fix: add json output to launchpad send command on faucet

starport/ui/src/views/Welcome.vue
I built my first blockchain and noticed we had an extra space before the comma
=> fix: remove extra space from Welcome.vue 

starport/ui/src/views/Welcome.vue
close https://github.com/tendermint/starport/issues/788
changed link to go to the docs href="https://docs.cosmos.network/
=> fix: link on welcome screen to go to docs not the repo

docs/1 Introduction/2 Install.md
Give users an alternative path if they have no write permissions on `/usr/local/bin/`.
=> docs: Update install instructions

docs/5 Wasm Smart Contracts/3 Deploying your first contract.md
Just some changes to make it work.
```
docker run --rm -v "$(pwd)":/code \
--mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
--mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
cosmwasm/workspace-optimizer:0.10.7
```
```
appd tx wasm instantiate 1 '{ "name": "xrp", "symbol": "XRP", "decimals": 8, "mint": {"minter": "cosmos1vvvpnffcl4lzk7zfcr5y8zlp7hqmwuvjck2aq0", "cap": "99900000000"}, "initial_balances": [ { "address": "cosmos1vvvpnffcl4lzk7zfcr5y8zlp7hqmwuvjck2aq0", "amount": "12345678000"} ]}' --from alice --label xrp --gas 1000000 
```
=> docs: update CosmWasm docs for v0.14 and Stargate

docs/1 Introduction/1 Introduction.md
Cosmonauts World is deprecated now, in favor of the new ecosystem page on the Cosmos website.
=> Updated link to ecosystem projects

docs/1 Introduction/1 Introduction.md
aragon is no longer launching their own cosmos chain. removing from docs.
=> docs: remove aragon chain

starport/services/scaffolder/component.go, starport/services/scaffolder/message.go, starport/services/scaffolder/packet.go, starport/services/scaffolder/type.go
We were only verifying for the same kind of component if the name already exists. Now we prevent having a `type` and a `message` with the same name (which used to work and generated a code that doesn't compile)
=> fix: prevent duplicated component name

.github/workflows/goreleaser.yml, starport/ui/package-lock.json
since it is no longer needed to be a part of this process and modifies the source code.
also make sure we have the latest dev ui dist in the source code.
=> fix(ci): rm ui build step

starport/templates/typed/stargate/x/{{moduleName}}/types/messages_{{typeName}}.go.plush, starport/templates/typed/stargate_legacy/x/{{moduleName}}/types/messages_{{typeName}}.go.plush
When using "starport type" the generated messages_type.go do not match the expected results.
The expected generated results should be
```
var _ sdk.Msg = &MsgDeleteType{}
func NewMsgDeleteType...
```
instead, the actual generated file contains 
```
var _ sdk.Msg = &MsgCreateType{}
func NewMsgDeleteType...
```
=> fix: messages scaffolding, type implementation mistake

starport/interface/cli/starport/cmd/network.go
Use `nightly.starport.network` to support `launch` module renaming on `spn`
=> fix: use nightly.starport.network

.github/workflows/goreleaser.yml
=> fix(ci): remove unused snap

docs/99 Extra/1 Adding Support for CosmWasm.md, docs/README.md
@fadeev I didn't realize our README was wonky (oops, my mistake) so here's a PR to fix the table of contents for the Starport docs
I manually crafted the top-level table of contents for this update. Teach me if there is an automated TOC option. 
I use the in-file Atom text editor Markdown package to generate an in-file toc, but can use some coaching for readme toc generation.
TOC links to go:
- the folder if there were multiple files
- the file if there was a single file
=> docs: Fix Starport readme TOC

starport/services/networkbuilder/blockchain.go, starport/services/networkbuilder/networkbuilder.go, starport/services/networkbuilder/verification.go
Check the genesis URL of a chain before joining it. A method `verifyChain` is called inside `Init`. Though we may refactor this method in the future, the idea is to have a generalistic method `verifyChain` to verify the static information of the chain. This method should be called before any operation with chains of Starport Network.
For test purpose, the chain `toast2` of `nightly` has a incorrect hash for the genesis
=> feat(network): verify chain and custom genesis URL

starport/templates/typed/genesis.go, starport/templates/typed/indexed/new_stargate.go
Introduce a function that patches `types/genesis.go` to make it compatible with current scaffolding logic.
Since other template inconsistencies could arise in the future, it could make sense to introduce a package `patch` in `template` that centralize all of them.
The difference between the current "modify" logic and the notion of patch is:
- modify functions only modify the code from the placeholders inside it
- patches can also modify other parts not only related to placeholders
For testing, the following app is scaffolded with 0.14.0:
https://github.com/lubtd/earth
=> fix: type generation error with <v0.14.0 apps

.gitpod.Dockerfile, .gitpod.yml, go.mod, go.sum, scripts/test-vue, starport/services/chain/serve.go
Bumps template to v0.1.46 which includes @starport/* v0.1.46
Fixes https://github.com/tendermint/starport/issues/1031
Also fixes error in WS env var and build errors when using test-vue script
=> fix: Bump template to v0.1.46

.goreleaser.yml, scripts/data/gen-nodetime/package.json, scripts/gen-nodetime, starport/pkg/nodetime/binary_linux_arm64.go
we don't have a proper environment to build arm binaries for nodetime yet, until we
have one let's rm arm support for now.
=> refactor(nodetime): rm arm support

starport/cmd/relayer.go, starport/cmd/relayer_lowlevel.go, starport/pkg/cosmosgen/generate_javascript.go, starport/pkg/nodetime/nodetime.go, starport/pkg/nodetime/ts-proto/tsproto.go
which are:
* `starport relayer lowlevel ibc-setup`
* `starport relayer lowlevel ibc-relayer`
and remove the old `starport relayer rly` from the go-relayer.
=> feat(cmd/relayer): wire lowlevel confio/relayer commands

docs/intro/install.md
This sounds silly, but on some systems `make -C starport install` fails with `make: *** No rule to make target build.  Stop.`. I've noticed this on one virtual server and Tobias had this problem on macOS. Maybe an old version of `make`, but `cd starport && make install` works reliably everywhere.
=> docs: update install.md

.gitignore, starport/templates/app/stargate/go.mod.plush, starport/templates/module/create/ibc.go, starport/templates/module/create/ibc/x/{{moduleName}}/types/expected_keeper_ibc.go.plush, starport/templates/module/create/stargate/x/{{moduleName}}/keeper/keeper_test.go.plush, starport/templates/module/placeholders.go, starport/templates/typed/stargate/component/x/{{moduleName}}/keeper/{{typeName}}_test.go.plush
This PR has only setup code for the keeper that is initialized when a module is created. And tests for non-indexed type. The plan is to reuse `KeeperSuite` for `QuerierSuite` and `MsgServerSuite`.
I don't see any reasons to use table tests so far, maybe only as an example of how they can be written. Maybe I will change my opinion when I will extend this stuff.
I didn't add any new tests, since the change already covered by integration tests, that execute `go test ./...`.
related: https://github.com/tendermint/starport/issues/715
=> feat: basic unit tests for non-indexed type

starport/templates/module/create/stargate/x/{{moduleName}}/types/query.go.plush, starport/templates/typed/stargate.go
Remove the `types/query.go` file from scaffolding that was only used with REST querier
=> fix: remove query routes

starport/templates/typed/indexed/stargate/component/x/{{moduleName}}/keeper/grpc_query_{{typeName}}_test.go.plush, starport/templates/typed/indexed/stargate/component/x/{{moduleName}}/keeper/{{typeName}}_test.go.plush, starport/templates/typed/indexed/stargate/messages/x/{{moduleName}}/keeper/msg_server_{{typeName}}_test.go.plush
related to: https://github.com/tendermint/starport/issues/715
=> feat(templates): unit tests for indexed type

.github/workflows/test-integration.yml
later we'll be enabling parallel tests for testing things faster.
=> chore(ci): run integration tests on self-hosted runner

integration/cmd_message_test.go, starport/templates/message/stargate.go
A import in `/types/codec.go/` was replaced with `Replace` instead of `ReplaceOnce` and `MsgServer` in `handler.go` as well. This made it impossible to scaffold two messages in the same module
Use `ReplaceOnce` instead of `Replace`
=> fix: cannot create two messages in the same module

starport/templates/ibc/packet.go, starport/templates/ibc/packet/component/x/{{moduleName}}/keeper/{{packetName}}.go.plush, starport/templates/module/create/ibc/x/{{moduleName}}/module_ibc.go.plush, starport/templates/module/create/stargate/x/{{moduleName}}/types/codec.go.plush
Allows to use the tutorial with Starport with `ts-relayer`
=> fix: use JSON marshalling to encode IBC packets and acknowledgements when scaffolding IBC modules and packets

starport/templates/app/stargate/.github/workflows/build.yml.plush
This brings go to 1.16 in the scaffolded github action, so that it does not fail when asked to embed docs.
=> fix(templates/ci): upgrade go version

.github/CODEOWNERS
let's see if this will fix it. before, other codeowners were not being automatically added as reviewers to PRs that updates .md files.
=> fix(codeowners): make global owners to get added to all prs

readme.md
* v0.16
* Chain name
* Channel on Discord
=> docs: Minor updates to the readme

docs/configure/reference.md
* Added `client.openapi`
* Removed 12345 from `host`
@barriebyron do you think you can set up your editor to format tables like in this PR? It's a bit easier to read when in text editor, in my opinion. This is the default way VS Code formats tables in Markdown.
=> docs: Added client.openapi, removed 12345

starport/pkg/localfs/save.go, starport/pkg/nodetime/nodetime.go, starport/pkg/protoc/protoc.go
print the command name while executing temp binaries.
=> feat: add more debug info

changelog.md, starport/cmd/cmd.go, starport/pkg/cmdrunner/cmdrunner.go, starport/pkg/goenv/goenv.go, starport/services/chain/build.go
=> fix(env): make sure that $PATH has Go bin set

docs/intro/install.md
A good chunk of questions we get on Discord is about `appd: command not found`. Let's mention this more explicitly in the install doc.
=> docs: install, mention setting go env vars

starport/cmd/build.go
edits I didn't parse during the (quick!) cycle of https://github.com/tendermint/starport/pull/1237 
this --release flag is a game-changer. Starport is growing up!
=> docs: build.go suggested edits for optional --release flag 

Dockerfile
This PR is intended to address #1202 by switching users earlier.
Using `starport/cli:latest`
Using my build:
=> fix(dockerfile): switch user earlier to mitigate perms issues

docs/getting-started/index.md
Replaced `x/blog/query.proto` with `proto/blog/query.proto`.
=> docs: fix typo in getting started

integration/env_test.go, starport/cmd/chain.go, starport/cmd/chain_build.go, starport/cmd/chain_faucet.go, starport/cmd/chain_serve.go, starport/cmd/cmd.go
move 'serve', 'build' and 'faucet' commands to under 'chain'.
related to #1244.
=> refactor(cmd): add 'chain' command and

go.mod, go.sum
- Remove deprecated warning for Mac 10.15+ versions;
- Bump `go-keychain` version;
- Replace `keybase/go-keychain` with `99designs/go-keychain` to avoid deprecated warnings;
```shell
$ make install
```
=> fix(templates): remove deprecated warning for Mac 10.15+

starport/pkg/clispinner/clispinner.go
Closes #1265
Fix the data race condition for the CLISpinner. 
The current spinner has some data race conditions, and using the locks provided by the package can stuck the main goroutine and stop the application. The issue can be reproduced by calling a `lock` after calling the `stop` method.
Scaffolding a new application with the Golang `-race` parameters active
=> fix: solve the race condition for the clispinner

.gitpod/readme.md, readme.md, starport/cmd/scaffold_chain.go, starport/services/chain/serve.go, starport/templates/app/stargate/readme.md.plush
Update `starport app` -> `starport scaffold app`
`starport serve` -> `starport chain serve`
In some area where the command is mentioned
=> fix: update some part with the new command name format

starport/cmd/scaffold.go, starport/cmd/scaffold_vue.go, starport/services/scaffolder/init.go
=> feat(cmd/scaffold): add vue command

docs/cli/index.md, integration/cmd_app_test.go, starport/cmd/scaffold_chain.go
Signed-off-by: Sonia Singla <soniasingla.1812@gmail.com>
Rename --no-default-module to --no-module.
Fixes #1345
=> improvement(cmd): rename --no-default-module to --no-module

contributing.md
Add a section about `Feedback/Issues` in the Contributing File 🤗
=> docs(contribution): add Feedback/Issues

starport/templates/app/stargate/.github/workflows/release.yml
Because chains scaffold with Starport uses _tendermint/spm_ and this adds `wasm` entry to chain's `go.sum`, therefore chain cannot compile to arm64.
=> chore(templates/ci): do not build arm binaries

starport/cmd/generate_vuex.go, starport/services/chain/generate.go
whether if 'client' section presents or not in the 'config.yml'.
=> fix(cmd/generate): vuex and openapi cmds should work

starport/pkg/protoanalysis/parser.go
related to invalid .proto files.
instead of just returning with the parsing error, path info for the
related file also included. e.g.:
```
file: /home/ilker/Documents/code/src/github.com/tendermint/starport/local_test/mov/proto/mov/tx.proto: <input>:17:1: found "}" but expected [field =]
```
related to https://github.com/tendermint/starport/issues/1342.
=> feat(codegen): add file path for code generation errs

integration/cmd_map_test.go, starport/templates/typed/indexed/stargate.go
The rpc query path used a wrong naming convention for the index name by setting all characters to lowercase.
For example running `starport s map foo --index fooBar` fails
We set it to lower camel case so it can correctly retrieve the field in the type.
We also add a test to include this case.
=> fix: error when using a custom index for map that includes more than two word

starport/cmd/chain_init.go, starport/services/chain/init.go, starport/services/chain/serve.go, starport/services/config.go, starport/services/networkbuilder/blockchain.go, starport/services/networkbuilder/config.go, starport/services/networkbuilder/networkbuilder.go
Prevent initializing accounts from the config when using a chain from Starport Network because in this case we must create our own account
Another fix is to create `.starport` config directory when initializing `networkbuilder` config
This fixes currently known issues for Starport Network usage for `0.17.0`
=> fix(services/chain): don't init accounts from config for SPN chains

docs/intro/docker.md, docs/intro/go.md, docs/intro/install.md
This document adds the installation process of go across the different operating systems.
**Note** The Starport content is moving from the https://github.com/cosmos/sdk-tutorials/ repo to the https://github.com/tendermint/starport/ repo to consolidate in our best place.
[Starport docs structure](https://www.notion.so/allinbits/Starport-Content-Outline-draft-41ad2d55b6244da4a9710d990df5c882) are in Notion
=> docs: how to install go

starport/templates/typed/stargate/component/x/{{moduleName}}/keeper/{{typeName}}.go.plush
`TypeName.LowerCamel` instead of `<%= TypeName.LowerCamel %>`
=> fix: small comment typo in `list` template

starport/pkg/cosmosanalysis/module/module.go, starport/pkg/cosmosanalysis/module/module_test.go, starport/pkg/cosmosanalysis/module/testdata/planet/go.mod, starport/pkg/cosmosanalysis/module/testdata/planet/proto/planet/planet.proto, starport/pkg/cosmosanalysis/module/testdata/planet/x/planet/types/types.go, starport/pkg/cosmosgen/generate.go
closes #1342
- Compile proto only from `build.proto.path`; instead, compile all proto files from the project.
- Specify the proto folder to be analyzed.
- Compile [Ethermint](https://github.com/tharsis/ethermint) with proto files generated by tests:
```shell
$ git clone git@github.com:tharsis/ethermint.git
$ cd ethermint && make install
$ cd tests/solidity && yarn install
$ cd ../..
$ starport c serve -v
```
=> fix(cosmosanalysis/module): discover proto files only in certain dirs

Makefile, go.mod, go.sum, starport/cmd/cmd.go, starport/cmd/starport/main.go, starport/internal/tools/gen-cli-docs/main.go, starport/internal/version/version.go
and print instructions to upgrade.
this is how it looks like:
```
·
· 🛸 Starport "v0.16.2" is available!
·
· If you're looking to upgrade check out the instructions: https://docs.starport.network/intro/install.html#upgrading-your-starport-installation
·
··
Starport is a tool for creating sovereign blockchains built with Cosmos SDK, the world’s
most popular modular blockchain framework. Starport offers everything you need to scaffold,
test, build, and launch your blockchain.
To get started, create a blockchain:
starport scaffold chain github.com/cosmonaut/mars
Usage:
starport [command]
Available Commands:
scaffold    Scaffold a new blockchain, module, message, query, and more
chain       Build, initialize and start a blockchain node or perform other actions on the blockchain
generate …
```
=> feat(cmd): check for a new version

starport/pkg/ctxreader/ctxreader.go
closes #1303
All cancelable readers reach the timeout deadline make a data race condition to close the `Read` method.
- Fix the data race condition using channels;
- Return the Reader error;
Run the unit test: ` go test -v -race github.com/tendermint/starport/starport/pkg/ctxreader/...`
=> fix(pkg/ctxreader): Fix the data race after the context timeout

starport/pkg/gocmd/gocmd.go, starport/services/scaffolder/module.go, starport/templates/app/stargate/go.mod.plush, starport/templates/module/import/stargate.go
depends on https://github.com/tendermint/spm-extras/pull/1, https://github.com/tendermint/spm/pull/2.
we also need to make release for spm and spm-extras.
and go mod tidy this PR after.
=> refactor(templates): use wasm from tendermint/spm-extras

.gitpod.yml
gitpod now makes all the ports private by default. this pr makes the p2p conn proxy port open.
=> fix(gitpod/chisel): fix p2p conn establishment

starport/cmd/relayer.go
let's not use Latin, so change "via" to "by using"
per best practices for plain language and https://developers.google.com/style/abbreviations?hl=en#dont-use 
Use "Connect" for parallel construction, other verbs are imperative language, so let's make the same
=> fix(relayer.go): Change Latin "via" to "by using" 

starport/internal/tools/gen-cli-docs/main.go
Since we merge the CLI ref PR only before the release is cut, we don't need to mention that the reference describes the upcoming release. It actually describes the current version of Starport.
=> docs: remove a note about upcoming release

docs/cli/index.md, docs/intro/install.md, starport/cmd/tools.go
See the deploy preview at https://deploy-preview-1421--starport-docs.netlify.app/cli/#starport-tools-completions
=> docs(cli): add docs for starport tools completions cmd

go.mod, starport/cmd/account.go, starport/cmd/account_create.go, starport/cmd/account_delete.go, starport/cmd/account_export.go, starport/cmd/account_import.go, starport/cmd/account_list.go, starport/cmd/account_show.go, starport/cmd/cmd.go, starport/cmd/scaffold_chain.go, starport/pkg/cliquiz/question.go, starport/pkg/cosmosaccount/cosmosaccount.go
Added `starport account` command to manage accounts.
Next, I'll use this feature in `starport relayer` to see how these two will work together and do needed improvements on the accounts feature accordingly.
=> feat(cmd): init accounts command

starport/templates/ibc/packet/messages/x/{{moduleName}}/client/cli/tx_{{packetName}}.go.plush, starport/templates/message/stargate/x/{{moduleName}}/client/cli/tx_{{msgName}}.go.plush, starport/templates/query/stargate/x/{{moduleName}}/client/cli/query_{{queryName}}.go.plush, starport/templates/typed/indexed/stargate/component/x/{{moduleName}}/client/cli/query_{{typeName}}.go.plush, starport/templates/typed/indexed/stargate/messages/x/{{moduleName}}/client/cli/tx_{{typeName}}.go.plush, starport/templates/typed/singleton/stargate/messages/x/{{moduleName}}/client/cli/tx_{{typeName}}.go.plush, starport/templates/typed/stargate/messages/x/{{moduleName}}/client/cli/tx_{{typeName}}.go.plush
Based on this fix on `spn` https://github.com/tendermint/spn/pull/241
The cli command parameters in prompt help should use kebab case
=> fix(template): use kebab case for cli command parameter 

go.mod, starport/pkg/cosmosclient/cosmosclient.go, starport/pkg/spn/spn.go
@toschdev I heard that you're instered in programatically accessing sdk based chains in Go.
One of the requirements of doing this is accessing to `client.Context`, which this PR provides. 
Please see [this](https://gist.github.com/ilgooz/0d87818184e9c0802c97753c47d7f47a) example of querying bank module.
For creating and broadcasting txs you can refer to [this](https://github.com/tendermint/starport/blob/12189d4fefc1806ed57e514522549ea4641273f7/starport/pkg/spn/spn.go). You can search for keywords like `clientCtx`, `cosmosclient.NewFactory` and `cosmosclient.NewContext`.
When you're dealing with tx's you need to set the keyring to `clientCtx` like this:
```go
clientCtx = clientCtx.WithKeyring(client.NewKeyringFromBackend(clientCtx, "test"))
```
=> feat(pkg): add cosmosclient pkg

changelog.md, integration/cmd_message_test.go, starport/cmd/scaffold_message.go, starport/services/scaffolder/message.go, starport/templates/message/message.go, starport/templates/message/options.go, starport/templates/message/stargate.go, starport/templates/message/stargate/x/{{moduleName}}/types/message_{{msgName}}.go.plush
The `--signer` flag for `message` allows to determine a custom name for the signer of the message instead of "creator"
=> feat(cmd/message): add `--signer` flag

starport/pkg/field/field.go, starport/templates/typed/indexed/stargate.go, starport/templates/typed/indexed/stargate/component/proto/{{moduleName}}/{{typeName}}.proto.plush, starport/templates/typed/singleton/stargate/component/proto/{{moduleName}}/{{typeName}}.proto.plush, starport/templates/typed/singleton/stargate/component/x/{{moduleName}}/client/cli/query_{{typeName}}_test.go.plush, starport/templates/typed/singleton/stargate/component/x/{{moduleName}}/keeper/{{typeName}}_test.go.plush, starport/templates/typed/stargate/component/proto/{{moduleName}}/{{typeName}}.proto.plush, starport/templates/typed/stargate/component/x/{{moduleName}}/client/cli/query_{{typeName}}_test.go.plush, starport/templates/typed/stargate/component/x/{{moduleName}}/keeper/{{typeName}}.go.plush, starport/templates/typed/stargate/component/x/{{moduleName}}/keeper/{{typeName}}_test.go.plush, starport/templates/typed/typed.go
closes #1362
Remove type `Creator` field for internal types if `--no-message` flag is enable;
- Scaffold types with the messages:
```shell
$ starport scaffold chain github.com/cosmonaut/test && cd test
$ starport s single single-type desc
$ starport s map map-type desc --index addr
$ starport s list list-type desc
```
- Scaffold types without the messages:
```shell
$ starport s single single-type-no-msg desc --no-message
$ starport s map map-type-no-msg desc --index addr --no-message
$ starport s list list-type-no-msg desc --no-message
```
=> feat(proto): Remove type `Creator` field for internal types

starport/services/scaffolder/oracle.go
closes #1481
closes #1482
Create a method to install a specific `bandchain` version to avoid `cosmos-sdk` version conflicts.
- Scaffold a chain and run the tests:
```shell
$ starport s chain github.com/cosmonaut/test
$ starport s module consuming --ibc
$ starport s band oracleone --module consuming
```
=> fix(oracle): add a specific `bandchain` pkg version to avoid `cosmos-sdk` version conflicts

starport/pkg/cosmosanalysis/module/module_test.go, starport/pkg/localfs/search_test.go, starport/templates/typed/indexed/stargate/tests/component/x/{{moduleName}}/client/cli/query_{{typeName}}_test.go.plush, starport/templates/typed/indexed/stargate/tests/component/x/{{moduleName}}/keeper/grpc_query_{{typeName}}_test.go.plush, starport/templates/typed/indexed/stargate/tests/component/x/{{moduleName}}/keeper/{{typeName}}_test.go.plush, starport/templates/typed/indexed/stargate/tests/messages/x/{{moduleName}}/keeper/msg_server_{{typeName}}_test.go.plush, starport/templates/typed/singleton/stargate/component/x/{{moduleName}}/keeper/{{typeName}}_test.go.plush, starport/templates/typed/singleton/stargate/messages/x/{{moduleName}}/keeper/msg_server_{{typeName}}_test.go.plush, starport/templates/typed/stargate/component/x/{{moduleName}}/client/cli/query_{{typeName}}_test.go.plush, starport/templates/typed/stargate/component/x/{{moduleName}}/keeper/grpc_query_{{typeName}}_test.go.plush, starport/templates/typed/stargate/component/x/{{moduleName}}/keeper/{{typeName}}_test.go.plush, starport/templates/typed/stargate/messages/x/{{moduleName}}/keeper/msg_server_{{typeName}}_test.go.plush
closes #1422
use the `require` package from `testify` instead of the `assert` package for the unit tests.
- Scaffold a chain and run the tests:
```shell
$ starport scaffold chain github.com/cosmonaut/test
$ go test -v ./...
```
=> feat(template): replace `assert` with `require` from `testify` packages

go.mod, go.sum, starport/cmd/cmd.go, starport/cmd/network.go, starport/cmd/version.go, starport/internal/version/version.go, starport/pkg/docker/docker.go, starport/pkg/gitpod/gitpod.go, starport/services/networkbuilder/blockchain.go, starport/services/networkbuilder/networkbuilder.go
```
Starport version:	development
Starport build date:	2021-08-18T14:31:33
Starport source hash:	a2b74e1862524077b836d3670826dfb3f66a3d04
Your os:		linux
Your arch:		amd64
Your go version:	go version go1.16.4 linux/amd64
Your uname -a:		Linux ubuntu 5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Your cwd:		/home/ilker/Documents/code/src/github.com/tendermint/starport
Is on Gitpod:		false
Is in Docker:		false
```
close https://github.com/tendermint/starport/issues/1203
=> feat(cmd/version): provide detailed info

starport/pkg/cosmosgen/cosmosgen.go, starport/pkg/cosmosgen/generate.go
When trying to integrate starport with my application I got the following error:
```
[STARPORT] 🛠️  Building proto...
[STARPORT] cannot build app:
[STARPORT] 
[STARPORT]      go.mod has missing proto modules
```
This seems to happen because of the hardcoded cosmos-sdk path in https://github.com/tendermint/starport/blob/develop/starport/pkg/cosmosgen/generate.go#L14, along with my application replacing the cosmos-sdk in the go.mod file.
This PR allows replacing the cosmos-sdk import path if a custom one is defined in the go.mod file, or keep using the default path otherwise.
=> fix(cosmosgen): handle replaced cosmos-sdk

starport/pkg/multiformatname/multiformatname.go, starport/pkg/multiformatname/multiformatname_test.go, starport/services/scaffolder/component.go, starport/services/scaffolder/message.go, starport/services/scaffolder/module.go, starport/services/scaffolder/oracle.go, starport/services/scaffolder/packet.go, starport/services/scaffolder/query.go, starport/services/scaffolder/type.go
close #1469
Fix scaffold components with suffix `test`  Go understands the `_test.go` suffix as a test file. This PR checks the suffix and shows a message to the user.
```shell
$ starport s map map-test first second third:uint --index idOne,idTwo:uint,idThree
$ starport c serve -v
```
=> fix(scaffolder): prevent scaffolding types with suffix `test`

starport/templates/module/create/ibc.go, starport/templates/module/create/stargate.go, starport/templates/module/create/stargate/x/{{moduleName}}/keeper/keeper.go.plush, starport/templates/module/create/stargate/x/{{moduleName}}/module.go.plush, starport/templates/module/create/stargate/x/{{moduleName}}/types/errors.go.plush, starport/templates/module/create/stargate/x/{{moduleName}}/types/keys.go.plush, starport/templates/module/placeholders.go
Prevent scaffolding ibc placeholders for non-IBC modules to make non-IBC module code cleaner.
Remove placeholder for some places where replacement is short and can be added inline in the template
=> fix(template/module): prevent scaffolding ibc placeholders for non-IBC modules

starport/templates/module/create/ibc.go, starport/templates/module/create/stargate/proto/{{moduleName}}/genesis.proto.plush, starport/templates/module/create/stargate/x/{{moduleName}}/genesis.go.plush, starport/templates/module/create/stargate/x/{{moduleName}}/types/genesis.go.plush, starport/templates/module/placeholders.go
Remove the extra placeholders used for IBC modules in `genesis.go`, `types/genesis.go` and `genesis.proto`
=> fix(template): remove extra placeholders in genesis files

docs/guide/blog.md
Right now `types.RegisterQueryHandlerClient` is used too early (in the "Create post" section), and it throws an error.`
> types.RegisterQueryHandlerClient` is needed for querying, and it needs `query.proto` to be populated before `protoc-gen-grpc-gateway` generates `query.pb.gw.go`, which contains RegisterQueryHandlerClient.
=> docs: Fix the blog tutorial

docs/README.md
improve title and add maintenance to the virtues
I always get distracted when I see the preview of Starport docs with "Introduction to Starport"
let's change it to "Starport CLI" or even just "Starport"
=> docs: fix title

docs/guide/hello.md
thanks to Simon for asking about a murky bit in the docs, we need to add context to the imports
from this Slack convo in #devx https://allinbits.slack.com/archives/C014GFM3FRQ/p1632228436124700?thread_ts=1632227946.123000&cid=C014GFM3FRQ
=> docs(hello.md): fix misleading context import step

changelog.md, starport/chainconf/config.go, starport/pkg/goanalysis/goanalysis.go, starport/services/chain/build.go
added `build.main` field to config.yml for apps to specify the path of their chain's main package. This is only required to be set when an app contains multiple main packages.
to test use: https://github.com/notional-labs/dig. it has `./cmd/digd` and `./airdrop` main packages.
=> feat: add an option to specify path of chain's main pkg

docs/kb/config.md
add https://github.com/tendermint/starport/blob/develop/docs/kb/config.md#configyml-reference
closes https://github.com/tendermint/starport/issues/1617 
for update to https://docs.starport.network/kb/config.html
=> docs: add build.main to kb/config.md

starport/templates/typed/list/genesis.go, starport/templates/typed/map/stargate.go
Use `require.ElementsMatch` to assert array instead of `require.Len` and `require.Subset`
=> fix(templates): use `ElementsMatch` in genesis tests for types

starport/templates/typed/list/stargate/component/x/{{moduleName}}/keeper/grpc_query_{{typeName}}_test.go.plush, starport/templates/typed/map/stargate/tests/component/x/{{moduleName}}/keeper/grpc_query_{{typeName}}_test.go.plush
Add an assertion in grpc query tests for list and map that the All query returns all elements with `ElementsMatch`
=> fix(templates): add missing assertion in grpc query tests

starport/cmd/cmd.go
I agree with @barriebyron that it looks better without the quotes.  There are no other impacts to the modification.
=> chore(cmd): simplify version display on Starport's update message

docs/kb/band.md
The Bandchain team asked to change the relayer port from `26657` to `80`. Both are working.
- Use the port `80` instead of the `26657`;
- Fix typo for starport command;
=> fix(docs/band): Update the bandchain relayer sourc port

docs/kb/band.md
The proto message namespace is wrong for package and option into the `gold_price.proto` file in the bandchain tutorial. Also, the path of the files are wrong too.
=> fix(bandchain): Fix proto message for bandchain gold price tutorial

starport/services/network/path.go, starport/services/network/path_test.go
Implement a utility method that returns the default chain home `~/spn/<launchID>` in this PR since it should be used for almost all command
=> feat(`network`): implement method to get chain home

go.mod, go.sum, starport/templates/app/stargate/go.mod.plush
- Update Cosmos SDK version to `0.44.1` to prevent the IAVL race condition issue that poses a problem for front-end development
- Bump `tendermint/vue` to `v0.1.54`
=> chore: release v0.18.4

docs/guide/loan.md
* Replaced `sdkerrors.ErrWrongLoanState` with `types.ErrWrongLoanState`, otherwise the chain doesn't build.
=> docs: Fix the loan tutorial

docs/guide/install.md
clarify the docs for installing Starport on macOS with M1
https://deploy-preview-1815--starport-docs.netlify.app/guide/install.html#installing-starport
=> docs: fix the brew install to exclude M1 chip on macOS

go.mod, go.sum, starport/pkg/chaincmd/chaincmd.go, starport/pkg/cosmosclient/cosmosclient.go
this is useful if tx for faucet transfer not sent in the `sync` mode.
* pkg/cosmosclient: improve faucet defaults.
* pkg/cosmosfaucet: ensure that transfer tx uses `syncA mode.`
=> fix(pkg/cosmosclient): ensure account has funds after faucet transfer

starport/services/network/request.go, starport/services/network/request_test.go
When statically verifying a Add Validator request, convert the address in the gentx to `spn` to match the one stored on-chain
=> fix(cmd/network/request/approve): use `spn` address prefix for static request verification

starport/pkg/cosmosgen/generate_go.go
When I run `scaffold chain {id}`, it caused `cannot copy path error`.
I found it weird logic to handle error right after copying path from tmp to `appPath`.
I've fixed to return error only if copy causes an error.
=> fix(`scaffold chain {id}`): fixed error handler for generated path copy

starport/services/network/networkchain/prepare.go
Add the `unsafe-reset-all` command in `prepare` so the chain has always a fresh database once prepared
=> fix(`network chain prepare`): add `unsafe-reset-all` command

docs/contributing/index.md
On Line 20 of this file, the link to see the current issues needing fix was broken. I replaced the broken path file with a static link, as per Barrie's instructions.
=> docs: fixed broken link to Issues page

starport/templates/module/create/simapp/x/{{moduleName}}/module_simulation.go.plush
Fix issue to run a simulation when the module has int32 types for the params fields.
Scaffold a module with params:
```shell
starport scaffold chain github.com/cosmonaut/mars --no-module && cd mars && \
starport scaffold module launch --params minLaunch:uint,maxLaunch:int,chainDescription
```
Run the simulation:
```shell
starport c simulate --numBlocks 200 --blockSize 50
```
this error will appear:
```
Simulating... block 3/200, operation 0/196.--- FAIL: BenchmarkSimulation
simulate.go:300: error on block  3/200, operation (90/172) from x/gov:
failed to execute message; message index: 0: key: MaxLaunch, value: "0", err: json: cannot unmarshal string into Go value of type int32: failed to set parameter: invalid proposal content [cosmos/cosmos-sdk@v0.44.5/x/gov/keeper/proposal.go:24] …
```
=> fix(simapp): fix run simulation with randomized params

integration/map/cmd_map_test.go, integration/other_components/cmd_query_test.go, starport/services/scaffolder/component.go, starport/services/scaffolder/query.go, starport/templates/field/field.go, starport/templates/query/stargate.go, starport/templates/typed/map/stargate.go
To follow the proto standard we set the proto message fields as `Snake` case
However, for a field name that contains a full uppercase component: `postID`, the proto field is `post_id` and then the generated code from proto is `PostId` while our `LowerCamel` conversion set it to `postID`, making some inconsistency in the code
This PR set back the proto field to camel case `postID` so that the generated field will be `PostID`
We're unfortunately out of the proto standard, this PR is a quickfix. The workaround would be to generate `postId` with our camel case conversion but then we would be out of this standard as well
Other fixes
- add the query's request fields into the rpc URL for the `starport s query` command
- prevent using custom type as query-s request field
=> fix(`template`): inconsistency with proto generated code and camel case

readme.md
The Discord link mentioned in the `readme` file is not correct.
=> docs: fix Discord link

changelog.md, docs/migration/index.md
- omit punctuation from end of headings (remove colon)
- omit punctuation from end of list items (we had mostly sentence fragments, so let's omit throughout)
- omit italics from version references, emphasis is not required see https://docs.starport.com/migration/v0.18.html
- provide actionable numbered steps for migration
@ilgooz let's go through migration doc and other changes to make sure I didn't inadvertently introduce technical inaccuracy
=> docs: changelog and migration doc edits for consistency and style

docs/contributing/index.md, docs/contributing/templates/concept_template.md, docs/contributing/templates/readme.md, docs/contributing/templates/tutorial-template.md, docs/kb/config.md, docs/kb/docker.md, docs/kb/frontend.md, docs/kb/genesis.md, docs/kb/index.md, docs/kb/params.md, docs/kb/proto.md, docs/kb/relayer.md, docs/kb/scaffold-chain.md, docs/kb/serve.md, docs/kb/simapp.md, docs/kb/types.md
We have a variety of compliance with the Title Case heading style we inherited from the Cosmos SDK docs and tutorials.
This PR changes our Titles and Headings to use Sentence case to establish a convention before we start adding more Starport Network docs 
We'll follow these guidelines:
> In document titles and headings, use sentence case. That is, capitalize only the first word in the title, the first word in a subheading after a colon, and any proper nouns or other terms that are always capitalized a certain way.
> Use sentence case for all the elements in a table: contents, headings, labels, and captions.
https://developers.google.com/style/capitalization?hl=en#capitalization-in-titles-and-headings
Scope: Knowledge Base articles
=> docs: minor edits and change all headings to use Sentence case

go.mod, go.sum, starport/pkg/cosmosgen/template.go, starport/pkg/cosmosgen/templates/vuex/store/index.ts.tpl
The `swagger-typescript-api` library used to generate the API class when generating vuex/js code uses a different ruleset for camelCasing than `strcase` in golang.
This PR uses `https://github.com/takuoki/gocase` to revert Go's common initialisms in order for resulting strings to match.
=> fix(codegen): adjust Go's camelCasing for templates to match JS' 

docs/migration/index.md
IBC-go provides really great migration docs, best to link them instead of linking to the PR that changes the template.
=> docs(migration): improve v0.19.2 upgrade guideline 

starport/cmd/network_chain_list.go, starport/cmd/network_request_list.go, starport/services/network/queries.go
Remove the `Fetching chain information...` that appears sometimes when list chains
Solution: call `cleanup` of network builder utility before rendering chain list
=> fix(`network chain list`): printing chain spinner bug

docs/migration/index.md
Noticed incorrect Github imports path in Starport v0.19.2 migration doc. Fixed it.
=> docs: fix v0.19.2 migration Github import paths

docs/guide/install.md
Thanks Waleed for working through sudo for curl and for bash to install Starport on an M1 chip machine
Thanks @nassdonald  for reporting the redundant TOC in the install doc
Docs are updated
=> docs(install): remove TOC, add M1 sudo, minor install doc improvements

.github/workflows/test-lint.yml, .golangci.yml, Makefile
- Add a step in the `make format` step to run `goimports` along with the existing step of running `gofmt`.
- Changes the `golint` linter to `revive` and upgrades the lint CI tool version to v1.41.0. 
_Based on @aljo242 suggestion into the `spn` (https://github.com/tendermint/spn/pull/509 / https://github.com/tendermint/spn/pull/510)_
=> chore(CI/Makefile): update the `golint` and add `go import` to the make command

starport/cmd/network_chain_show.go, starport/services/network/networkchain/prepare.go, starport/services/network/networktypes/genesisinformation.go, starport/services/network/networktypes/genesisinformation_test.go
a part of https://github.com/tendermint/starport/issues/2091.
=> fix(network): genesis account ordering

docs/kb/genesis.md
closes: https://github.com/tendermint/starport/issues/2111 
thanks @fadeev for the issue
=> docs: replace busted URL link to external Cosmos Hub genesis doc

docs/guide/blog/connect-blockchain.md
This PR is to fix a small typo under comment section of blog chain tutorial.
=> docs: fixing a typo under blog tutorial

docs/guide/blog/index.md
**Problem**:
The `blog` doc  provides a snippet of code with an unnecessary import. This is during the implementation of `AppendPost` see:
`func (k Keeper) AppendPost(ctx sdk.Context, post types.Post) uint64`
(https://github.com/tendermint/starport/blob/30b3e5091c5cdbcf6447042b681b89108a324197/docs/guide/blog/index.md)
Non-experienced users will receive an error during the rebuilding of the chain that they may not know how to recover from.
```
cannot build app:
error while running command go: 
../../x/mars/keeper/post.go:8:3: imported and not used: "strconv"
: exit status 2
```
**Solution**:
PR removes the unneeded `strconv` import.
=> docs(blog): remove unused import

docs/guide/install.md
closes: https://github.com/tendermint/starport/issues/2129 
@fadeev  two questions:
1. Do we want to keep the [Build from source](https://docs.starport.com/guide/install.html#build-from-source) section?
2. If yes, what are the benefits of using this installation method? can we provide guidance?
=> docs: remove homebrew from install 

integration/app/cmd_serve_test.go, starport/pkg/cosmosanalysis/app/app_test.go, starport/pkg/cosmosanalysis/cosmosanalysis_test.go, starport/pkg/cosmosutil/genesis_test.go, starport/pkg/localfs/search_test.go, starport/services/chain/chain_test.go
A small testing enhancement.
We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
=> test: use `T.TempDir` to create temporary test directory

starport/templates/typed/simapp.go
In the simulation template `opWeight` variable value for an operation is hardcoded to `op_weight_msg_create_chain`
Fix the template to take the name of the message reconsideration
```
starport s message foo-bar -> op_weight_msg_foo_bar
```
Thanks @aljo242 for spotting
=> fix(`template`): simulation `opWeight` name for an operation always the same

starport/templates/typed/list/stargate/component/x/{{moduleName}}/client/cli/query_{{typeName}}_test.go.plush, starport/templates/typed/map/stargate/component/x/{{moduleName}}/keeper/grpc_query_{{typeName}}.go.plush, starport/templates/typed/map/stargate/tests/component/x/{{moduleName}}/client/cli/query_{{typeName}}_test.go.plush, starport/templates/typed/map/stargate/tests/component/x/{{moduleName}}/keeper/grpc_query_{{typeName}}_test.go.plush, starport/templates/typed/singleton/stargate/component/x/{{moduleName}}/keeper/grpc_query_{{typeName}}.go.plush
Now not found queries are returning invalid argument errors. This PR fixes the code for the scaffolded queries, returning not found code.
=> fix(templates): fix not found error codes for scaffolded queries

starport/pkg/checksum/checksum.go, starport/services/network/network.go, starport/services/network/networkchain/binarycache.go, starport/services/network/networkchain/init.go, starport/services/network/networkchain/networkchain.go, starport/services/network/networkchain/prepare.go, starport/services/network/publish.go
This pull requests introduces caching for network commands. Few network commands have to build chain binary during their execution. It happens everytime but chain source can be the same between runs so chain binary can be reused.
Instead of calling c.chain.Build() new function c.Build() is introduced. It is checks if binary for a specific launch was built and reuse it.
=> feat(cmd/network): implement binary caching for network commands

starport/pkg/cosmosgen/install.go
This fixes https://github.com/tendermint/starport/issues/2171, but is not ideal... tooling binaries should be installed by running `go install [path]@[version]`, but protoc-gen-gocosmos uses a replace directive in the `go.mod` which is [incompatible with this method](https://github.com/golang/go/issues/44840#issuecomment-792789581). This fixes the problem for now, but adds plugin specific items to the go.mod of the scaffolded project, which shouldn't be there.
=> fix: installation of plugins for Go `v1.18` and above

starport/pkg/cosmoserror/error.go, starport/pkg/goanalysis/goanalysis_test.go, starport/services/network/publish.go, starport/services/network/queries.go
close #2176
Now the SPN returns the correct error code for not found queries. This PR fixes the error parse to check if the coordinator exists.
=> fix(network): invalid query return parser for get coordinator

docs/guide/hello.md
fixed typo ` Updates to the query qervice` to `Updates to the query service`
=> docs: fixing a typo in hello tutorial

go.mod, starport/pkg/entrywriter/entrywriter.go, starport/pkg/xstrings/xstrings.go, starport/services/chain/build.go, starport/templates/field/plushhelpers/plushhelpers.go, starport/templates/ibc/packet.go, starport/templates/module/create/genesistest.go, starport/templates/module/create/ibc.go, starport/templates/module/create/options.go, starport/templates/module/create/stargate.go
The `strings.Title` method was deprecated. The rule Title uses for word boundaries does not handle Unicode punctuation properly. 
- Import `golang.org/x/text/cases` pkg;
- move from the `strings.Title` method to `cases.Title` instead;
- create a helper `Title` method into the `xstrings` pkg;
=> refactor(templates): update the deprecated `string.Title` method to `cases.Title`

docs/guide/scavenge/08-cli.md
Rename `solutionHash` to `solution` because the arg in command line is solution, not solution hash
https://github.com/tendermint/starport/blob/fd403a2c13678da2430ce62ee35315a0e5b7d498/docs/guide/scavenge/09-play.md?plain=1#L34
=> fix: Update command `submit-scavenge` arg

docs/contributing/technical-setup.md
replace Tendermint with Ignite
remove the install Go steps so reader will use the official Starport docs
=> docs(technical-setup.md): fix Ignite company name in docs/contributing

docs/guide/hello.md
removed a step since the blockchain is already running
https://deploy-preview-2248--starport-docs.netlify.app/guide/hello.html
@soniasingla Auto-numbering in markdown we just use #1, also deleted step after discussion with @barriebyron
=> docs(hello.md): Update Hello Tutorial

docs/contributing/technical-setup.md, docs/migration/v0.19.2.md
migration paths for the GitHub packages still need updating, we can do next round
=> docs(technical-setup.md): fix rebrand install guide name

docs/guide/blog/comment-blog.md, docs/guide/ibc.md
close #2292 
Fixed typos on the Developer Tutorials: blog, ibc
Details are described in the issue
=> docs: fix typos on the Developer Tutorials

.goreleaser.nightly.yml
so our nightly build will be able to work until we resolve CI requirements.
=> chore(release/nightly): temporarily disable ARM and Darwin builds

changelog.md, ignite/templates/app/stargate/go.mod.plush
It's now possible to develop chains in Linux ARM machines and since
the chain depends on the CLI in its go.mod, it needs to use use the latest version
that support ARM targets.
=> fix(templates): use latest version to fix Linux ARM support

ignite/services/network/join.go
we are checking if the wrong address exists before adding
=> fix(network): fix wrong account address check for the join command

ignite/cmd/network_chain_publish.go, ignite/pkg/xurl/xurl.go, ignite/pkg/xurl/xurl_test.go
resolves #2380
The changes in the PR ensure that the source URL argument in the `ignite network chain publish` command is always prefixed with the "https://" prefix.
=> feat(network/publish): add support for source URLs without protocol

docs/guide/ibc.md
This is a fix to the issue: https://github.com/ignite-hq/cli/issues/2405
We pass in 'creator' as an argument in the Creating blog posts, Processing acknowledgments for sent posts, and Managing post timeouts
=> docs(tutorial): Pass in creator as an argument in CRUD transactions

ignite/cmd/network_chain_publish.go, ignite/pkg/xurl/xurl.go, ignite/pkg/xurl/xurl_test.go, ignite/services/chain/chain.go, ignite/services/chain/faucet.go, ignite/services/chain/plugin-stargate.go, ignite/services/chain/serve.go, ignite/services/network/networkchain/simulate.go, integration/app/tx_test.go, integration/env.go, integration/faucet/faucet_test.go
fixes #2390
The protocol related functions should be refactored to avoid errors:
=> refactor(pkg/xurl): change protocol functions to prevent possible bugs

ignite/pkg/cosmosgen/cosmosgen_test.go, ignite/pkg/cosmosutil/gentx.go, ignite/pkg/cosmosutil/gentx_test.go, ignite/services/network/networktypes/request.go, ignite/services/network/networktypes/request_test.go
We are parsing the pubkey wrong as a simple byte array, we should decode to `base64` and wrapper into an `ed25519` pubkey
=> fix(network): fix validator pubkey parser from gentx

ignite/cmd/cmd.go, ignite/cmd/ignite/main.go, ignite/internal/tools/gen-cli-docs/main.go
Closes #2468
The fix avoids invalid output to stdout when a new Ignite CLI version is available.
=> fix: shell completion generation when new version is available

.github/workflows/stats.yaml
Hello! Thanks for using github-repo-stats! I suppose you're interested in using a more recent version :) Release notes for the past few releases can be found here: https://github.com/jgehrcke/github-repo-stats/releases
=> chore: gh workflows: bump github-repo-stats to 1.4.0

ignite/pkg/cosmosgen/generate_javascript.go, ignite/pkg/protoc/protoc.go
Closes #2521
If `NODE_OPTIONS` environment variable is setted when running `protoc` from the Ignite CLI it might cause unexpected issues with the [vercel "pkg"](https://github.com/vercel/pkg) (nodetime). It already happened before and it seems to be the cause of #2521.
=> fix(cosmosgen): unset `NODE_OPTIONS` to avoid configuration conflicts

ignite/cmd/network_request_verify.go, ignite/services/network/networkchain/simulate.go
The requests cannot be approved or rejected because the rewards info gets the block height zero, and it's invalid in the genesis when we try to simulate the requests.
=> fix(network/request): fix request simulation

ignite/pkg/placeholder/tracer_test.go, ignite/templates/typed/list/stargate/messages/x/{{moduleName}}/client/cli/tx_{{typeName}}_test.go.plush, ignite/templates/typed/map/stargate/tests/component/x/{{moduleName}}/client/cli/query_{{typeName}}_test.go.plush, ignite/templates/typed/map/stargate/tests/messages/x/{{moduleName}}/client/cli/tx_{{typeName}}_test.go.plush, ignite/templates/typed/singleton/stargate/component/x/{{moduleName}}/client/cli/query_{{typeName}}_test.go.plush, ignite/templates/typed/singleton/stargate/messages/x/{{moduleName}}/client/cli/tx_{{typeName}}_test.go.plush
We have in several places in TDT the usage of `tc := tc`
Which is not necessary since `tc` is not a pointer
This PR removes every instance of this initialization in `tracer_test.go` and some of the templates
=> fix: remove useless `tc := tc` in TDT tests and some of the templates

docs/kb/frontend.md
The frontend app should be run using `npm run dev` when following the CLI tutorial.
Running it using `npm run serve` requires an extra step to build the app, which at the moment is causing some issues. See #2503.
=> chore: change frontend docs to run it using `npm run dev`

ignite/cmd/cmd.go, ignite/cmd/scaffold_chain.go
I propose we move the docs that are highly relevant to specific commands into the CLI to make it easier to update and use.
=> docs: update the scaffold chain inline docs

ignite/templates/module/create/ibc/x/{{moduleName}}/module_ibc.go.plush
Fix the interface of the handshake methods to comply with IBC v3
https://github.com/cosmos/ibc-go/blob/main/docs/migrations/v2-to-v3.md
=> fix(`module`): IBC module scaffolding interface

docs/docs/kb/09-docker.md
Also:
- adds a preliminary step related to the `$HOME/sdh` creation and a
rationale.
- remove `-w /app` flag since the default is `/apps` and it works well
with it.
- fix docker hub URL which was changed to `ignite/cli` instead of
`ignitehq/cli`
- use public docker hub URL (previous version was private and redirects
to the login page of docker hub)
Fix #2596
=> docs: replace docker deprecated cmds

.golangci.yml, Makefile, ignite/pkg/cache/cache.go, ignite/pkg/cliui/cliui.go, ignite/pkg/cosmosanalysis/app/testdata/app_minimal.go, ignite/pkg/cosmosanalysis/app/testdata/two_app.go, ignite/pkg/cosmosgen/generate.go, ignite/pkg/xurl/xurl.go
What this PR does:
- update `golangci-lint` to `v1.47.2` for better go 1.18 support
- update `.golangci.yml` lint runners
- run `make lint` and make appropriate changes
- run `make format`
=> chore: lint and format

ignite/templates/app/stargate/app/app.go.plush
=> refactor(`app`): remove `monitoringp` module from template

ignite/pkg/cosmosutil/genesis.go, ignite/pkg/cosmosutil/genesis_test.go, ignite/services/network/networkchain/init.go, ignite/services/network/publish_test.go
- Add a method in `ChainGenesis` object to count gentxs in a genesis
- Add the check for no gentx in `initGenesis`. `initGenesis` generate the initial genesis of the chain so it makes sense to add this check here as a consideration that the initial genesis is only valid without gentx so that the condition is checked in any workflow using the initial genesis like `publish` but other command in the case a coordinator published a chain without the CLI
Run a local `spn`:
```
ignite chain serve -c config_2.yml -r
```
Chain with default genesis can be published
```
ignite n chain publish https://github.com/tendermint/spn --spn-node-address http://0.0.0.0:26661/ --spn-faucet-address http://0.0.0.0:4502/ --chain-id spn-1
✔ Source code fetched
✔ Blockchain set up
✔ Chain's binary built
✔ …
```
=> feat(`network`): check no gentx are present in the initial genesis

go.mod, go.sum
Issue: #2650
Original issue was also discussed on Discord: https://discord.com/channels/893126937067802685/905127580087234590/1000483556767846501
The main issue was:
> Currently, it is impossible to use cosmos accounts with ignite on a Mac m1 chip because ignite uses keyring v1.1.6.  The Cosmos SDK upgraded this to v1.2.1 only 9 days ago to fix this, but it has yet to be updated on ignite
The PR made to the Cosmos SDK was quite simple and after testing it with a couple of machines (M1 included) it seems like a safe update.
The PR: https://github.com/cosmos/cosmos-sdk/pull/12576
=> fix(`account`): Update keyring dependency to match Cosmos SDK

ignite/templates/query/stargate/x/{{moduleName}}/client/cli/query_{{queryName}}.go.plush
It should use the query client context.
Fix #2656
=> fix(template): client query uses tx client context

docs/docs/index.md
Add github.com/sonr-io/sonr to the projects being built with Ignite in the root of the docs.
=> feat(docs): add Sonr to the Projects building with

ignite/templates/ibc/oracle.go, ignite/templates/ibc/oracle/x/{{moduleName}}/oracle.go.plush, ignite/templates/ibc/packet.go, ignite/templates/module/create/ibc.go, ignite/templates/module/create/ibc/x/{{moduleName}}/module_ibc.go.plush, ignite/templates/module/create/stargate/x/{{moduleName}}/module.go.plush
Use `IBCModule` idiom as seen here:
- https://github.com/cosmos/ibc-go/blob/v5.0.0-beta1/modules/apps/transfer/ibc_module.go#L21-L30
- https://github.com/cosmos/ibc-go/blob/v5.0.0-beta1/modules/apps/transfer/module.go#L33
=> feat: use ibcmodule idiom

ignite/cmd/chain_build.go, ignite/cmd/chain_init.go, ignite/cmd/chain_serve.go, ignite/cmd/network_chain_init.go, ignite/cmd/network_chain_install.go, ignite/cmd/network_chain_join.go, ignite/cmd/network_chain_prepare.go, ignite/cmd/network_chain_publish.go, ignite/services/chain/build.go, ignite/services/chain/chain.go, ignite/services/network/networkchain/networkchain.go
Resolves #137
These changes makes `go mod verify` during build optional. The default behaviour is not to verify during build.
App dependencies verification is a good practice but is not really required for the build.
By default, these changes bypass the verification to avoid the missing ziphash files for local modules that can happen when a workspace is used. The real issue seems to be a Go tooling issue that happens when `go mod verify` is run within a Go workspace context.
=> feat: make go dependency validation during build optional

ignite/cmd/account_create.go, ignite/pkg/cosmosaccount/cosmosaccount.go
Resolves #2701
`cosmosaccount.New()` was missing the following line:
```go
cryptocodec.RegisterInterfaces(interfaceRegistry)
```
=> fix(`pkg/cosmosaccount`): register cryptocodec interfaces

ignite/templates/module/create/stargate/x/{{moduleName}}/genesis.go.plush, ignite/templates/module/create/stargate/x/{{moduleName}}/module.go.plush, ignite/templates/module/create/stargate/x/{{moduleName}}/types/genesis.go.plush
Removed:
* `func (AppModuleBasic) RegisterCodec(cdc *codec.LegacyAmino)`
* `func (AppModuleBasic) RegisterRESTRoutes(clientCtx client.Context, rtr *mux.Router)`
* `func (am AppModule) Name() string`
* mentions of the `capability` module from the comments
close https://github.com/ignite/cli/issues/2705
=> fix(template): removed unused methods and fix comments

ignite/cmd/network_chain_join.go, ignite/services/network/join.go
We initialized the chain in a temporary directory so we could have a genesis to check the existing accounts without erasing the current gentx.
At the end, I think we don't need this if we don't provide a gentx from a custom path. If we use the default gentx, it means we use the one from the chain home, so the chain is already initialized.
We initialize the chain in the home if a custom gentx is used to check the accounts, when a custom gentx is used the node ID will be parsed in the gentx itself
=> fix(`network`): Gitpod networking issue

ignite/cmd/tools.go
Completions are provided by Cobra by default with `ignite completion`, so there is no need to have the command hard-coded into Ignite.
closes https://github.com/ignite/cli/issues/2402
=> fix: remove `ignite tools completions`

docs/docs.go, ignite/pkg/cosmosclient/cosmosclient.go, ignite/services/network/testutil/response.go
Moves to using the `MsgResponses` field `TxMsgData` instead of the deprecated `MsgData` field.
This PR retains the decoding of deprecated messages in the `Decode` method of `cosmosclient`.
=> fix(`cosmosclient`): use protobuf Any for TxMsgData 

ignite/cmd/network.go
Change host used when using `--local` flag of `network` commands
We created `config_2.yml` on `spn`to serves the chain with different ports so that the chain can be launched locally with default config
We change to those ports with the `--local` flag
=> refactor(network): change host for local flag

go.mod, go.sum
Synchronize `spn` with version on `develop` branch where `0.46` has been merge to avoid as `0.46` branch has been deleted
=> chore(`0.46`): upgrade spn version to `develop`

ignite/pkg/relayer/relayer.go
Fixes #2711 
**Description**
The `pkg/relayer` was sending the private keys to the [TS relayer](https://github.com/confio/ts-relayer) as arguments in "ASCII armored" format instead of "secp256k1" which is the [expected format](https://github.com/cosmos/cosmjs/blob/main/packages/crypto/src/secp256k1.ts#L35).
=> fix: change relayer call args to use `secp256k1` private keys

ignite/pkg/chaincmd/runner/chain.go, ignite/services/network/join.go, ignite/services/network/join_test.go, ignite/services/network/networkchain/simulate.go
Add some fixes for issues occurring when launching `spn`
- Remove existing account verification in `join`
The verification process was flawed as the genesis to verify accounts was already initialized with the account.
We simulate the genesis in the  `approve` process to check request validity. We can rely on this method so that we have a single entrypoint to maintain for requests validation
- Change endpoint to check simulated chain running
Change checked endpoint from `api/node_info` to `rpc/health` for the check. `api/node_info` seems to be no longer exposed with `0.46` and `api` may not be used by all chains
=> fix(`network`): various fixes to launch `spn` from `spn`

docs/docs/kb/01-scaffold-chain.md
Because we no longer have `prefix.go`. This might change once we no longer depend on `cosmoscmd`, but for now it's the case.
close https://github.com/ignite/cli/issues/1990
=> docs: change the prefix in `app/app.go`

ignite/cmd/scaffold_module.go
The idea is to have extensive inline documentation for each command. This makes it easier for devs to know how exactly the command behaves without looking it up in the documentation.
=> docs: `ignite scaffold module` inline documentation

ignite/version/version.go
Just a tiny tweak to make it easier to debug frontend-related issues in the future.
close https://github.com/ignite/cli/issues/2251 (we no longer need the Flutter version, because mobile is on hold)
=> chore: add Node.js version in the output of `ignite version`

docs/docs.go, ignite/pkg/cosmosclient/cosmosclient.go, ignite/services/network/networkchain/prepare.go
Some basic lint fixes:
- remove usage of deprecated `io/ioutil` package
- formatting
=> chore: lint fixes

docs/docs/guide/03-blog/02-connect-blockchain.md, docs/docs/guide/04-nameservice/02-messages.md, docs/docs/guide/04-nameservice/04-keeper.md, docs/docs/guide/05-scavenge/07-keeper.md, docs/docs/guide/05-scavenge/08-cli.md, docs/docs/guide/07-ibc.md, docs/docs/guide/08-interchange/02-init.md, docs/docs/guide/08-interchange/05-mint-and-burn-voucher.md, docs/docs/guide/08-interchange/06-creating-sell-orders.md, docs/docs/guide/08-interchange/07-creating-buy-orders.md, docs/docs/guide/08-interchange/08-cancelling-orders.md
- Change `ibc-go` import to use "v5"
- Add missing package definition to code examples that can be copy/pasted
- Change file references to paths for consistency with other tutorials
- Fix interchange tutorial to use ports that don't overlap
- Remove unused imports
- Fix documentation issues
=> docs: update tutorials 

ignite/pkg/cosmosclient/cosmosclient.go
account prefix config not correct when broadcasting a tx from a newly created default account
Fixes https://github.com/ignite/cli/issues/2738
There is a weird bug from `0.46`
When broadcasting a tx without mentioning an account with the `--from` flag, an account `default` is used. If default doesn't exist, the account will be created on the fly and will request tokens with the faucet.
In the case, `default` is created on the fly, the address prefix update in the SDK global config: https://github.com/ignite/cli/blob/4eaa73a187b78cdd4b6d0b19594387bfa50ca11a/ignite/pkg/cosmosclient/cosmosclient.go#L338
will not update the prefix, from `cosmos` to `spn` for example. This will make the method fails because `cosmos` prefix will be used and the error in the related issue will occur using …
=> fix(cosmosclient): fix account prefix config

ignite/cmd/network_chain_show_genesis.go, ignite/pkg/xos/mv.go, ignite/pkg/xos/mv_test.go, ignite/services/network/networkchain/account.go, integration/chain/cmd_serve_test.go
Fix #2660
os.Rename fails when source and destination are in different partitions.
xos.Rename works in that context.
=> fix: replace os.Rename with xos.Rename

ignite/cmd/chain_build.go, ignite/cmd/cmd.go
- inline docs
- lowercase flag descriptions (to match cobra's defaults, see `--help`)
- removed the `--home` flag, because I don't think it's used for the `build` command
=> docs: inline documentation for `chain build`

.github/workflows/cl-enforcer.yml
This forces the developper to add an entry in the changelog.md file of his PR.
It is possible to skip that rule by adding a `Skip-Changelog` label.
=> chore: add CL enforcer gh action

.github/workflows/go-formatting.yml, Makefile, go.mod, go.sum, ignite/internal/tools/tools.go, ignite/pkg/confile/confile_test.go
- Use `goimports` with `-local` flag which separates ignite/cli package from
the others.
- Use `gofumpt` instead gofmt
The gh action is triggered when a commit with a go file change is pushed to
develop. If `goimports` or `gofumpt` have changed some files, then an other commit
is pushed to develop. Nothing happens if there's no change.
I initially triggered the action on pull requests, but I found annoying
and intrusive to have these new commits in the context of a feature
branch.
1) this commit contains an unrelated change to `confile_test.go`, in
order to test that gofumpt will fix that. For goimports there's already
a couple of changes that will happen.
2) I noticed that the files in `.github/workflows` used to have a prefix. Maybe we could add `chore-` prefix to this new gh action, …
=> chore: add go formatting github action

.github/workflows/go-formatting.yml
Surprisingly, actions/setup-go doesn't fetch the latest go version. We
need to specify 1.18 because we use some generics.
=> fix: go formatting require go 1.18

ignite/templates/module/create/stargate/x/{{moduleName}}/module.go.plush, ignite/templates/module/create/stargate/x/{{moduleName}}/types/keys.go.plush
`QuerierRoute` key is used only in the deprecated `QuerierRoute` function. Might as well simplify the template right now. Also, fixed a comment.
=> fix(template): remove QuerierRoute

go.mod, go.sum
Updates the `spn` dependency to the latest version on the `develop` branch.
Bumping this dependency is important because `spn` is now [updated](https://github.com/tendermint/spn/commit/985b629a92ddd6cddb2adc2c774d455c4466eae6) to use the latest version of the `x/fundraising` module, removing the previous import of a fork.
=> chore: use latest `spn`

changelog.md, docs/docs/guide/08-interchange/05-mint-and-burn-voucher.md, go.mod, ignite/pkg/cosmosfaucet/cosmosfaucet.go, ignite/pkg/cosmosutil/gentx.go, ignite/pkg/cosmosutil/gentx_test.go, ignite/services/network/join_test.go, ignite/services/network/networktypes/genesisinformation_test.go, ignite/services/network/networktypes/request_test.go, ignite/services/network/reward_test.go, ignite/services/network/share_percent_test.go, ignite/templates/typed/list/stargate/messages/x/{{moduleName}}/client/cli/tx_{{typeName}}_test.go.plush, ignite/templates/typed/map/stargate/tests/messages/x/{{moduleName}}/client/cli/tx_{{typeName}}_test.go.plush, ignite/templates/typed/singleton/stargate/messages/x/{{moduleName}}/client/cli/tx_{{typeName}}_test.go.plush
Use the `cosmossdk.io/math` package instead of the math types found in `github.com/cosmos/cosmos-sdk/types`.  
As of `v0.46.x` the old type aliases are deprecated.
=> refactor: use `cosmossdk.io/math` package

docs/docs/guide/02-hello.md, ignite/templates/module/create/stargate/x/{{moduleName}}/module.go.plush, ignite/templates/typed/list/stargate.go, ignite/templates/typed/map/stargate.go, ignite/templates/typed/singleton/stargate.go
close https://github.com/ignite/cli/issues/2797
=> fix(template): remove a placeholder in `module.go`

.gitattributes, changelog.md
Since we are forcing the updage of changelog.md on every PR, this leads to many conflicts when it's time to merge.
By forcing the merge strategy of this file to `union`, it decreases the chance of conflicts by ~90%. The downside is sometimes the merge gets wrong (repeated lines) so the dev should have a look at the result.
=> chore: set union merge strategy to changelog.md

docs/docs/guide/03-blog/00-build-blog.md, docs/docs/guide/03-blog/01-comment-blog.md, ignite/templates/typed/list/stargate.go, ignite/templates/typed/singleton/stargate.go
Noticed we're using both dashes `-` and slashes `/` for key index separators. Might as well stick to one convention.
=> fix(template): use slashes for key separators

docs/docs/guide/02-hello.md
Fix #2817
Revert part of commit 7c836df5ec90e9a7abd15a114cd6ec2b10969a27
There's 2 reasons why this change should be reverted:
- the version that does the registration automatically is not released yet (0.24)
- the hello tutorial requires the use of cli 0.22, where the registration is always manual.
What could be changed in the 0.24 documentation:
- remove the 0.22 requirement (latest could be used w/o any problem I think)
- remove the manual grpc registration.
=> docs(guide/hello): revert grpc registration removal

readme.md
Update compatibility table for upcoming `v0.24.0` release
=> docs: update compatibility table

changelog.md, ignite/templates/app/stargate/.github/workflows/release.yml
A missing ignite-hq switch!
Tools like `ag` intentionally ignores directories that starts with a `.`, that's probably why we missed them.
=> fix: cli action org in templates

.github/workflows/gen-docs-cli.yml, .github/workflows/go-formatting.yml, .github/workflows/release-binary.yml, .github/workflows/release-nightly.yml, .github/workflows/test-integration.yml, .github/workflows/test-lint.yml, .github/workflows/test.yml, .golangci.yml, Makefile, go.mod, go.sum, ignite/internal/tools/tools.go, ignite/services/network/join_test.go
- update CI workflows to use latest go version (1.19) and checkout actions (v3)
- update CI lint tool and rules
- add `govulncheck` 
- minor `go vet` fix
=> chore: tooling updates

changelog.md, ignite/pkg/cosmosgen/generate_typescript.go, ignite/pkg/cosmosgen/templates/module/module.ts.tpl, ignite/pkg/cosmosgen/templates/root/package.json.tpl, ignite/pkg/nodetime/programs/sta/sta.go, scripts/data/gen-nodetime/package-lock.json, scripts/data/gen-nodetime/package.json
- Updated `nodetime`: `ts-proto` to `v1.126.0`, `protobufjs` to `v7.1.1`, `swagger-typescript-api` to `v9.2.0`
- Switched codegen client to use `axios` instead of `fetch`
=> chore: Nodetime updates

changelog.md, ignite/pkg/cosmosfaucet/http.go, ignite/pkg/cosmosfaucet/http_test.go
**Description**
Some of the faucet service endpoint are using C.O.R.S. but those endpoints are not allowing `OPTIONS` requests which are needed for the preflight one.
**Solution**
Change faucet's HTTP handler to allow `OPTIONS` request in all the endpoints that have C.O.R.S. enabled.
=> fix: change faucet to allow C.O.R.S. preflight requests

changelog.md, ignite/templates/app/stargate/app/app.go.plush
Fix #2867
Found how the wiring is done in gaia :angel: 
I wasn't sure if I should add a new field in the `App` struct for this keeper, so I didn't, tell me if I should.
Now the incriminated command in the issue works :
```
$ appd query ica controller params
controller_enabled: true
```
=> fix: ICA controller wiring

ignite/cmd/network.go
Fix #2888
The command will now appear in `ignite help` and in the CLI reference documentation.
=> chore: reveal `network` command

docs/docs/network/03-validator.md
Fix a tabulation issue in the list of chains of the network guide
=> docs: fix tabulation in network guide

docs/docs/07-cli.md
=> Fix: typos

changelog.md, ignite/cmd/cmd.go, ignite/cmd/network_campaign_list.go, ignite/cmd/network_chain_init.go, ignite/cmd/network_chain_join.go, ignite/cmd/network_chain_list.go, ignite/cmd/network_chain_show.go, ignite/cmd/network_request_list.go, ignite/cmd/network_reward_release.go, ignite/cmd/relayer_configure.go, ignite/cmd/scaffold.go, ignite/pkg/cliui/clispinner/clispinner.go, ignite/pkg/cliui/cliui.go
=> fix: change session to use the same spinner reference

ignite/cmd/network_campaign.go, ignite/cmd/network_profile.go, ignite/cmd/network_reward.go
Hide command sets not used and in development for now
```
n campaign
n reward
n profile
```
=> chore(`network`): hide unused command sets

ignite/cmd/network_request_approve.go
Should we mention that the order of request IDs matter?
=> docs: network request approve

ignite/cmd/network_request_add_account.go
=> fix(`network`): use correct prefix for network `add-account` request

changelog.md, ignite/cmd/network_request.go, ignite/cmd/network_request_remove_validator.go, ignite/services/network/join.go, ignite/services/network/request.go
Closes #2966
Moves `Send**Request` functions from `join.go` to `request.go`
=> feat: `ignite n request remove-validator`

ignite/services/network/networkchain/simulate.go, ignite/services/scaffolder/init.go
In the process of approving requests, we simulate genesis to check the chain can start
In this process, we ignore the error where validator set is still nil and chain can't start, so that the coordinator can approve requests before approving the first validator for the chain
We do this by comparing error string
Since the error statement for this has been updated in the SDK, we store the historical list of this error so we can ignore the the error for several version of the SDK
=> fix(`network`): set validator set nil error up to date

ignite/cmd/chain_build.go, ignite/cmd/chain_init.go, ignite/cmd/chain_serve.go, ignite/cmd/network.go, ignite/cmd/network_chain_init.go, ignite/cmd/network_chain_join.go, ignite/cmd/network_request_approve.go, ignite/cmd/scaffold_chain.go, ignite/cmd/scaffold_list.go, ignite/cmd/scaffold_map.go, ignite/cmd/scaffold_message.go, ignite/cmd/scaffold_module.go
=> docs: fix formatting to get code blocks rendered

ignite/services/plugin/template/go.mod.plush
Fix an error where the `plugin` template `go.mod` used an old hash of `cli`  before we switched to using `main` instead of `develop`.
=> fix: `plugin` tests

ignite/cmd/plugin.go
`plugin.Manifest()` shouldn't be invoked if the plugin load failed.
=> fix: plugin list panic if plugin load failed

go.mod, go.sum
Upgrade `spn` version to include latest fix on-chain (param name verification)
=> chore: upgrade `spn`

docs/docs/guide/03-blog/01-comment-blog.md
The error message uses the wrong id, it should be postID
=> fix: incorrect error message in `docs`

Makefile, docs/docs/guide/02-hello.md, docs/docs/guide/03-blog/00-build-blog.md, docs/docs/guide/03-blog/01-comment-blog.md, docs/docs/guide/06-loan.md, docs/docs/guide/07-ibc.md, docs/docs/guide/08-interchange/04-creating-order-books.md, docs/docs/guide/08-interchange/08-cancelling-orders.md, docs/docs/migration/v0.18.md, docs/docs/migration/v0.24.0.md, docs/docs/migration/v0.25.0.md, go.mod, go.sum, ignite/internal/tools/tools.go
[mdgofmt](https://github.com/tbruyelle/mdgofmt) is a small tool I wrote that runs `gofmt` on go snipppets inside markdown files.
By adding its usage in `make format`, it will run with the `Go Formatting` github action.
It can fail if the code isn't accepted by `gofmt`, so I had to fix some our snippets to accommodate that.
=> docs: use mdgofmt to format go snippets in markdown

ignite/cmd/cmd.go, ignite/cmd/plugin.go
Closes #3235
We decided to remove this flag entirely since any use cases should be covered by the local + global config options users have.
=> refactor(`plugins`): remove plugin flag

ignite/templates/app/files/tools/tools.go.plush
This file was removed by mistake in this PR that was merged w/o reviews :/ 
https://github.com/ignite/cli/pull/2961
As a remind this file helps to track external tools version in the scaffolded chain.
=> fix: removed file by mistake

ignite/pkg/cliui/colors/colors.go
Resolves #3297
The changeset leaves name style in bold to avoid contrast issues in terminals with different backgrounds.
Using `lipgloss.AdaptativeColor` doesn't work as expected so the simpler solution is just to remove foreground color in this case.
=> chore: remove color from name styles

docs/docs/guide/01-install.md, docs/versioned_docs/version-v0.25.2/guide/01-install.md
uses `main` instead of `develop` in changelog links
=> fix: changelog links

ignite/templates/app/files/app/simulation_test.go.plush
The simulation file template has a comment instruction with Starport instead Ignite
=> chore(simulation): fix wrong comment for simulation template file

docs/docs/clients/_category_.json, docs/docs/guide/_category_.json, docs/docs/kb/_category_.json, docs/docs/migration/_category_.json, docs/docs/network/_category_.json
Renamed categories to:
* Build a chain
* Build a client-app
* Launch a chain
URL are unchanged, so no breaking links.
=> docs: rename top-level categories

changelog.md, ignite/services/scaffolder/component.go, integration/other_components/cmd_message_test.go
Closes #3327. Instead of just uppercasing the component name, the change lowercases it so mixed capitalization doesn't cheat past it.
=> fix: Disallow components with same name

changelog.md, ignite/templates/module/create/files/base/x/{{moduleName}}/client/cli/query_params.go.plush, ignite/templates/typed/list/files/component/x/{{moduleName}}/client/cli/query_{{typeName}}.go.plush, ignite/templates/typed/map/files/component/x/{{moduleName}}/client/cli/query_{{typeName}}.go.plush, ignite/templates/typed/singleton/files/component/x/{{moduleName}}/client/cli/query_{{typeName}}.go.plush
=> fix(template): wrong client context for cmd query methods

changelog.md, ignite/cmd/chain_build.go, ignite/cmd/chain_init.go, ignite/cmd/chain_serve.go, ignite/pkg/cosmosver/app.go, ignite/pkg/gocmd/gocmd.go, ignite/services/chain/build.go, ignite/services/chain/serve.go
Add the `--build.tags` flag for the `chain serve` and `chain build` commands so we can build the binary, passing a list of tags to use in the go build command.
This will set the `-tag` flag for the go build and also the `version.BuildTags` var for the cosmos-sdk `ldFlag`
E.g.:
```shell
go build -tags "app_v1 netgo ledger" -ldflags '-X "github.com/cosmos/cosmos-sdk/version.BuildTags=app_v1,netgo,ledger" ...
```
__By default, the `app_v1` flag is set.__
```shell
ignite chain serve -r --clear-cache --build.tags app_v1,ledger,netgo
```
```shell
ignite chain build --clear-cache --build.tags app_v2,ledger
```
=> feat(chain): Add `--build.tags` flag for `chain serve` and `chain build` commands

changelog.md, go.mod, go.sum, ignite/pkg/chaincmd/runner/runner.go
The package `github.com/ghodss/yaml` is no longer actively maintained. See discussion in https://github.com/ghodss/yaml/issues/75 and https://github.com/ghodss/yaml/issues/80. [`sigs.k8s.io/yaml`](https://github.com/kubernetes-sigs/yaml) is a permanent fork of `github.com/ghodss/yaml`.
The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, but `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. Changes can be seen here [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), mostly bug fixes.
=> refactor: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

integration/app.go, integration/cosmosgen/bank_module_test.go, integration/cosmosgen/bank_module_test.ts, integration/cosmosgen/custom_module_test.go, integration/network/network_test.go, integration/network/request_test.go, integration/testdata/tstestrunner/testutil/setup.ts, integration/testdata/tstestrunner/vitest.config.ts
These integration tests are failing because the SPN app is not compatible with the new apps wiring. Tests can be enabled once SPN is migrated to support it.
=> chore: temporarily skip network command integration tests

changelog.md, ignite/pkg/checksum/checksum.go
Resolves https://github.com/ignite/cli/issues/3480
Checksum format `<sha256sum><space><space><file_name>` instead of `<sha256sum><space><file_name>`.
Reference see [here](https://linux.die.net/man/1/sha256sum):
> The sums are computed as described in FIPS-180-2. When checking, the input should be a former output of this program. The default mode is to print a line with checksum, a character indicating type ('*' for binary, ' ' for text), and name for each FILE.
=> fix: correct checksum format

.github/workflows/janitor.yml
Add workflow Janitor to clean up previous runs that are not completed for a given workflow. It cancels Sims and Tests
=> feat: add github worflow for clean up previous runs that are not completed

actions/cli/Dockerfile
At some point docker pipeline was updated and now produce "tagged/versioned" images & "latest" ("develop" => "latest"). 
At this moment action can't be used at all for "new" chains (GO 1.19), as it try to use outdated "develop" with GO 1.18 onboard.
This change should fix this.
=> fix: set correct docker container tag for GH action

.github/workflows/release-nightly.yml, ignite/templates/app/files/.github/workflows/release.yml
From https://github.com/dev-drprasad/delete-tag-and-release/releases, it can be seen that there is currently no version v0.2.0, and the latest version is v0.2.1.
=> feat: bump dev-drprasad/delete-tag-and-release to v0.2.1

changelog.md, ignite/pkg/cosmosfaucet/openapi/openapi.yml.tmpl
Fix: #3496 
Aftet this fix, I can get balance by clicking the url in faucet swagger UI
=> fix: wrong bank balance query url in cosmos faucet openapi

changelog.md, ignite/cmd/chain_build.go, ignite/cmd/chain_init.go, ignite/cmd/chain_serve.go, ignite/cmd/generate_go.go, ignite/pkg/cosmosanalysis/cosmosanalysis.go, ignite/pkg/cosmosgen/generate.go, ignite/pkg/cosmosver/cosmosver.go, ignite/pkg/cosmosver/detect.go, ignite/services/chain/chain.go, ignite/services/scaffolder/scaffolder.go, ignite/version/version.go
=> fix: upgrade Cosmos SDK app compatibility check

changelog.md, ignite/cmd/plugin_default.go
the new version has the sdk `v0.47.3` without warnings into the `stdout`
=> chore(network): Bump network plugin version to `v0.1.1`

.github/workflows/md-link-checker-config.json, .gitpod/readme.md, contributing.md, docs/docs/02-guide/02-getting-started.md, docs/docs/03-clients/02-typescript.md, docs/docs/06-migration/v0.26.0.md, docs/docs/06-migration/v0.27.1.md, docs/versioned_docs/version-v0.25.2/guide/04-nameservice/01-init.md, docs/versioned_docs/version-v0.25.2/guide/04-nameservice/02-messages.md, docs/versioned_docs/version-v0.25.2/guide/04-nameservice/03-types.md, docs/versioned_docs/version-v0.25.2/guide/06-loan.md, docs/versioned_docs/version-v0.26.1/02-guide/02-getting-started.md, docs/versioned_docs/version-v0.26.1/03-clients/02-typescript.md, docs/versioned_docs/version-v0.26.1/06-migration/v0.26.0.md, docs/versioned_docs/version-v0.27.1/02-guide/02-getting-started.md, docs/versioned_docs/version-v0.27.1/03-clients/02-typescript.md, docs/versioned_docs/version-v0.27.1/06-migration/v0.26.0.md, docs/versioned_docs/version-v0.27.1/06-migration/v0.27.1.md, readme.md
=> docs: add migration steps for Ignite CLI v0.27.1

ignite/cmd/cmd.go
Previous link(getting 404) : https://docs.ignite.com/guide/install#upgrading-your-ignite-cli-installation
Correct link : https://docs.ignite.com/welcome/install#upgrading-your-ignite-cli-installation
=> fix: update instruction link for ignite CLI version upgradation

ignite/cmd/scaffold_map.go
Looks like a simple typo, where you are trying to reference the difference between "map" and "list", but mention "list" twice.
=> fix: docs for scaffold map

changelog.md, ignite/templates/app/files/app/app.go.plush
The module must be added to avoid triggering an assertion that requires that all modules are added to `SetOrderBeginBlockers` even if they don't implement `HasBeginBlocker`. Modules that don't implement it can be removed from the list once Cosmos SDK `v0.50.0` is released.
=> chore: add back crisis module to SetOrderBeginBlockers

changelog.md, ignite/pkg/protoanalysis/builder.go
Proto HTTP rule parameters can have extra arguments which are defined after a "=", for example `/foo/{bar=**}`.
Fixes #3554
=> fix(pkg/protoanalysis): support HTTP rule parameter arguments

ignite/cmd/scaffold_map.go
while using ``` ignite scaffold map ``` I came across a typo. I am opening this pull request with a fix.
=> fix: scaffold_map typo

docs/docs/06-migration/v0.27.1.md, docs/versioned_docs/version-v0.27.1/06-migration/v0.27.1.md
The `go` syntax changed to `text` to aviod CI errors when `mdgofmt` validates and format the snippets. Migration snippets are writen as "diffs" so the code within them is not valid Go code.
=> ci: remove `go` snippet syntax from migration docs

.github/labeler.yml
Fix issue with labeler config and exclude labeler GitHub action config files from the label trigger to avoid issues when any of the config files is broken.
=> chore: fix labeler GitHub action config

.github/labeler.yml
Better not to include markdown files like changelog in the labeler, otherwise most PRs would be labeled as `doc` because of that.
=> ci: change labeler to ignore root markdown files

changelog.md, ignite/pkg/cosmosfaucet/cosmosfaucet.go, ignite/pkg/cosmosfaucet/transfer.go, ignite/services/chain/faucet.go
cosmos faucet has overflow issue because uint64. Ethermint based chain is using decimal 18 so uint64 is not enough for them. 
Instead of that. it's more reasonable to use sdk.int of cosmos types.
Closes #3609
=> chore: uin64 overflow fix

changelog.md, ignite/pkg/cosmosgen/templates/composable/index.ts.tpl
=> fix: Remove unintentional vue type import

docs/docs/08-references/01-cli.md
typo in the Synopsis of the map command replacing "list" with "map"
=> docs: typo in the Synopsis of documentation

ignite/pkg/cosmosanalysis/cosmosanalysis.go, ignite/templates/app/files/app/app.go.plush, ignite/templates/app/files/app/ibc.go.plush, ignite/templates/module/create/files/msgserver/proto/{{appName}}/{{moduleName}}/tx.proto.plush
Improvements to https://github.com/ignite/cli/pull/3659.
I'll be submitting a few scoped PRs targeting that branch.
=> refactor: v0.50 store app wiring

ignite/templates/ibc/files/oracle/x/{{moduleName}}/types/{{queryName}}.go.plush, ignite/templates/ibc/files/packet/messages/x/{{moduleName}}/types/messages_{{packetName}}.go.plush, ignite/templates/message/files/message/x/{{moduleName}}/types/message_{{msgName}}.go.plush, ignite/templates/module/create/files/base/x/{{moduleName}}/types/keys.go.plush, ignite/templates/module/create/files/base/x/{{moduleName}}/types/msg_update_params.go.plush, ignite/templates/module/create/files/msgserver/proto/{{appName}}/{{moduleName}}/tx.proto.plush, ignite/templates/typed/gogoproto.go, ignite/templates/typed/list/files/messages/x/{{moduleName}}/types/messages_{{typeName}}.go.plush, ignite/templates/typed/map/files/messages/x/{{moduleName}}/types/messages_{{typeName}}.go.plush, ignite/templates/typed/proto.go, ignite/templates/typed/singleton/files/messages/x/{{moduleName}}/types/messages_{{typeName}}.go.plush
Improvements to https://github.com/ignite/cli/pull/3659.
I'll be submitting a few scoped PRs targeting that branch.
This PRs remove the legacy `Route()` and `Type()` from modules, as well as the `GetSigners` function.
In v0.50 `GetSigners` is inferred from the proto annotation (that was added here: https://github.com/ignite/cli/pull/3659/commits/e52af7506044d29ec509539a92c9a6547484d3c3)
=> refactor: remove unecessary boilerplate in module

ignite/templates/app/files/cmd/{{binaryNamePrefix}}d/cmd/root.go.plush, ignite/templates/app/files/go.mod.plush
Improvements to https://github.com/ignite/cli/pull/3659.
I'll be submitting a few scoped PRs targeting that branch.
This brings in app wiring changes from https://github.com/cosmos/cosmos-sdk/pull/17920.
=> refactor: simplify app.go

docs/docs/02-guide/03-hello/01-scaffolding.md, ignite/templates/app/files/app/app.go.plush, ignite/templates/module/create/files/base/x/{{moduleName}}/client/cli/query.go.plush, ignite/templates/module/create/files/base/x/{{moduleName}}/module.go.plush, ignite/templates/module/create/files/base/x/{{moduleName}}/types/codec.go.plush
Improvements to https://github.com/ignite/cli/pull/3659.
I'll be submitting a few scoped PRs targeting that branch.
Remove unnecessary boilerplate in module and fix a typo in app.go
=> refactor: remove unnecessary boilerplate (part 2)

.github/workflows/release-nightly.yml
The release action requires a version that includes the patch version to be able to download the right tarball with the Go binary.
See https://github.com/wangyoucao577/go-release-action/blob/2ac3035fa4c4feed6a8272ce278b0577b93cf8e5/setup-go.sh#L24
=> fix: change Go version in nightly release config to `1.21.2`

.github/workflows/release-nightly.yml
Latest version is used by default but it shouldn't be specified explicitly because the value "latest" is not supported.
=> fix: remove explicit "latest" for Go version release nightly

.github/workflows/test-integration.yml, .github/workflows/test-lint.yml, ignite/pkg/cache/cache.go, ignite/pkg/cosmosanalysis/app/app.go, ignite/pkg/placeholder/error.go
These changes fix some issues that are causing that some PR test workflows are failing
=> ci: fix integration tests and lint workflows

changelog.md, ignite/pkg/cosmosgen/generate_openapi.go, ignite/pkg/nodetime/programs/swagger-combine/swagger-combine.go, ignite/templates/app/files/go.mod.plush, ignite/templates/app/files/proto/buf.gen.sta.yaml
This fixes some flaky issues that were coming up for me while running on Linux:
Changes:
- Reuse `nodetime.CommandSwaggerCombine` command rather than generating a tmp binary each time (fixes flaky issues due to: https://github.com/golang/go/issues/22315)
- Bump `openapiv2` version to `v2.18.0` which introduces an `ignore_comments` flag which allows `swagger-combine` to merge multiple swagger.json files with no conflicts due to nom-matching comments/descriptions
=> fix: Optimise ts-client generation

changelog.md, ignite/pkg/cosmosgen/generate.go
We should not add modules to the cache if their includes[] contains a tmp folder as generated by buf on the fly (looking at you cosmos-sdk)
=> fix: Don't cache modules with tmp includes

changelog.md, ignite/templates/module/create/files/base/x/{{moduleName}}/client/cli/suite_test.go.plush, ignite/templates/testutil/files/testutil/network/network.go.plush, ignite/templates/typed/list/files/component/x/{{moduleName}}/client/cli/query_{{typeName}}_test.go.plush, ignite/templates/typed/list/files/messages/x/{{moduleName}}/client/cli/tx_{{typeName}}_test.go.plush, ignite/templates/typed/map/files/tests/component/x/{{moduleName}}/client/cli/query_{{typeName}}_test.go.plush, ignite/templates/typed/map/files/tests/messages/x/{{moduleName}}/client/cli/tx_{{typeName}}_test.go.plush, ignite/templates/typed/singleton/files/component/x/{{moduleName}}/client/cli/query_{{typeName}}_test.go.plush, ignite/templates/typed/singleton/files/messages/x/{{moduleName}}/client/cli/tx_{{typeName}}_test.go.plush
The mutex lock into the package [`cosmos-sdk/testutil/network/network`](https://github.com/cosmos/cosmos-sdk/blob/main/testutil/network/network.go#L356) is blocking the CLI tests into a scaffolded Chain
Move to the suite test
_This PR also speeds up the chain and Ignite integration tests_
=> feat: add test suite for the cli tests

.github/workflows/docs-deploy.yml, .github/workflows/release-docker.yml, .github/workflows/release-nightly.yml
Change Github action pointing to `ignite`. The upstream one is not anymore available.
=> fix(github): change github action

changelog.md, ignite/pkg/chaincmd/chaincmd.go, ignite/pkg/chaincmd/runner/chain.go, ignite/pkg/cosmosfaucet/cosmosfaucet.go, ignite/pkg/cosmosfaucet/transfer.go, ignite/pkg/cosmosver/cosmosver.go, ignite/services/chain/faucet.go
This PR allows the faucet work with the new SDK chains and the old SDK chain
Query events are different after the sdk version `v0.50`. We should use the `query` flag, not the `events` flag, and the syntax changes slightly. The faucet tries to [get the funds](https://github.com/ignite/cli/blob/f400fbcdd4d84359991af2d31c856b92d563672d/ignite/pkg/cosmosfaucet/transfer.go#L65-L65) before sending, and the [query](https://github.com/ignite/cli/blob/f400fbcdd4d84359991af2d31c856b92d563672d/ignite/pkg/chaincmd/runner/chain.go#L272-L272) is falling.
=> feat: add faucet compatibility for latest sdk chains

ignite/templates/app/files/readme.md.plush
Addresses #3764 
The vue frontend is not automcatically scaffolded but needs to be done manually.
We now support vue and react, this should be reflected in the README.md
=> chore: Modify README within blockchain for frontend

changelog.md, ignite/templates/app/files/app/app.go.plush, ignite/templates/app/files/app/ibc.go.plush, ignite/templates/app/files/cmd/{{binaryNamePrefix}}d/cmd/root.go.plush
The IBC modules are being registered only on the server side. So, every time the client side tries to generate a new genesis, it discards the IBC modules because they are outside the basic manager. 
With the missing entries into the genesis JSON, the export genesis command constantly crashes.
This PR adds a dummy IBC modules direct manager manually into the code.
=> fix: `v0.50` ibc genesis issue 

docs/docs/01-welcome/02-install.md
Go version for Ignite is now 1.21.1 or higher, not 1.19 as mentioned in the installation process
=> docs: Increase required go version

go.mod, go.sum, ignite/cmd/ignite/analytics.go, ignite/pkg/gacli/doc.go, ignite/pkg/gacli/gacli.go
=> chore: small improvements gacli

ignite/pkg/xgit/xgit.go
Tiny PR to change the default branch name used when scaffolding a chain.
It is more in line with the [default](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches#about-the-default-branch) GH branch naming.
=> chore: change default scaffolding branch to main

ignite/internal/analytics/analytics.go, ignite/pkg/gacli/gacli.go, integration/env.go
Skip analytics for the integration tests, setting the env var `DO_NOT_TRACK` to `true`, avoiding saving fake data, and fixing the integration tests. The test is stuck on the analytics question.
=> fix: skip analytics for the integration tests

ignite/pkg/cosmosanalysis/app/app.go, ignite/pkg/cosmosanalysis/app/app_test.go, ignite/pkg/cosmosanalysis/app/testdata/modules/app_config/go.mod, ignite/pkg/cosmosanalysis/app/testdata/modules/crescent/app.go, ignite/pkg/cosmosanalysis/app/testdata/modules/crescent/go.mod, ignite/pkg/cosmosanalysis/app/testdata/modules/gaia/app.go, ignite/pkg/cosmosanalysis/app/testdata/modules/gaia/go.mod, ignite/pkg/cosmosanalysis/app/testdata/modules/juno/go.mod, ignite/pkg/cosmosanalysis/app/testdata/modules/single_app/go.mod, ignite/pkg/cosmosanalysis/app/testdata/modules/spn/go.mod, ignite/pkg/cosmosanalysis/module/module.go, ignite/pkg/cosmosanalysis/module/module_test.go, ignite/pkg/cosmosanalysis/module/options.go, ignite/pkg/cosmosgen/cosmosgen.go, ignite/pkg/cosmosgen/generate.go, ignite/pkg/cosmosgen/generate_typescript.go, ignite/pkg/cosmosgen/templates/module/index.ts.tpl, ignite/pkg/cosmosgen/templates/module/module.ts.tpl, ignite/pkg/cosmosgen/templates/root/client.ts.tpl, ignite/pkg/cosmosgen/templates/root/index.ts.tpl, ignite/pkg/cosmosgen/templates/root/modules.ts.tpl, ignite/pkg/cosmosgen/templates/root/package.json.tpl, ignite/pkg/gocmd/gocmd.go, ignite/pkg/gomodule/gomodule.go, ignite/pkg/gomodule/gomodule_test.go, ignite/pkg/gomodule/testdata/module/go.mod, ignite/pkg/xstrings/xstrings.go, ignite/pkg/xstrings/xstrings_test.go
=> fix: restore runtime app API registered module discovery

changelog.md, ignite/cmd/ignite/main.go, ignite/internal/analytics/analytics.go, ignite/pkg/gacli/gacli.go
=> refactor: remove flags from analytics

changelog.md, ignite/pkg/cosmosanalysis/module/module.go
=> fix: correct TS code generation to generate paginated fields

changelog.md, ignite/cmd/ignite/main.go
Removes extra gRPC information from Ignite App errors to have consistent CLI error messages
=> feat: remove gRPC info from Ignite Apps errors

changelog.md, ignite/pkg/cosmosgen/templates/root/client.ts.tpl
Found this while doing some more extensive testing. `coinType` has been deprecated from the root keplr `ChainInfo` type and lives only in the `Bip44` field
=> fix: Minor keplr type-checking bug

changelog.md, ignite/cmd/plugin.go, ignite/services/plugin/client_api.go
=> fix: change ignite apps to be able to run in any directory

changelog.md, ignite/templates/app/files/go.mod.plush
Bump SDK to v0.50.2
Bump confix and x/upgrade to latest point version
=> chore: bump sdk to v0.50.2 and other modules

changelog.md, ignite/pkg/cosmosanalysis/app/app.go, ignite/templates/app/files/app/ibc.go.plush, ignite/templates/app/files/cmd/{{binaryNamePrefix}}d/cmd/root.go.plush
The CLI IBC commands are falling because we cannot unpack some interfaces into the client side; this PR adds this interfaces registry.
=> fix: add missing ibc interfaces to chain client

changelog.md, ignite/templates/app/files/app/ibc.go.plush, ignite/templates/app/files/cmd/{{binaryNamePrefix}}d/cmd/commands.go.plush, ignite/templates/app/files/cmd/{{binaryNamePrefix}}d/cmd/root.go.plush
Closes: https://github.com/ignite/cli/issues/3857
Follow-up of https://github.com/ignite/cli/pull/3836
=> refactor(templates): add all ibc commands

changelog.md, ignite/pkg/gacli/gacli.go
The event name does not allow strings with underscores
=> fix(gacli): fix analytics event name

.github/workflows/gen-docs-version.yml
The action created a version without the ` v`  prefix: https://github.com/ignite/cli/pull/3887#pullrequestreview-1822887831
=> ci: add doc version prefix

ignite/templates/app/files/.github/workflows/release.yml
ref: https://github.com/ignite/example/actions/runs/7541462001/job/20528235996
default scaffolded release action will fail and `-y` does not bypass the analytics prompt.
=> chore(templates): update release action with console do not track + ` y` 

changelog.md, ignite/cmd/cmd.go, ignite/cmd/completion.go
Closes: https://github.com/ignite/cli/issues/3896
=> fix(cmd): fix cobra completion

changelog.md, ignite/cmd/cmd.go, ignite/cmd/plugin.go, ignite/services/plugin/scaffold_test.go
close #3373
- Fix panic from `app update` command;
- Use the GitHub namespace to find the plugin without the target;
=> fix: fix `app update` command and duplicated apps

docs/src/css/custom.css
This PR aims to fix the mobile menu separator on light theme to be less than `100% width`. It also corrects the button border radius.
Close: #3251
=> docs: fix menu separator mobile

docs/src/css/custom.css
Fix Searchbar border color in Docusaurus by completing the drop-shadow var style.
Close: #3245
=> style: fix searchbar border color in docs

ignite/services/chain/serve.go
Currently when `serve` fails, it shows
```
Blockchain failed to start.                           
If the new code is no longer compatible with the saved
state, you can reset the database by launching:       
ignite chain serve --reset-once         
```
Considering this will the entry point for many folks new to Ignite, probably adding a suggestion for verbose logging is a trivial, but helpful addition.
Cheers.
=> refactor(services): add suggestions for logging on `serve` failure

changelog.md, ignite/services/plugin/plugin.go
=> fix: Apps Stdout is redirected to Stderr

changelog.md, ignite/templates/app/files/app/app.go.plush, ignite/templates/app/files/app/ibc.go.plush
- Pass the `servertypes.AppOptions` to the `registerIBCModules` function so we can use it in the wasm integration app;
- Return an error for `registerIBCModules` instead panic;
=> feat: prepare for wasm app

changelog.md, ignite/services/plugin/template/.gitignore.plush
Remove the app name prefix from the `.gitignore` file. All files with the same name are being ignored. For instance, if I have an app name `wasm` and a file with the name `wasm.go` will be ignored
=> fix: remove app name prefix from the `.gitignore` file

changelog.md, ignite/cmd/plugin.go
=> fix: init app client API chainer only when chain info is available

.github/workflows/release-homebrew.yml, .github/workflows/release-snapcraft.yml, .gitpod/readme.md, docs/docs/01-welcome/02-install.md, packaging/brew/ignite.rb, packaging/readme.md, readme.md
Blocked on https://github.com/Homebrew/homebrew-core/pull/161938 to be merged.
=> chore: add homebrew formula

changelog.md, ignite/cmd/cmd.go
=> feat: skip Ignite app load for some commands

changelog.md, ignite/cmd/chain_debug.go, ignite/cmd/chain_serve.go, ignite/cmd/generate_composables.go, ignite/cmd/generate_hooks.go, ignite/cmd/generate_typescript_client.go, ignite/cmd/generate_vuex.go, ignite/cmd/relayer_configure.go, ignite/cmd/scaffold_band.go, ignite/cmd/scaffold_chain.go, ignite/cmd/scaffold_map.go, ignite/cmd/scaffold_module.go, ignite/cmd/scaffold_package.go, ignite/cmd/scaffold_query.go
Checking errors is not required because flag values are initially validated on execution while setting the string values.
Closes #1101
=> chore: remove error check after command flag get

changelog.md, ignite/cmd/chain.go, ignite/cmd/chain_lint.go, ignite/services/chain/lint.go, ignite/services/chain/lint_test.go, ignite/templates/app/files/app/ibc.go.plush
Closes: https://github.com/ignite/cli/issues/3288
=> feat(cmd): add `chain lint` command

changelog.md, ignite/cmd/chain_build.go, ignite/cmd/chain_debug.go, ignite/cmd/chain_faucet.go, ignite/cmd/chain_init.go, ignite/cmd/chain_lint.go, ignite/cmd/chain_serve.go, ignite/cmd/cmd.go, ignite/cmd/generate_composables.go, ignite/cmd/generate_go.go, ignite/cmd/generate_hooks.go, ignite/cmd/generate_openapi.go, ignite/cmd/generate_typescript_client.go, ignite/cmd/generate_vuex.go, ignite/cmd/plugin.go, ignite/cmd/scaffold.go, ignite/cmd/scaffold_band.go, ignite/cmd/scaffold_chain.go, ignite/cmd/scaffold_configs.go, ignite/cmd/scaffold_message.go, ignite/cmd/scaffold_module.go, ignite/cmd/scaffold_package.go, ignite/cmd/scaffold_params.go, ignite/cmd/scaffold_query.go, ignite/pkg/xfilepath/xfilepath.go, ignite/pkg/xfilepath/xfilepath_test.go, ignite/pkg/xgenny/sourcemodification.go, ignite/services/chain/chain.go
close #3982
close #3981
- Move `sourceModificationToString` function to `xgenny` pkg;
- Move `relativePath` function to `xfilepath` pkg;
- Move `newChainWithHomeFlags` function to `services` pkg;
=> feat(cmd): make some `cmd` pkg functions public

readme.md
Adds a Widget to the README that displays Discord and users online.
=> docs: Add Discord widget to README

changelog.md, ignite/templates/app/files/app/ibc.go.plush, ignite/templates/app/files/cmd/{{binaryNamePrefix}}d/cmd/root.go.plush
Closes: https://github.com/ignite/cli/issues/3994
=> fix(templates): fix interface check for ibc modules

readme.md
Shield button just linked to an image but should have the Discord invite as link.
=> docs: add invite link to chat shield

changelog.md, ignite/config/chain/base/config.go, ignite/pkg/chaincmd/chaincmd.go, ignite/pkg/chaincmd/runner/account.go, ignite/pkg/cosmosfaucet/cosmosfaucet.go, ignite/services/chain/faucet.go, ignite/services/chain/init.go
close #3967
Add address index and account number to the chain config to be added into the key add command flag.
Scaffold a mars chain (`ignite s chain mars`) and use this test `config.yml` file:
```yaml
version: 1
accounts:
- name: alice
mnemonic: apple pony round crazy boil solid inch beef equal attract soul accuse nice thumb shadow egg drum valley grace wish elbow hat salute pair
cointype: 118
account_number: 1
address_index: 2
coins:
- 20000token
- 200000000stake
- name: bob
coins:
- 10000token
- 100000000stake
client:
openapi:
path: docs/static/openapi.yml
faucet:
name: bob
coins:
- 5token
- 100000stake
validators:
- name: alice
bonded: 100000000stake
```
- run the chain with ignite: `ignite c serve --clear-cache --reset-once`, and you can see the Alice address will be …
=> feat(config): add HD wallet parameters `address index` and `account number` to the chain account config

changelog.md, ignite/cmd/scaffold_chain.go, ignite/services/scaffolder/configs.go, ignite/services/scaffolder/init.go, ignite/services/scaffolder/message.go, ignite/services/scaffolder/module.go, ignite/services/scaffolder/packet.go, ignite/services/scaffolder/params.go, ignite/services/scaffolder/query.go, ignite/services/scaffolder/scaffolder.go, ignite/services/scaffolder/type.go, ignite/templates/app/files/app/ibc.go.plush
Adds a `--skip-proto` flag to `s chain` to speed up scaffolding.
Advanced user can enjoy faster scaffolding time but still need to run `ignite chain serve` or `ignite chain build` afterwards.
=> feat(cli): add `skip-proto` flag to `s chain` command

ignite/services/plugin/template/go.mod.plush
Removes this temporary commit https://github.com/ignite/cli/pull/3945/commits/2e2cea46f40ebb15f250bd34e892c75aad720a45 now that https://github.com/ignite/cli/pull/3945 has been merged
=> chore: remove temporary hardcoded commit

.github/workflows/test.yml
codecov is blocking all prs because it is very flaky (still advocating to use sonarcloud, but that's another story)
this updates CI to not make fail the kob when codecov fails
=> ci: don't fail if codecov fails

readme.md
Tutorials are now hosted on tutorials.ignite.com - let's reflect this on the README
=> docs: Update readme.md with link to tutorials

changelog.md, ignite/config/plugins/config.go, ignite/services/plugin/plugin.go, ignite/services/plugin/plugin_test.go
Follow-up of https://github.com/ignite/cli/pull/4117
Fixes some edge cases
=> fix(plugins): correct relative path support

ignite/pkg/cosmosver/cosmosver.go, integration/readme.md
Found this while doing the rollkit app, docs for integration doesn't match the new api and latest version doesn't return the actual latest version.
=> chore: get correct `cosmosver.Latest` version

changelog.md, ignite/pkg/protoanalysis/protoutil/helpers.go, ignite/templates/module/create/configs.go, ignite/templates/module/create/params.go
Found in https://github.com/ignite/cli/pull/4118 (https://github.com/ignite/cli/actions/runs/9023607632/job/24795771972?pr=4118).
This must be merged before. This PR allows failing at scaffolding instead of failing at proto generation.
=> fix(protoanalysis,templates): fail at duplicate fields

changelog.md
This release includes a few notable bug fixes and features:
* Compatibility with the new Ignite Rollkit App. For easily scaffolding a rollkit app when using Cosmos SDK v0.50.6+
* Improve footgun prevention when scaffolding a chain with clashing store prefixes.
* Preparing work for the new Ignite scaffolding API with the introduction of the `xast` package.
Following an exhaustive list of changes in this release:
- [#4108](https://github.com/ignite/cli/pull/4108) Add `xast` package (cherry-picked from [#3770](https://github.com/ignite/cli/pull/3770))
- [#4110](https://github.com/ignite/cli/pull/4110) Scaffold a consumer chain with `interchain-security` v5.0.0.
- [#4117](https://github.com/ignite/cli/pull/4117), [#4125](https://github.com/ignite/cli/pull/4125) Support relative path when …
=> chore: prepare v28.4.0

docs/docs/06-migration/readme.md
Explain the `gen-mig-diffs` functionality and a Get Started Guide.
=> docs: Add to the docs how to use the migration guide

ignite/internal/tools/gen-mig-diffs/cmd/root.go, ignite/internal/tools/gen-mig-diffs/go.mod, ignite/internal/tools/gen-mig-diffs/go.sum, ignite/internal/tools/gen-mig-diffs/pkg/repo/repo.go, ignite/internal/tools/gen-mig-diffs/pkg/scaffold/scaffold.go
If the user doesn't specify the `from` version, we get the last major release instead of the last patch release. This way, we can better generate migration docs with significant migration content
=> feat: by default generate the migration docs from a major version to another

changelog.md, ignite/cmd/scaffold.go, ignite/pkg/protoanalysis/protoutil/creator.go, ignite/templates/field/datatype/int.go, ignite/templates/typed/map/map.go
Closes: https://github.com/ignite/cli/issues/1723
=> refactor(templates)!: scaffold int64 instead of int32

changelog.md, ignite/services/chain/init.go, ignite/services/chain/runtime.go
The default `client.toml` doesn't have `chain-id` specified, which requires a user to always use the `--chain-id` flag when using directly the binary instead of ignite (that does autodetection by querying the node status)
=> feat(services): set default chain-id in client.toml

changelog.md, ignite/templates/app/files-consumer/cmd/{{binaryNamePrefix}}d/cmd/root.go.plush, ignite/templates/app/files/cmd/{{binaryNamePrefix}}d/cmd/root.go.plush, ignite/templates/app/files/go.mod.plush
Just tagged https://github.com/cosmos/cosmos-sdk/releases/tag/client%2Fv2.0.0-beta.2 with quite good improvements and some wiring changes.
This PR upgrades it in Ignite scaffolded chains
=> refactor: bump client/v2 to v2.0.0-beta.2

changelog.md, ignite/templates/app/files/{{protoDir}}/buf.gen.pulsar.yaml.plush, ignite/templates/app/proto_test.go, integration/app/cmd_proto_path_test.go
Closes: https://github.com/ignite/cli/issues/4174
=> fix(buf): set correct prefix for api

changelog.md, ignite/templates/app/files-consumer/cmd/{{binaryNamePrefix}}d/cmd/root.go.plush, ignite/templates/app/files/app/config.go.plush, ignite/templates/app/files/cmd/{{binaryNamePrefix}}d/cmd/config.go.plush, ignite/templates/app/files/cmd/{{binaryNamePrefix}}d/cmd/root.go.plush
Closes: https://github.com/ignite/cli/issues/4185
=> refactor(templates): Set and seal SDK global config in `app/config.go`

ignite/services/plugin/template/.gitignore.plush
Idea taken from Spawn: https://github.com/rollchains/spawn/blob/v0.50.2/simapp/.gitignore#L1
In cosmosregistry/example, I did it with the mean of a `THANKS.md`: https://github.com/cosmosregistry/example/blob/754905a/scripts/rename.sh#L45-L47 but having it not cluttering the root  directory is better.
This will be useful as we are removing the branded placeholders for AST only.
=> chore: add scaffolding branding

changelog.md, ignite/services/plugin/grpc/v1/interface_flag.go
Add any flag to the extension, and don't use the flag or don't set a default value to this flag crashes the extension
=> fix: set default values for extension flag to dont crash ignite

changelog.md, ignite/templates/app/files-consumer/app/app.go.plush, ignite/templates/app/files/app/app.go.plush, ignite/templates/module/create/files/base/x/{{moduleName}}/keeper/keeper.go.plush
close #4066
Since we are not using the module keeper as a pointer, the scoped keeper can't be saved inside the keeper structure, causing chain crashes. This PR makes the App handle the scoped keeper logic.
=> fix: avoid create duplicated scopedKeppers

changelog.md, ignite/templates/ibc/packet.go, ignite/templates/module/create/files/base/x/{{moduleName}}/module/module.go.plush
remove deprecated `sdk.MustSortJSON` used for GetSignbytes, this is now automatic with amino signing.
=> refactor: remove deprecated `sdk.MustSortJSON`

ignite/pkg/cosmosclient/cosmosclient.go
In `CreateTx` in `pkg/cosmosclient/cosmosclient.go` if gas is set to auto the function will calculate gas using the gasometer.
The gas adjustment is used in this calculation (at least in the cosmos sdk implementation)
https://github.com/cosmos/cosmos-sdk/blob/10465a6aabdfc9119ff187ac3ef229f33c06ab45/client/tx/tx.go#L149-L166
As the `txf.WithGasAdjustment` is set after the calculation the function will use the default value.
This PR moves the assignment to before the calculation so that the gas adjustment is correctly applied in the gasometer estimation.
=> fix: set gas adjustment before calc

changelog.md, ignite/cmd/plugin_default.go, ignite/cmd/plugin_default_test.go
hermes/v0.2.4 has been tagged so we can re-enable it on ignite
=> chore: bring back default extensions

changelog.md, ignite/cmd/plugin_test.go, ignite/services/plugin/flag.go, ignite/services/plugin/flag_test.go, integration/plugin/testdata/example-plugin/main.go
close https://github.com/ignite/apps/issues/116
This PR creates a simple flag parser, so we don't need to depend on another library to parse a few objects. It also solves the [issue of missing default values in the flags](https://github.com/ignite/apps/issues/116).
=> feat: add custom flag parser for extensions

.github/workflows/docs-deploy.yml, .github/workflows/release-docker.yml, .github/workflows/release-nightly.yml
This job has been timing out, and we don't need it anyway: https://github.com/ignite/cli/actions/runs/10032367974/job/27723961043 / https://github.com/ignite/consecutive-workflow-action as we use `cancel-in-process`.
=> ci: remove consecutiveness step

changelog.md, ignite/cmd/chain_build.go, ignite/cmd/chain_debug.go, ignite/cmd/chain_faucet.go, ignite/cmd/chain_init.go, ignite/cmd/chain_lint.go, ignite/cmd/chain_serve.go, ignite/cmd/cmd.go
We are using the verbose flag in some parts of the code, but the flag is no set
=> fix: add missing verbose mode flags

changelog.md, ignite/templates/module/create/files/base/x/{{moduleName}}/module/genesis.go.plush, ignite/templates/module/create/files/base/x/{{moduleName}}/module/genesis_test.go.plush, ignite/templates/module/create/files/base/x/{{moduleName}}/module/module.go.plush, ignite/templates/module/create/ibc.go, ignite/templates/typed/list/genesis.go, ignite/templates/typed/map/map.go, ignite/templates/typed/singleton/singleton.go
Avoid using a lot of panic calls into the `InitGenesis` and `ExportGenesis` methods and panic in the parent function. This also make the code more testable.
=> feat(template): only panics the module in the most top function level

.gitpod.Dockerfile, docs/docs/01-welcome/02-install.md, docs/versioned_docs/version-v28/01-welcome/02-install.md, go.mod, ignite/internal/plugin/testdata/execute_fail/go.mod, ignite/internal/plugin/testdata/execute_ok/go.mod, ignite/internal/tools/gen-config-doc/go.mod, ignite/internal/tools/gen-mig-diffs/go.mod, ignite/pkg/cosmosanalysis/app/testdata/modules/juno/go.mod, ignite/pkg/cosmosanalysis/testdata/chain-sdk-fork/go.mod, ignite/pkg/cosmosver/testdata/chain-sdk-fork/go.mod, ignite/pkg/cosmosver/testdata/chain-sdk-local-fork/go.mod, ignite/pkg/gomodule/testdata/module/go.mod, ignite/services/plugin/template/go.mod.plush, ignite/templates/app/files/go.mod.plush, integration/plugin/testdata/example-plugin/go.mod, scripts/indocker
Bumps to Go 1.23 for https://github.com/ignite/cli/pull/4289
=> chore: bump to Go 1.23

ignite/templates/typed/list/list.go
The list name is using the `_seq` suffix instead the sequence.
=> fix(templates): wrong name for list and seq

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/meta.md
Improves the existing issue templates by expanding context sections, adding clear guidance for bug reports and feature requests, and introducing new templates for enhancements and meta tasks. These updates streamline issue creation, ensuring contributors provide detailed and actionable information for better development efficiency and workflow clarity.
Issue templates also now follow the action-based issue title convention**, aligning with the new approach of focusing titles on actions while characteristics and types are handled through labels.
** "FIX" may be reconsidered.
=> docs: improve issue templates

changelog.md, ignite/cmd/chain_build.go, ignite/cmd/chain_debug.go, ignite/cmd/chain_faucet.go, ignite/cmd/chain_init.go
Closes: https://github.com/ignite/cli/issues/4291
=> fix(cmd): add missing --config handling

ignite/internal/analytics/analytics.go
Our do not track check was wrong and always returning true.
This is why we were getting nothing.
=> fix(analytics): check do not track

changelog.md, ignite/cmd/model/chain_serve.go, ignite/pkg/announcements/announcement.go, ignite/pkg/announcements/announcement_test.go, ignite/pkg/cliui/icons/icon.go
fixes #4211
The url is not going to be used anywhere else, so didn't make a separate variable for it - please let me know if the icon needs a change or the url to be a constant
=> feat: added survey link 

ignite/cmd/ignite/main.go, ignite/cmd/testnet_inplace.go, ignite/internal/analytics/analytics.go, ignite/pkg/announcements/announcement.go, ignite/pkg/sentry/sentry.go
Due to the way the Sentry client parses the DSN, it isn't possible to use a proxy.
Otherwise, the request will all fail due to a wrong DSN.
We should just hardcode it in ignite, which is fine IMHO as sentry doesn't deprecate the DSN.
I have seen other open source Go project do the same.
Opened https://github.com/ignite/infraconfig/pull/6 to delete the proxy from infra.
=> chore: do not proxy sentry dsn

ignite/cmd/ignite/main.go, ignite/cmd/testnet_inplace.go, ignite/internal/analytics/analytics.go, ignite/pkg/announcements/announcement.go, ignite/pkg/sentry/sentry.go
Manually backporting https://github.com/ignite/cli/pull/4359 as mergify has issues.
=> chore: do not proxy sentry dsn (#4359)

changelog.md, ignite/cmd/testnet_inplace.go
=> refactor: use different chain id for in place testnet

changelog.md, ignite/templates/app/files/Makefile.plush
=> feat(templates): scaffold makefile

ignite/cmd/bubblemodel/testnet_multi_node.go, ignite/cmd/testnet_multi_node.go, ignite/pkg/chaincmd/in-place-testnet.go, ignite/pkg/chaincmd/runner/chain.go, ignite/pkg/markdownviewer/markdownviewer.go
Follow-up of https://github.com/ignite/cli/pull/4377. Simply runs `make lint-fix`
=> chore: `make lint-fix`

changelog.md, ignite/pkg/cosmosutil/gentx.go, ignite/pkg/cosmosutil/gentx_test.go, ignite/pkg/cosmosutil/testdata/gentx2.json
Fix gentx parser into the cosmosutil package because the use of Delegator Address in MsgCreateValidator is deprecated
https://github.com/cosmos/cosmos-sdk/blob/8bfcf554275c1efbb42666cc8510d2da139b67fa/proto/cosmos/staking/v1beta1/tx.proto#L66-L69
=> fix: fix gentx parser into the cosmosutil package

ignite/cmd/bubblemodel/chain_debug_test.go, ignite/cmd/bubblemodel/chain_serve_test.go, ignite/cmd/bubblemodel/testnet_multi_node.go, ignite/cmd/chain_debug.go, ignite/cmd/chain_serve.go, ignite/cmd/testnet_multi_node.go, ignite/templates/app/files/cmd/{{binaryNamePrefix}}d/cmd/commands.go.plush, ignite/templates/app/files/cmd/{{binaryNamePrefix}}d/cmd/testnet_multi_node.go.plush
close https://github.com/ignite/cli/pull/4398#issuecomment-2464620202
because can't push to branch `merge/bp/release/v28.x.y/pr-4377`
=> feat: Add multi node (validator) testnet (backport #4377)

docs/versioned_docs/version-v28/02-guide/04-blog.md
- Correct the error: The `Post` in `&types.QueryShowPostResponse` is a pointer type `Post *Post`
- Add a build statement before starting the blockchain; otherwise, the code will throw an error, which might confuse readers.
- fix comment: `bei` => `by`
=> docs(blog): fix pointer type and add build steps

ignite/templates/typed/list/files/simapp/x/{{moduleName}}/simulation/{{typeName}}.go.plush
In simapp template, I found one mistake that uses MsgUpdateXXX where it should use MsgDeleteXXX
=> fix(templates): fix simapp simulation method update->delete

ignite/templates/app/files/app/export.go.plush, ignite/templates/ibc/files/packet/component/x/{{moduleName}}/keeper/{{packetName}}.go.plush, ignite/templates/module/create/files/ibc/x/{{moduleName}}/module/module_ibc.go.plush, integration/relayer/cmd_relayer_test.go
Follow-up of https://github.com/ignite/cli/pull/4432
Removal of sdk.Context in modules. The app (v1) should still have sdk.Context while in sdk v2 not.
Next PR is integrating SDK v2.
=> refactor(templates): use go context instead of sdk.Context

docs/versioned_docs/version-v0.27/03-clients/03-vue.md, docs/versioned_docs/version-v0.27/04-network/02-introduction.md, docs/versioned_docs/version-v28/02-guide/06-tokenfactory/01-tokenfactory.md
=> docs: remove repetitive words

changelog.md, ignite/cmd/chain_serve.go, ignite/cmd/cmd.go, ignite/services/chain/serve.go
Closes: https://github.com/ignite/cli/issues/4251
=> feat(cmd): allow to manually skip rebuilding

.github/workflows/test-lint.yml, ignite/cmd/cmd.go, ignite/cmd/doctor.go, ignite/cmd/plugin.go, ignite/config/plugins/parse.go, ignite/pkg/cliui/entrywriter/entrywriter.go, ignite/pkg/cosmostxcollector/adapter/postgres/schemas.go, ignite/pkg/openapiconsole/console.go, ignite/pkg/protoanalysis/protoutil/helpers.go, ignite/services/scaffolder/type.go, ignite/templates/field/datatype/custom.go
Linter job is broken in release/v28.y.x (https://github.com/ignite/cli/actions/runs/12686175460/job/35358078508)
This brings the job from main to this branch
=> ci: fix linter in release/v28.x.y

changelog.md, ignite/cmd/chain_simulate.go, ignite/pkg/chaincmd/runner/simulate.go, ignite/pkg/chaincmd/simulate.go, ignite/services/chain/simulate.go, ignite/templates/app/files/cmd/{{binaryNamePrefix}}d/cmd/commands.go.plush
Updates simulation with latest 0.52.
`-Period` got removed in https://github.com/cosmos/cosmos-sdk/pull/23341 as invariant isn't a thing in 0.52 anymore.
Additionally, this closes https://github.com/ignite/cli/issues/4308, by letting the user pass any sim test directly (default to the whole app simulation)
=> refactor!: sync with latest simulation changes + make it extensible

ignite/services/scaffolder/chain_registry.go
Follow-up of https://github.com/ignite/cli/pull/4413
Required by https://github.com/cosmology-tech/create-cosmos-app/blob/fd87039feee9568a86aa8d8d19edea8f4a78f599/templates/chain-template/utils/faucet.ts#L21-L22
=> refactor: add apis to chain-registry

ignite/pkg/chainregistry/asset.go, ignite/pkg/chainregistry/chain.go, ignite/pkg/chainregistry/chainregistry.go, ignite/pkg/chainregistry/consts.go, ignite/pkg/chainregistry/doc.go, ignite/services/scaffolder/chain_registry.go
This PR exposes the chain registry structs that were recently added.
This package will then be used by Ignite Connect app to avoid duplication (https://github.com/ignite/apps/pull/102)
=> feat: expose chain-registry structs

changelog.md, ignite/pkg/archive/tar_gz.go, ignite/services/chain/build.go, ignite/templates/app/files/.github/workflows/release.yml
Someone on discord found an issue with our release job. This fixes it.
=> fix(chain): fix issue in release ci and command

changelog.md, ignite/templates/field/datatype/types.go
close #4284
When we Scaffold a `uint64` type, Ignite understands it as a custom type because it is in the code but is not a valid default type. This PR adds `uint64` and `int64` as default types.
```shell
ignite scaffold params blocksPerYear:uint64 -y
```
=> fix: scaffold an `uint64 type crashs Ignite

changelog.md, ignite/pkg/cosmosclient/cosmosclient.go
Cosmos SDK v0.52 does not allow configuration changes when the Config is sealed.
`SetConfigAddressPrefix` function cannot be excuted after the Config is set, but instead must be used `WithAddressPrefix` in  client.Context.
Closes: https://github.com/ignite/cli/issues/2744
=> fix: set address prefix with sdk v0.52

changelog.md, ignite/services/plugin/flag.go, ignite/services/plugin/flag_test.go, ignite/services/plugin/grpc/v1/interface_flag.go
Fix default values for app flags, it always gets zero if the value is not set
=> fix: default flag parser for apps

ignite/services/plugin/template/go.mod.plush, ignite/templates/app/files/app/ibc.go.plush
Now that https://github.com/ignite/cli/pull/4477 has been merged, we can put the main branch for the plugin tests.
This as well implement a comment about the usage of .String()
=> test: fix build

ignite/templates/app/files/Makefile.plush
Show how to install necessary proto dependencies (for those using buf directly) and not proto-builder (that may get out of date with go version change):
ref: https://github.com/cosmonity/example/commit/ac21eb6e9e77af68e4032a1f75af989b82fd9c18
=> refactor(templates): do not use proto-builder

ignite/cmd/testnet.go
Closes: https://github.com/ignite/cli/issues/4425
=> docs: update long description `testnet`

changelog.md, ignite/pkg/cosmosclient/cosmosclient.go
This reverts commit 8a382f92158f636bf9831cf3cc6309e8fe5d862b.
ref: https://github.com/ignite/cli/pull/4487#issuecomment-2649186038
=> Revert "fix: set address prefix with sdk v0.52 (#4486)"

.github/workflows/test-cov.yml, .github/workflows/test-integration.yml, .github/workflows/test.yml, changelog.md, ignite/config/chain/base/config.go, ignite/services/chain/faucet.go
Allow to specify fee to be paid by the faucet in the config.
An user on discord had the issue that when the chains is requiring the fee, the faucet will fail.
This was already supported, but we didn't have a field to pass in the config for it.
=> feat(services): add faucet fee config

.gitpod.Dockerfile, Dockerfile
Closes: https://github.com/ignite/cli/issues/4516
This will be reverted in https://github.com/ignite/cli/pull/4509
=> build: switch dockerfile to go 1.23

changelog.md, ignite/pkg/chaincmd/runner/runner.go
Should resolve the issue when using Go 1.24 with Ignite.
Won't solve the nasty logs sonic is printing however, as it will be fixed in https://github.com/ignite/cli/pull/4509 after the sonic library bump.
=> fix(chaincmd): skip non json in JSONEnsuredBytes

changelog.md
Ignite CLI v29.0.0-beta.1 introduces **IBC-go v10 (IBC v2) support** and default **collections support**, enhancing blockchain interoperability and data management. Other key additions include `scaffold configs`, `scaffold params` commands, to help you best in your module development. New tools like `chain lint` and automatic buf config migration to v2 (via `ignite doctor`) have been added to streamline development, and much more!
The [`gen-mig-diffs`](https://tutorials.ignite.com/guide-to-use-gen-mig-diffs-for) tool can help you upgrade to v29 easily.
Any feedback and bug reports are welcome. Documentation is being updated to reflect this new beta.
Following an exhaustive list of changes in this release:
- [#3707](https://github.com/ignite/cli/pull/3707) and …
=> chore: prepare v29.0.0-beta.1

changelog.md, go.mod, go.sum, ignite/cmd/account_create.go, ignite/cmd/account_delete.go, ignite/cmd/account_export.go, ignite/cmd/account_import.go, ignite/cmd/cmd.go, ignite/pkg/cliui/clispinner/simple.go, ignite/pkg/cliui/colors/colors.go
close #2432
- remove `github.com/gookit/color`;
- use `session.print` instead `cmd.print`;
=> refactor: remove `github.com/gookit/color`

docs/docusaurus.config.js
ref: https://github.com/ignite/cli/actions/runs/13731942058/job/38410500388.
v0.25 isn't maintained, so I do not think updating it/keeping the link valid is possible nor makes sense.
=> docs: fix docs build

changelog.md, go.mod, ignite/cmd/account.go, ignite/cmd/account_create.go, ignite/cmd/account_import.go, ignite/cmd/account_list.go, ignite/cmd/account_show.go, ignite/cmd/scaffold_chain.go, ignite/cmd/scaffold_chain_registry.go, ignite/cmd/testnet_inplace.go, ignite/pkg/chainregistry/chain.go, ignite/pkg/cosmosaccount/cosmosaccount.go, ignite/pkg/cosmosclient/bank.go, ignite/pkg/cosmosclient/cosmosclient.go, ignite/services/chain/chain.go, ignite/services/chain/chain_test.go, ignite/services/scaffolder/chain_registry.go, ignite/services/scaffolder/init.go, ignite/templates/app/app.go, ignite/templates/app/files-minimal/app/app.go.plush, ignite/templates/app/files/app/app.go.plush, ignite/templates/app/files/app/config.go.plush, ignite/templates/app/options.go, integration/app/cmd_app_test.go
Add flags to set coin type on commands. Add getters for bech32 prefix and coin type.
It is useful for the chain-registry config, and web explorer config.
=> feat: wire custom coin type and get bech32 prefix

changelog.md, ignite/pkg/cosmosfaucet/cosmosfaucet.go, ignite/pkg/cosmosfaucet/transfer.go, ignite/services/chain/faucet.go
Closes: https://github.com/ignite/cli/issues/4528
Ignite CLI will now check the user `config.yml` for an indexer override and skip the checks accordignly:
```yaml
validators:
- name: alice
bonded: 100000000stake
config:
tx_index:
indexer: "null"
```
=> feat(cosmosfaucet): loosen faucet check when indexer disabled

actions/cli/Dockerfile, actions/release/vars/action.yml
**Environment:**
- action version: v28.9.0
- reponame: kepler
- cosmos version: v0.50.13
**Step output:**
```bash
echo "- should_release: true"
echo "- is_release_type_latest: true"
echo "- tag_name: latest"
echo "- tarball_prefix: 'kepler'_latest"
```
**Result:**
```
fe7c65961ba0a91e097c75c78d68ecaf06d8ae078320ab2b5a11383a05f912d6  'kepler'_latest_darwin_amd64.tar.gz
64dd9ecf56ad50a195f6f493d5f10ed0ec9d95bf6b366d3a3c903fe8d11cb739  'kepler'_latest_darwin_arm64.tar.gz
e872fda69c7d951f5b626f32035b37876358f0addec13dc78d6c797f8dea8359  'kepler'_latest_linux_amd64.tar.gz
```
---
Root was set, but I was having issues getting the `release_checksum` from:
```yaml
- name: Publish the Release
uses: softprops/action-gh-release@v1
if: ${{ steps.vars.outputs.should_release == 'true' }}
with: …
```
=> fix: Adjust GHA Dockerfile UID/GID and fix tarball_prefix quotes

changelog.md, ignite/pkg/xast/function.go, ignite/pkg/xast/function_test.go
`AppendFuncAtLine` would only work with one line expression.
This fixes it by re-using `codeToBlockStmt`.
=> feat(xast): allow append arbitrary blocks

ignite/pkg/cosmosutil/genesis/genesis.go, ignite/pkg/goanalysis/goanalysis.go, ignite/pkg/gomodule/gomodule.go, ignite/pkg/protoanalysis/protoanalysis.go
There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.
=> refactor: use slices.Contains to simplify code

changelog.md, ignite/pkg/xast/function.go, ignite/pkg/xast/function_test.go
Use the `xast` package to add a test case to a table. The test will add a new test case with weird indentation. This PR fixes this issue and adds a new test case.
eg:
```go
}, {
desc: "valid first genesis state",
genState: GenesisState{}}, {
desc: "valid second genesis state",
genState: GenesisState{}},
```
Expected:
```go
}, {
desc:     "valid first genesis state",
genState: GenesisState{},
}, {
desc:     "valid second genesis state",
genState: GenesisState{},
},
```
=> fix: xast test case indentation

changelog.md, ignite/templates/field/field.go, ignite/templates/field/field_test.go
`IsSlice` was doing the shortcut of NonIndexable = Slices.
While 99% true, this isn't the case for Coin.
=> refactor(templates): harden `IsSlice`

ignite/templates/app/files/cmd/{{binaryNamePrefix}}d/cmd/commands.go.plush
The wasm app adds the flags to `addModuleInitFlags`, which is great, as multiple app may add flags (think of rollkit + 
cosmwasm).
We should re-add this to the template as no-op to not break plugins.
=> fix(templates): make v29 compatible with wasm app

changelog.md, ignite/cmd/generate.go, ignite/cmd/scaffold.go, ignite/cmd/scaffold_chain.go, ignite/pkg/cmdrunner/cmdrunner.go, ignite/pkg/env/env.go, ignite/services/plugin/plugin.go
Closes: https://github.com/ignite/cli/issues/3077
While the environment variable was doing what this issue was requesting, adding it to the command makes the UX better and the verbosity only apply for the CLI part only (and not the plugin part).
=> feat: add verbose flag to scaffold and generate commands

ignite/pkg/cosmosbuf/buf.go, integration/client.go
Optimize code using a more modern writing style.
=> refactor: use maps.Copy for cleaner map handling

docs/docusaurus.config.js
Change links in docs footer, that lead nowhere: press and accelerator pages are not available.
=> docs: Change links in footer, that lead nowhere

changelog.md, ignite/pkg/cosmosanalysis/module/message.go, ignite/pkg/cosmosanalysis/module/module.go, ignite/pkg/cosmosanalysis/module/module_test.go, ignite/pkg/cosmosanalysis/module/testdata/earth/proto/planet/mars/mars.proto, ignite/pkg/cosmosanalysis/module/testdata/planet/proto/planet/mars/mars.proto
Fixes the message filtering in cosmosanalysis.
=> refactor(cosmosanalysis): proper message filtering

changelog.md, ignite/templates/field/datatype/address.go, ignite/templates/field/datatype/types.go, ignite/templates/field/datatype/types_test.go, ignite/templates/field/field.go, ignite/templates/ibc/packet.go, ignite/templates/message/message.go, ignite/templates/typed/list/list.go, ignite/templates/typed/map/map.go, ignite/templates/typed/singleton/singleton.go, integration/other_components/cmd_message_test.go
Closes: https://github.com/ignite/cli/issues/4668
I went with Danilo suggestion:
```
ignite scaffold list message from:address to:address msg:string
```
=> feat: add address type

docs/docs/02-guide/03-hello-world.md
"fmt" was missing in the imports of the hello-world tutorial but used.
=> docs: Add fmt to imports hello-world

changelog.md, docs/docs/06-migration/v29.0.0.md, ignite/pkg/cosmosanalysis/app/app.go, ignite/pkg/cosmosanalysis/app/testdata/app_generic.go, ignite/pkg/cosmosanalysis/app/testdata/app_minimal.go, ignite/pkg/cosmosanalysis/app/testdata/modules/app_config/app.go, ignite/pkg/cosmosanalysis/app/testdata/modules/single_app/app.go, ignite/pkg/cosmosanalysis/app/testdata/two_app.go, ignite/pkg/cosmosanalysis/cosmosanalysis.go, ignite/pkg/cosmosanalysis/cosmosanalysis_test.go, ignite/pkg/cosmosanalysis/module/testdata/earth/app/app.go, ignite/pkg/cosmosanalysis/module/testdata/planet/app/app.go
Closes: https://github.com/ignite/cli/issues/1324
ref: https://github.com/ignite/cli/issues/4697#issuecomment-2902849472
v29: embeds runtime
v28: embeds runtime
v27: embeds baseapp
This should be future proof as apps should be embedding runtime or baseapp (e.g https://github.com/atomone-hub/atomone/blob/main/app/app.go#L74)
=> feat: improve app detection

changelog.md, ignite/cmd/generate_typescript_client.go, ignite/templates/app/files/go.mod.plush
Closes: https://github.com/ignite/cli/issues/4623, https://github.com/ignite/cli/issues/4708
---
Ignite CLI v29.0.0 is finally there! This new version is packed with new features and dev ux improvement: 
* As always, Ignite scaffolds the latest Cosmos Stack: Cosmos SDK v0.53, IBC-go v10 (IBC v1 and v2 enabled), and all the latest features enabled 💥.
* New scaffolding commands: `config`, `params` and new scaffolding flags: `--default-denom` to allow you to do more, with less.
* Thanks to an overhaul of the CLI internal, Ignite now scaffolds a chain without cluttering it with the infamous `// this line is used by starport scaffolding` line.
* Scaffolded modules now uses `cosmossdk.io/collections` for state management.
* New `xast` package to help developers make Ignite Apps even easily (an …
=> chore: bump client/v2 + prepare v29

.github/workflows/gen-docs-migration.yml, .github/workflows/release-homebrew.yml, scripts/gen-mig-diffs
Fixes https://github.com/ignite/cli/actions/runs/15361542890
=> ci: fix gen mig diff job

go.mod, go.sum
Fixes #4752
by using https://github.com/bytedance/sonic/releases/tag/v1.14.0
Log:
```
$ go get github.com/bytedance/sonic@latest && go mod tidy
go: upgraded github.com/bytedance/sonic v1.13.2 => v1.14.0
go: upgraded github.com/bytedance/sonic/loader v0.2.4 => v0.3.0
```
Related:
* upstream https://github.com/bytedance/sonic/pull/808
* downstream https://github.com/Homebrew/homebrew-core/pull/226636
=> fix(deps): Support Go 1.25 by upgrading github.com/bytedance/sonic to v1.14.0

.github/workflows/test-integration.yml, changelog.md, ignite/templates/app/files/go.mod.plush
replace the broken `github.com/bytedance/sonic` version in the `go.mod` 
Sometimes the `go.mod` downloads the `v1.14`:
https://github.com/ignite/cli/actions/runs/16953585035/job/48051162243?pr=4791#step:4:100
but the `cosmossdk.io/log` uses the `v1.13`
https://github.com/ignite/cli/actions/runs/16953585035/job/48051162243?pr=4791#step:4:224
=> fix: replace broken `bytedance/sonic` version in the `go.mod`
