ignite/cli

templates/app/templates/frontend/package-lock.json, templates/app/templates/frontend/package.json, templates/app/templates/frontend/src/components/Wallet.vue, templates/app/templates/frontend/src/store/index.js
Switching to a newer library for wallet management and transaction signing.
https://github.com/CosmWasm/cosmjs/
From the users' perspective nothing has changed, it should correctly sign in to a wallet, sign and send transactions.
close https://github.com/tendermint/starport/issues/24
=> Switch from tendermint/sig to CosmJS

scripts/npm-publish
resolves https://github.com/tendermint/starport/issues/43
=> ci: add README to npm package

.github/workflows/test.yml
=> ci: run unit tests for Starport

readme.md
Added `starport add wasm` to the readme.
=> Updated readme with CosmWasm

go.mod, go.sum, templates/app/templates/frontend/package-lock.json, templates/app/templates/frontend/package.json, templates/app/templates/frontend/src/store/index.js
* Replaced `@cosmjs/sdk38` with `@cosmjs/launchpad`
* Removed wallet from Vuex state
close https://github.com/tendermint/starport/issues/73
=> Update to @cosmjs/launchpad

go.mod, go.sum, interface/cli/starport/cmd/serve.go
and more simplifications on serve.
depends on https://github.com/tendermint/starport/pull/82,
solves a part of https://github.com/tendermint/starport/issues/81.
=> cli/starport/cmd: use context for cancellation

go.mod, go.sum, interface/cli/starport/cmd/serve.go, services/serve/serve.go
to the new services/serve package.
this is just a 1:1 move from one pkg to another, source code has not changed.
depends on https://github.com/tendermint/starport/pull/86,
solves a part of https://github.com/tendermint/starport/pull/71.
=> services/serve: move serve logic from starport/cmd

starport/services/serve/serve.go
=> services/serve: general refactoring, simplify code

starport/templates/add/new.go
Reference: https://github.com/CosmWasm/wasmd/blob/master/app/app.go#L302
=> Added fix to add wasm cmd (fix #114)

go.mod, go.sum, starport/services/serve/serve.go
=> services/serve: simplify err checks

go.mod, go.sum, starport/pkg/cmdrunner/step/step.go, starport/pkg/lineprefixer/lineprefixer.go, starport/pkg/lineprefixer/lineprefixer_test.go, starport/pkg/prefixgen/prefixgen.go, starport/pkg/prefixgen/prefixgen_test.go, starport/services/serve/log.go, starport/services/serve/serve.go
* added new pkg/lineprefixer.
* added new pkg/prefixgen.
* added options builder to pkg/cmdrunner/step.
* cosmetics.
resolves https://github.com/tendermint/starport/issues/105.
=> services/serve: add prefixes to verbose logs

go.mod, go.sum, starport/services/serve/serve.go
fixes https://github.com/tendermint/starport/issues/139
=> services/serve: allow git repos without tags

go.mod, go.sum, starport/services/serve/serve.go
=> services/serve: improve cancellation

go.mod, go.sum, starport/interface/cli/starport/cmd/add.go
fixes https://github.com/tendermint/starport/issues/149
=> add cmd: wasm can be added once

starport/templates/app/templates/app/app.go.plush
fix https://github.com/tendermint/starport/issues/161
=> Replace appName string

readme.md
| Flag               | Default  | Description                |
|----|----|----|
|`--address-prefix` |`cosmos` | Prefix, used for addresses |
| Flag        | Default | Description                          |
|----|----|----|
|`--verbose` |`false` | Enable verbose output from processes |
|`--path`    |         | Path to the project                  |
=> Add docs on flags to the readme

starport/templates/app/templates/frontend/src/components/TypeItem.vue
Added tiny client-side validation to prevent button from being smashed until the user is signed in.
fix https://github.com/tendermint/starport/issues/160
=> Check sign in before enabling CREATE button

go.mod, go.sum, starport/interface/cli/starport/cmd/app.go
resolves #35.
```
ilker@ig:~/.../starporttest/a3$ git log
commit a2c600b14dad29909420a0f0e8668e5af86a19ad (HEAD -> master)
Author: DevX Team @ Tendermint <devx@tendermint.com>
Date:   Thu Jan 1 00:00:00 1970 +0000
initialized w/ Starport
```
=> app cmd: git init by default

go.mod, go.sum, starport/services/serve/conf/config.go, starport/services/serve/serve.go
genesis.json will be overwrited with the genesis value set to config.yml
closes #106.
=> services/serve: add 'genesis' section to config.yml

go.mod, go.sum, starport/pkg/xos/env.go, starport/services/serve/serve.go
to validate system has needed dependencies installed and pre-conditions set.
fixes #148.
=> services/serve: pre-check system conditions

go.mod, go.sum, starport/interface/cli/starport/cmd/type.go
closes https://github.com/tendermint/starport/issues/125
=> type cmd: check if type is added before

changelog.md, go.mod, go.sum, starport/services/serve/conf/config.go, starport/services/serve/serve.go, starport/templates/app/templates/config.yml
=> config.yml: added validator config support

changelog.md, go.mod, go.sum, starport/services/serve/serve.go, starport/templates/app/templates/vue/src/store/index.js.plush, starport/templates/app/templates/vue/vue.config.js
=> services/serve: run appcli rest-server with CORS enabled

changelog.md, go.mod, go.sum, starport/interface/cli/starport/cmd/add.go, starport/interface/cli/starport/cmd/cmd.go, starport/interface/cli/starport/cmd/serve.go, starport/interface/cli/starport/cmd/type.go, starport/services/serve/serve.go, starport/templates/app/templates/cmd/{{binaryNamePrefix}}cli/main.go.plush, starport/templates/app/templates/cmd/{{binaryNamePrefix}}d/main.go.plush
https://github.com/tendermint/starport/issues/208
@fadeev can you please double check the all commands again (looks fine in my tests), I made a core change in this PR.
=> type command: supports dashes in app names

.gitpod.yml
=> Add init hook

.gitpod.yml
=> Add command to gitpod yml

go.mod, go.sum, starport/interface/cli/starport/cmd/app.go, starport/services/scaffolder/init.go, starport/services/scaffolder/scaffolder.go
from the cmd package.
~ some refactoring efforts before starting to integrate Stargate.
related to https://github.com/tendermint/starport/issues/215.
=> start moving scaffolding logic to services/scaffolder

starport/interface/cli/starport/cmd/app.go, starport/interface/cli/starport/cmd/type.go, starport/pkg/gomodulepath/gomodulepath.go, starport/services/scaffolder/init.go, starport/services/scaffolder/scaffolder.go, starport/services/scaffolder/type.go
a part of https://github.com/tendermint/starport/issues/215.
=> general refactor & move cmd type to scaffolder

starport/services/serve/serve.go
=> Fix appd directory name

readme.md
=> Add "Starport in Gitpod" link

go.mod, go.sum, starport/services/serve/serve.go
=> fix CORS origins for Tendermint RPC

go.mod, go.sum, starport/services/serve/plugin-launchpad.go, starport/services/serve/plugin-stargate.go
=> fix CORS for Stargate by allowing all origins

go.mod, go.sum, starport/services/serve/dev.go
=> dev ui: add cors

Makefile, changelog.md
I added make clean to the Makefile to make things easier.﻿
=> Add make clean

go.mod, go.sum, scripts/indocker, starport/templates/app/new.go, starport/templates/app/stargate/third_party/proto/google/protobuf/descriptor.proto, starport/templates/typed/typed.go
=> some Stargate fixes

go.mod, go.sum, scripts/indocker
for development purposes.
today, I had some problems on running the `app` cmd. it was hanging forever for a reason that I couldn't have chance to debug yet. so, I created a container environment to develop Starport inside that does not get effected by any issues from my host machine.
this is also helpful to keep my `~` clean because Stargate creates non-hidden config files and my home folder gets huge.
=> scripts: added indocker to run Starport in Docker

.gitpod.yml
=> Fix frontend

docs/01 Introduction/01_starport_introduction/introduction.md, docs/01 Introduction/02_documentation_specification/02_documentation_specification.md, docs/01 Introduction/03_development_mode/03_development_mode.md, docs/02 Using Starport/01_using_starport/01_using_starport.md, docs/02 Using Starport/02_genesis_file/02_genesis_file.md, docs/02 Using Starport/03_configuration/03_configuration.md, docs/03 Modules/01_what_are_modules/01_what_are_modules.md, docs/03 Modules/02_basic_modules/02_basic_modules.md, docs/03 Modules/03_advanced_modules/03_advanced_modules.md, docs/03 Modules/04_smart_modules/04_smart_modules.md, docs/03 Modules/05_your_own_module/05_your_own_module.md, docs/04 Use cases/01_smart_contracts/01_smart_contracts.md, docs/05 Extras/05_01_cosmos_ethermint/05_01_cosmos_ethermint.md, docs/README.md
Updated links in the documentation to new folder names.
Closes #259
=> Update /docs links

go.mod, go.sum, starport/templates/typed/launchpad/x/{{appName}}/client/cli/tx{{TypeName}}.go.plush
with the `type` cmd.
e.g. `starport type user username age:int`.
thanks for reporting @vince19972!
=> scaffolder: fix adding int type

go.mod, go.sum, starport/services/serve/plugin-stargate.go
=> serve: fix serving Stargate

starport/ui/src/views/Start.vue
=> dev ui: fix chain-id for Stargate

starport/services/scaffolder/module.go, starport/services/scaffolder/scaffolder.go, starport/services/scaffolder/type.go
=> disable module import for Stargate

go.mod, go.sum, starport/services/scaffolder/type.go, starport/services/serve/plugin-launchpad.go, starport/templates/typed/launchpad/x/{{appName}}/client/cli/tx{{TypeName}}.go.plush, starport/templates/typed/options.go, starport/templates/typed/stargate/x/{{appName}}/client/cli/tx{{TypeName}}.go.plush, starport/templates/typed/typed.go
=> scaffolding: fix type for Launchpad&Stargate

Makefile
=> fix goreleaser: rm statik from make

go.mod, go.sum, starport/services/scaffolder/init.go, starport/templates/app/new.go, starport/templates/typed/new_launchpad.go, starport/templates/typed/new_stargate.go, starport/templates/typed/typed.go
=> fix packr2

changelog.md
=> Updated changelog

changelog.md, starport/services/scaffolder/option.go
fixes https://github.com/tendermint/starport/issues/285.
=> scaffolder: ensure address prefix is lowercase

docs/04 Use cases/03_cw20/03_cw20.md
Module import from `starport add wasm` to `starport module import wasm` on the CW20 tutorial.
=> /docs wasm Update module import

changelog.md, go.mod, go.sum, starport/interface/cli/starport/cmd/build.go, starport/interface/cli/starport/cmd/cmd.go, starport/services/serve/log.go, starport/services/serve/plugin-launchpad.go, starport/services/serve/plugin-stargate.go, starport/services/serve/plugin.go, starport/services/serve/serve.go, starport/templates/app/launchpad/Makefile.plush
closes https://github.com/tendermint/starport/issues/260.
related to https://github.com/tendermint/starport/pull/292, https://github.com/tendermint/starport/issues/288, https://github.com/tendermint/starport/issues/290.
=> add build cmd to build apps without serving

starport/interface/cli/starport/cmd/module-import.go, starport/services/scaffolder/module.go, starport/templates/module/new_import.go, starport/templates/module/options.go
- Created `module` package in `templates` for all templates related to `module` command
- Renamed `add` into `import`
=> Refactor add into import in templates

.github/workflows/goreleaser.yml, .goreleaser.yml
=> add snapcraft section

docs/01 Introduction/03_development_mode/03_development_mode.md, docs/02 Using Starport/01_using_starport/01_using_starport.md, docs/05 Extras/05_01_cosmos_ethermint.md
Follow up integration of review https://github.com/helder-moreira/starport/pull/1
=> /docs corrections after review

starport/templates/app/launchpad/vue/package-lock.json, starport/templates/app/launchpad/vue/package.json
Updated to `v0.1.6` of `@tendermint/vue`.
=> Fix frontend scaffold

starport/templates/app/launchpad/vue/package-lock.json, starport/templates/app/launchpad/vue/package.json
This should fix the type form.
=> Update to v0.1.7

go.mod, go.sum, integration/integration_test.go, starport/pkg/availableport/availableport.go, starport/services/serve/plugin-launchpad.go
* services/serve:launchpad: fixed customizing Tendermint address while serving sdk's API.
=> integration: implement RandomizeServerPorts()

readme.md
I didn't update the changelog but it's really tiny change
=> add quick start back to readme

docs/04 Use cases/04_cw20/04_cw20.md
Updates the CW20 tutorial with latest changes that are made and addressed by the CosmWasm team.
=> Update wasm tutorial to latest changes

docs/01 Introduction/01_starport_introduction/introduction.md
=> fix a typo

starport/services/chain/conf/config.go
=> chain/conf: omitempty

docs/1 Introduction/1 Introduction.md, docs/2 Architecture/3 Standard Modules.md
=> Docs fixes

changelog.md, starport/services/chain/relayer.go, starport/services/chain/serve.go
=> activate relayer only if its binary installed

docs/1 Introduction/4 Configuration.md
Added information about the address denomination variable in the frontend and the possibility to have it done automatically through the CLI.
=> Update 4 Configuration.md

changelog.md, go.mod, go.sum, starport/templates/app/stargate/x/{{appName}}/module.go.plush, starport/templates/typed/new_stargate.go, starport/templates/typed/stargate/x/{{moduleName}}/client/rest/query{{TypeName}}.go.plush
Thanks to [cmwaters](https://discord.com/channels/669268347736686612/746658605213810779/769475645892722698) for reporting this!
=> scaffold/stargate: fix routing REST API endpoints of querier on Stargate

.gitignore, starport/services/chain/serve.go
If relayer version not correct user has no ability to detect it so I added this log line.
=> Add messages about relayer error (like incorrect version)

.github/workflows/semantic-pull-request.yml
=> ci: Added semantic PR GH action

docs/1 Introduction/1 Introduction.md
=> Docs review

starport/ui/src/views/Welcome.vue
- update broken links of articles, videos, footerBlocks for the Welcome page
=> welcome: update broken links

changelog.md, go.mod, go.sum, starport/templates/app/stargate/app/prefix.go.plush, starport/templates/app/stargate/cmd/{{binaryNamePrefix}}d/cmd/root.go.plush
=> fix(scaffolder): evaluate to --address-prefix option

go.mod, go.sum, starport/pkg/spn/spn.go, starport/services/networkbuilder/networkbuilder.go
Save peers in persistent_peers of `config.toml` before chain start for the first time
=> fix: add the chain's peers in persistent_peers of config.toml

go.sum, starport/interface/cli/starport/cmd/build.go, starport/interface/cli/starport/cmd/cmd.go, starport/interface/cli/starport/cmd/network_chain_create.go, starport/interface/cli/starport/cmd/network_chain_join.go, starport/interface/cli/starport/cmd/network_chain_start.go, starport/interface/cli/starport/cmd/serve.go, starport/interface/cli/starport/main.go
* removed extra error messages printed for the failing commands
* removed usage text on failing commands
=> refactor(cmd): better ctx handling+error printing

starport/services/chain/plugin-stargate.go
set `gprc-address` to app.toml.
=> fix: set grpc-address to app.toml

starport/templates/typed/new_stargate.go
=> fix: Stargate Msg impl codec registration

starport/interface/cli/starport/cmd/network.go
=> feat(network): use .starport.network to access to SPN

starport/interface/cli/starport/cmd/network_proposal_approve.go, starport/interface/cli/starport/cmd/network_proposal_reject.go, starport/pkg/spn/spn.go, starport/services/networkbuilder/blockchain.go, starport/services/networkbuilder/proposal.go
resolves #454.
and preps a base for #453.
=> feat(spn): implement batch proposal creations&reviewals.

starport/interface/cli/starport/cmd/network_proposal_approve.go
=> feature(network): add 'accept' alias for 'approve'

go.mod, go.sum, starport/services/networkbuilder/blockchain.go, starport/services/networkbuilder/networkbuilder.go
=> refactor(network): overwrite with initial Genesis on first start

starport/interface/cli/starport/cmd/network.go
=> refactor(network): change server addresses to temporary ones

starport/pkg/spn/spn.go, starport/services/networkbuilder/networkbuilder.go
by setting to Chain's submission time to SPN for all validators.
=> fix(network): fix Genesis time

starport/interface/cli/starport/cmd/network_chain_create.go, starport/pkg/xchisel/xchisel.go
=> refactor(tweaks): update docs+Chisel's max retry to inf

starport/services/networkbuilder/networkbuilder.go
=> feat(network): fail start if there is no approved validators

starport/services/networkbuilder/networkbuilder.go
=> fix(chisel): make sure random client ports are released

starport/interface/cli/starport/cmd/network.go
Reverts tendermint/starport#469
=> refactor(network): change server addresses to alpha.starport.network

go.mod, go.sum, starport/interface/cli/starport/cmd/network_chain_join.go, starport/pkg/cliquiz/question.go
* also make p2p address required.
resolves #476.
=> feat(network/join): do not fail if ipify fails

go.mod, go.sum, starport/interface/cli/starport/cmd/network.go
=> fix(network): fix rpc address

starport/interface/cli/starport/cmd/network_chain_create.go, starport/interface/cli/starport/cmd/network_chain_join.go, starport/pkg/spn/spn.go, starport/services/chain/app.go, starport/services/chain/chain.go, starport/services/chain/init.go, starport/services/chain/plugin-launchpad.go, starport/services/chain/plugin-stargate.go, starport/services/chain/plugin.go, starport/services/networkbuilder/blockchain.go, starport/services/networkbuilder/networkbuilder.go
* ensured that chain does not exist before starting to the process.
* made some general cleanup and fixes.
resolves #441.
resolves #485.
=> feat(network/chain/create): require a chain id

docs/1 Introduction/2 Install.md
close https://github.com/tendermint/starport/issues/137
=> docs: mention protoc in install.md

go.mod, go.sum, starport/pkg/spn/spn.go
Use the new `ListProposals` query from `spn` to list proposals
=> fix(spn): update list proposals from spn new query

starport/interface/cli/starport/cmd/network_chain_create.go, starport/interface/cli/starport/cmd/network_chain_show.go, starport/pkg/jsondoc/jsondoc.go, starport/pkg/spn/spn.go, starport/services/networkbuilder/chain.go, starport/services/networkbuilder/networkbuilder.go
=> fix(spn): migrate to updated ShowChain&LanchInformation apis

go.mod, go.sum, starport/interface/cli/starport/cmd/network_chain_create.go, starport/pkg/cliquiz/question.go
from flags or interactive prompt.
resolves #486.
=> feat(network/chain/create): collect chain id and source url

starport/interface/cli/starport/cmd/network_chain_create.go
=> feat(cmd): cosmetic update in logs

go.mod, go.sum, starport/pkg/xchisel/xchisel.go
=> refactor(chisel): disable noisy logs

go.mod, go.sum, starport/interface/cli/starport/cmd/network_chain_join.go, starport/interface/cli/starport/cmd/network_proposal_approve.go, starport/interface/cli/starport/cmd/network_proposal_reject.go
=> feat(cmd): improve spinners

go.mod, go.sum, starport/interface/cli/starport/cmd/network.go, starport/interface/cli/starport/cmd/network_chain_create.go, starport/interface/cli/starport/cmd/network_chain_join.go, starport/interface/cli/starport/cmd/network_proposal_approve.go, starport/interface/cli/starport/cmd/network_proposal_reject.go, starport/pkg/cliquiz/question.go, starport/services/networkbuilder/blockchain.go
=> refactor(network): improve join command's workflow

go.mod, go.sum, starport/pkg/lineprefixer/lineprefixer.go, starport/pkg/lineprefixer/lineprefixer_test.go, starport/pkg/tendermintrpc/rpc.go, starport/services/chain/log.go, starport/services/networkbuilder/networkbuilder.go
=> feat(network): add connected peer count to 'start' logs

starport/interface/cli/starport/cmd/network_chain_join.go, starport/pkg/xchisel/xchisel.go, starport/services/chain/init.go, starport/services/networkbuilder/blockchain.go, starport/services/networkbuilder/networkbuilder.go
=> fix(network): minor fixes

starport/interface/cli/starport/cmd/network.go, starport/interface/cli/starport/cmd/network_chain_join.go, starport/services/chain/init.go, starport/services/chain/serve.go, starport/services/networkbuilder/blockchain.go
=> fix(network): target chain's account creation

starport/pkg/availableport/availableport.go
we were letting OS to find an available port previosuly but that has a side
effect of sometimes ports not being released back in time by the OS.
=> fix(pkg/availableport): change finding available port logic

changelog.md, starport/templates/typed/stargate/proto/{{moduleName}}/{{typeName}}.proto.plush, starport/templates/typed/stargate/x/{{moduleName}}/client/cli/tx{{TypeName}}.go.plush, starport/templates/typed/stargate/x/{{moduleName}}/client/rest/tx{{TypeName}}.go.plush, starport/templates/typed/stargate/x/{{moduleName}}/handler_{{typeName}}.go.plush, starport/templates/typed/stargate/x/{{moduleName}}/keeper/{{typeName}}.go.plush, starport/templates/typed/stargate/x/{{moduleName}}/types/messages_{{typeName}}.go.plush
=> refactor(template): use string instead of AccAddress for creator in types

.github/workflows/lint.yml
=> fix(ci): enable linter for develop&PRs

go.mod, go.sum, starport/pkg/fswatcher/fswatcher.go, starport/services/chain/build.go, starport/services/chain/chain.go, starport/services/chain/serve.go
=> fix(proto): enable code generation on serve

starport/errors/errors.go, starport/pkg/cosmosprotoc/cosmosprotoc.go, starport/services/chain/build.go, starport/services/chain/serve.go, starport/services/scaffolder/init.go
=> fix(serve): install protoc dependencies on serve

starport/interface/cli/starport/analytics.go, starport/interface/cli/starport/cmd/build.go, starport/interface/cli/starport/cmd/module-create.go, starport/interface/cli/starport/cmd/module-import.go, starport/interface/cli/starport/cmd/module.go, starport/interface/cli/starport/cmd/network.go, starport/interface/cli/starport/cmd/network_account.go, starport/interface/cli/starport/cmd/network_account_create.go, starport/interface/cli/starport/cmd/network_account_export.go, starport/interface/cli/starport/cmd/network_account_import.go, starport/interface/cli/starport/cmd/network_account_use.go, starport/interface/cli/starport/cmd/network_chain.go, starport/interface/cli/starport/cmd/network_chain_create.go, starport/interface/cli/starport/cmd/network_chain_join.go, starport/interface/cli/starport/cmd/network_chain_list.go, starport/interface/cli/starport/cmd/network_chain_show.go, starport/interface/cli/starport/cmd/network_chain_start.go, starport/interface/cli/starport/cmd/network_proposal.go, starport/interface/cli/starport/cmd/network_proposal_approve.go, starport/interface/cli/starport/cmd/network_proposal_list.go, starport/interface/cli/starport/cmd/network_proposal_reject.go, starport/interface/cli/starport/cmd/network_proposal_show.go, starport/interface/cli/starport/cmd/relayer.go, starport/interface/cli/starport/cmd/serve.go, starport/interface/cli/starport/cmd/type.go, starport/interface/cli/starport/cmd/version.go
=> fix(linter): cmd pkg related linter errors

starport/interface/cli/starport/cmd/network_chain_create.go, starport/pkg/cliquiz/question.go
=> feat(network): added support to define revision on create

go.mod, go.sum, starport/pkg/spn/chain.go
Use the new type `LaunchInformation` of `spn` introduced in https://github.com/tendermint/spn/pull/92 (need this PR to be merged first)
=> fix(genesis): launch information format

.github/workflows/npm-publish.yml
=> fix(ci): migrate workflows to latest GH rules

starport/interface/cli/starport/cmd/network_chain_list.go, starport/interface/cli/starport/cmd/network_proposal_list.go, starport/pkg/ctxreader/ctxreader.go, starport/pkg/ctxreader/ctxreader_test.go, starport/pkg/spn/chain.go, starport/pkg/spn/proposal.go, starport/services/networkbuilder/chain.go, starport/services/networkbuilder/proposal.go
=> refactor(network): refactor chain+proposal listing & enable chan pagination

go.mod, go.sum, starport/interface/cli/starport/cmd/network_chain_create.go
=> refactor(network/create): require arguments instead of flags

go.mod, go.sum, starport/interface/cli/starport/cmd/network_chain_list.go, starport/pkg/spn/chain.go, starport/services/networkbuilder/chain.go
`starport network chain list --search [prefix]` will list the chain the specified prefix
=> feat(network): add the search option for chain list

go.mod, go.sum, starport/interface/cli/starport/cmd/network_proposal_approve.go, starport/pkg/spn/chain.go
`starport network proposal approve` will first check the proposals don't generate an invalid genesis before approving the proposals
`--no-verification` allows disabling to verification, spawn a prompt for confirmation
=> feat(network): verify proposals when approving them

go.mod, go.sum, starport/interface/cli/starport/cmd/network_chain_create.go, starport/interface/cli/starport/cmd/network_chain_join.go, starport/pkg/ctxticker/ctxticker.go, starport/pkg/ctxticker/ctxticker_test.go, starport/pkg/gomodulepath/gomodulepath.go, starport/services/chain/build.go, starport/services/chain/chain.go, starport/services/chain/conf/config.go, starport/services/chain/init.go, starport/services/chain/serve.go, starport/services/networkbuilder/networkbuilder.go
* support blockchain module names that contains versions.
e.g. `module github.com/cosmos/gaia/v3`
=> feat: make config.yml optional

starport/interface/cli/starport/cmd/network_chain_create.go, starport/services/networkbuilder/networkbuilder.go
sample usage:
```
starport network chain create mychain https://github.com/cosmos/gaia --tag stargate-6
```
depends on https://github.com/tendermint/starport/pull/578 to be merged first.
=> feat(network): support creating chains from tags (releases)

go.mod, go.sum, integration/env_test.go, starport/pkg/cosmosver/cosmosver.go, starport/services/chain/chain.go, starport/services/networkbuilder/blockchain.go
=> feat(network): disable create command for Launchpad apps

.github/workflows/goreleaser.yml
Added `apt-get update` command
=> fix: Snapcraft set up

docs/1 Introduction/2 Install.md
[Rendered](https://github.com/tendermint/starport/blob/fadeev-patch-1/docs/1%20Introduction/2%20Install.md)
=> docs: install.md

go.mod, go.sum, starport/pkg/chaincmd/chaincmd.go, starport/pkg/chaincmd/runner/account.go, starport/pkg/chaincmd/runner/chain.go, starport/pkg/chaincmd/runner/runner.go, starport/services/chain/chain.go, starport/services/chain/init.go, starport/services/chain/log.go, starport/services/chain/plugin-launchpad.go, starport/services/chain/plugin-stargate.go, starport/services/chain/plugin.go, starport/services/chain/serve.go, starport/services/networkbuilder/blockchain.go, starport/services/networkbuilder/networkbuilder.go, starport/services/networkbuilder/simulation.go
`chaincmdrunner` provides a high level API to execute commands of an SDK app through programaticall access.
* refactor `services/` to use this new pkg.
=> refactor: add&use chaincmdrunner package

starport/interface/cli/starport/cmd/build.go, starport/interface/cli/starport/cmd/relayer.go, starport/interface/cli/starport/cmd/serve.go, starport/services/chain/chain.go, starport/services/networkbuilder/blockchain.go, starport/services/networkbuilder/networkbuilder.go, starport/services/networkbuilder/simulation.go
=> refactor(services/chain): make New depend on the source code

starport/interface/cli/starport/cmd/build.go, starport/interface/cli/starport/cmd/cmd.go, starport/interface/cli/starport/cmd/relayer.go, starport/interface/cli/starport/cmd/serve.go, starport/pkg/gomodulepath/gomodulepath.go, starport/services/networkbuilder/blockchain.go, starport/services/networkbuilder/networkbuilder.go, starport/services/networkbuilder/simulation.go, starport/services/scaffolder/module.go, starport/services/scaffolder/type.go
w/ gomodulepath.ParseAt().
solves a part of #609.
=> refactor(cmd): replace cmd.getModule()

docs/1 Introduction/2 Install.md
Install Starport with:
```
curl https://get.starport.network/starport! | bash
```
Mad props to @helder-moreira!
close https://github.com/tendermint/starport/issues/645
=> Update install info

starport/templates/app/launchpad/Dockerfile.plush, starport/templates/app/stargate/Dockerfile.plush
Generated dockerfiles were missinng d after AppName﻿
=> fix: dockerfiles

starport/templates/app/new.go, starport/templates/app/stargate/proto/{{appName}}/genesis.proto.plush, starport/templates/app/stargate/proto/{{appName}}/query.proto.plush, starport/templates/module/create/new_create_stargate.go, starport/templates/module/create/stargate/proto/{{moduleName}}/genesis.proto.plush, starport/templates/module/create/stargate/proto/{{moduleName}}/query.proto.plush, starport/templates/typed/stargate/proto/{{moduleName}}/{{typeName}}.proto.plush, starport/templates/typed/typed.go
=> fix(template): rm dash in proto pkg names

starport/templates/app/stargate/go.mod.plush, starport/templates/app/stargate/go.sum
=> feat(template): upgrade to Cosmos SDK 0.41.0

integration/tx_test.go, starport/templates/app/launchpad/config.yml, starport/templates/app/stargate/config.yml
This adds Alice and Bob to config.yml and provides a commented-out guide to the other features that can be used in config.yml
=> fix: rename users in config.yml, remove version property

starport/interface/cli/starport/cmd/relayer.go
related to https://github.com/tendermint/starport/pull/709#issuecomment-775792474.
=> docs(cmd/relayer): document low-level relayer command

go.mod, go.sum, starport/pkg/cosmosanalysis/docs.go, starport/pkg/cosmosanalysis/msgs/msgs.go, starport/pkg/cosmosanalysis/msgs/msgs_test.go, starport/pkg/cosmosprotoc/cosmosprotoc.go, starport/pkg/protoanalysis/protoanalysis.go
* `pkg/cosmosanalysis/msg.Discover()` discovers types that implements sdk.Msg.
* added `pkg/protoanalysis` for proto file analysis.
https://github.com/tendermint/starport/blob/4e857e9198d81923e27be6365528afff714ebcd5/starport/pkg/cosmosanalysis/msgs/msgs_test.go#L7-L11
=> feat: sdk msg discovery from app source

starport/services/chain/init.go
=> docs(serve): detailed account logs

starport/templates/app/stargate/config.yml
Just keepin' config nice and lean 🙃
=> chore: faucet.coins compact notation

go.mod, go.sum, starport/interface/cli/starport/cmd/app.go, starport/interface/cli/starport/cmd/build.go, starport/interface/cli/starport/cmd/module-create.go, starport/interface/cli/starport/cmd/module-import.go, starport/interface/cli/starport/cmd/packet.go, starport/interface/cli/starport/cmd/type.go, starport/services/chain/build.go
because spinners are awesome :)
~please feel free to suggest changes for spinners' text if needed.
=> feat(cmd): add more spinners

starport/services/chain/build.go, starport/services/scaffolder/init.go
Add `chain` prefix to generated vuex module path names
=> fix: add chain to path

starport/pkg/chaincmd/chaincmd.go, starport/pkg/chaincmd/runner/account.go, starport/pkg/chaincmd/runner/chain.go, starport/pkg/chaincmd/runner/runner.go, starport/services/chain/grpcweb_proxy.go, starport/services/chain/plugin-launchpad.go, starport/templates/app/launchpad/go.mod.plush, starport/templates/app/launchpad/go.sum
=> fix(chain): keyring backend & upgrade LP version

starport/templates/app/stargate/vue/README.md.plush
Is this PR a suitable way to submit a text suggestion for the `/github/starport/starport/templates/app/stargate/readme.md.plush` template?  Please teach me.
I noticed a typo and added a little grammar love while I was in there.
=> fix: README.md.plush suggested update to fix a typo and add a little grammar love

docs/1 Introduction/2 Install Starport.md
close https://github.com/tendermint/starport/issues/847
=> docs: add $GOPATH/bin in install intructions

starport/pkg/cosmosanalysis/module/module.go, starport/pkg/gomodule/gomodule.go, starport/services/chain/build.go
=> fix(codegen): make it work when there is no proto/ dir

docs/README.md
add link to published docs so that people who land on the repo and easily visit the docs site
=> docs: README.md

.gitignore, scripts/gen-nodetime
also made a small refactoring on the nodetime binary generation script.
=> chore(nodetime): rebuild binary to include ts-relayer

starport/cmd/app.go, starport/cmd/build.go, starport/cmd/cmd.go, starport/cmd/message.go, starport/cmd/module-create.go, starport/cmd/module-import.go, starport/cmd/module.go, starport/cmd/network.go, starport/cmd/packet.go, starport/cmd/serve.go, starport/cmd/type.go, starport/cmd/version.go, starport/services/chain/build.go
Minor improvements to the descriptions of commands.
=> docs: Modified command descriptions

scripts/data/gen-nodetime/src/relayer/lib/chain.ts, scripts/data/gen-nodetime/src/relayer/lib/link.ts, scripts/data/gen-nodetime/src/relayer/lib/start.ts, starport/pkg/nodetime/ts-relayer/tsrelayer.go
closes https://github.com/tendermint/starport/pull/1054#issuecomment-830082716.
=> chore(ts-relayer shim): support long running executions

starport/templates/typed/genesis.go
Thanks @dshulyak for the report https://github.com/tendermint/starport/issues/1078#issuecomment-832437547
=> fix: add count field for exported genesis for scaffolded type

scripts/data/gen-nodetime/src/relayer/lib/chain.ts, starport/pkg/xrelayer/chain.go
=> fix(relayer/ts-lib): add options to ensureChainSetup

scripts/data/gen-nodetime/src/relayer/index.ts, scripts/data/gen-nodetime/src/relayer/lib/relayer.ts, starport/cmd/relayer_configure.go, starport/pkg/xrelayer/relayer.go
What do you guys think about this addition?
=> feat(ts-relayer): add a security warning

starport/templates/testutil/stargate/testutil/network/network.go.plush, starport/templates/typed/indexed/stargate/component/x/{{moduleName}}/client/cli/query{{TypeName}_test.go.plush, starport/templates/typed/indexed/stargate/component/x/{{moduleName}}/client/cli/query{{TypeName}}.go.plush, starport/templates/typed/stargate/component/x/{{moduleName}}/client/cli/query{{TypeName}}.go.plush, starport/templates/typed/stargate/component/x/{{moduleName}}/client/cli/query{{TypeName}}_test.go.plush
depends on: https://github.com/tendermint/starport/pull/1132
closes: https://github.com/tendermint/starport/issues/716
changes:
- test for show/list indexed/non-indexed types
- extended list commands with pagination flags
=> feat(templates): integration tests for cli querier

Makefile
Remove unused makefile UI command
=> chore(Makefile): rm unneeded ui command

docs/.vuepress/config.js, docs/package-lock.json
They made a mistake and called it `startport` 🙄
=> docs: Docs search

changelog.md, starport/cmd/cmd.go, starport/cmd/relayer.go, starport/cmd/tools.go
I also plan to expose `protoc` binary under `starport tools` in the future.
a part of #1244.
=> feat(cmd): add 'tools' command

integration/cmd_app_test.go, integration/env_test.go, starport/cmd/cmd.go, starport/cmd/scaffold.go, starport/cmd/scaffold_chain.go
move 'app' to 'scaffold chain'.
a part of #1244.
=> refactor(cmd): add 'scaffold' command and

starport/internal/tools/gen-cli-docs/main.go
once this is merged, docs.starport.network should be updated automatically.
=> chore(docs/cli): add notice

.github/CODEOWNERS
Closes #1290
Add me as a Codeowner
=> feat: add @Pantani to Codeowners

starport/templates/app/stargate/go.mod.plush, starport/templates/app/stargate/go.sum
This just brings the sdk to 0.42.6 and tendermint to 0.34.11
:)
=> feat(templates): upgrade sdk version

starport/pkg/nodetime/data/data.go
=> fix(docs): typo

docs/intro/index.md, readme.md, starport/chainconf/config.go
Signed-off-by: Sonia Singla <soniasingla.1812@gmail.com>
Added link to contribution file in readme and minor nit improvements in getting started documentation 🤗
=> docs: improve docs and add link to contribution guideline

readme.md
v0.17 hasn't been released yet, so it's early to change the readme.
=> docs: Revert changes to the readme

.gitpod/readme.md
v0.17 hasn't been released yet, so it's early to change the readme.
=> docs: Revert changes to the readme on Gitpod

starport/cmd/chain.go, starport/cmd/generate.go, starport/cmd/network.go, starport/cmd/scaffold.go, starport/cmd/scaffold_chain.go, starport/cmd/scaffold_list.go, starport/cmd/scaffold_map.go, starport/cmd/scaffold_message.go, starport/cmd/scaffold_package.go, starport/cmd/scaffold_query.go, starport/cmd/scaffold_single.go, starport/cmd/scaffold_vue.go
Signed-off-by: Sonia Singla <soniasingla.1812@gmail.com>
Fixes #1352
replace command descriptions
=> docs(cmd): improve command descriptions

starport/templates/typed/stargate/component/x/{{moduleName}}/keeper/grpc_query_{{typeName}}_test.go.plush
=> fix(template/map): add an additional check in query tests

starport/templates/typed/genesis.go
closes #1398
adding count verification in generated genesis `Validate()` method for list scaffolding 
- Create a list
```shell
$ starport s list coordinator --no-message
```
- Check the implementation in `<moduleName>/type/genesis.go`
=> feat(genesis): count verification in generated genesis validation

contributing.md
close https://github.com/tendermint/starport/issues/1423
=> docs: CLI refeference in `contributing.md`

scripts/build-protoc-gen-dart
a small compiler script for the project
=> feat: add compile script

starport/templates/typed/stargate/component/x/{{moduleName}}/keeper/{{typeName}}.go.plush
https://github.com/tendermint/starport/issues/1397
=> fix(template/list): index for count of list prefixed twice

integration/env_test.go, starport/cmd/chain_serve.go, starport/services/chain/chain.go
when client.toml > keyring-backend used.
=> fix(services/chain): detecting keyring

starport/pkg/chaincmd/runner/account.go
related to https://github.com/tendermint/starport/issues/1439.
=> fix(services/chain): support 0.43.x based chains

go.mod, go.sum
We've released new version of flutter template and wanted to include it in starport
=> feat: bump flutter dependency to v1.0.0

readme.md
Use the updated "Starport is the all-in-one platform to build, launch and maintain any crypto application on a sovereign and secured blockchain."
=> docs: change readme intro

docs/kb/genesis.md
thanks for PR #1525 @soniasingla (but the review period was open and closed during my off hours... oops, so here's my review suggestions in a new PR)
I remember writing this topic during my first months here and this PR fixes some style conventions that I missed on that first effort.
=> fix:(genesis.md) minor grammar adjustments

docs/kb/band.md
Fix the order No. to 12 from 99
=> docs: fix order No.

docs/guide/blog.md, docs/guide/hello.md, docs/guide/install.md
- Install instructions
- Blog tutorial intro
=> docs: Guide improvements

docs/.vuepress/config.js, starport/templates/app/stargate/readme.md.plush
=> fix: discord link

docs/contributing/technical-setup.md
=> fix: remove obsolete /TODO from docs/technical-setup.md

starport/pkg/protoanalysis/builder.go, starport/pkg/protoanalysis/protoanalysis_test.go, starport/pkg/protoanalysis/testdata/nested_messages/nested_messages.proto
=> fix(pkg/protoanalysis): correctly name nested messages

docs/guide/blog.md, docs/guide/hello.md
Update developers Guide to Starport v0.18
=> docs: Update to v0.18

docs/.vuepress/config.js
Update links at the bottom of the docs website.
=> docs: Update links

starport/templates/app/stargate/readme.md.plush
* updated URLs
* removed references to SPN (for now)
=> docs: update readme in the template

go.mod, go.sum, starport/cmd/network_chain_publish.go, starport/pkg/clispinner/icon.go, starport/pkg/cosmosclient/cosmosclient.go, starport/services/chain/chain.go, starport/services/network/blockchain.go
* cmd/network/publish: support --campaign flag.
* cmd/network/publish: output launch and campaign ids after publishing a chain.
* pkg/cosmosclient: added Response.Decode() func to decode TX responses.
=> feat(network/publish): add remaining features

readme.md
from Slack convo https://allinbits.slack.com/archives/C014GFM3FRQ/p1636551660198600?thread_ts=1636531909.189900&cid=C014GFM3FRQ
=> docs: (readme.md) create an issue on GitHub before new feature

docs/guide/ibc.md, docs/guide/interchange/02-init.md
We still have a legacy prop in some tutorials.
=> docs: remove dev-ui property from config.yml

readme.md
thanks @soniasingla for noticing!
=> docs: fix blog link to starport.com/blog

docs/guide/nameservice/03-types.md
close https://github.com/tendermint/starport/issues/1841
=> docs: fix a typo (removed a bullet)

.github/CODEOWNERS
=> chore: add @ivanovpetr to CODEOWNERS

docs/contributing/index.md
a few little updates to embrace the concept that documentation is good for productivity, community, & culture.
I got excited reading https://octoverse.github.com/creating-documentation/ 
In #opensource projects & enterprises, #developers see 50% productivity boost w/ easy-to-source docs. GitHub Issues are #documentation too. 
what other changes can we make? I'm open to understanding more.
=> docs: update docs/contributing/index.md to improve contributor experience

go.mod, go.sum
New [release](https://github.com/tendermint/vue/releases/tag/v0.1.55) v0.1.55
=> feat(frontend): version bump 

docs/contributing/technical-setup.md, docs/contributing/templates/concept_template.md, docs/contributing/templates/readme.md, docs/contributing/templates/tutorial-template.md
fixed a few things that were broken, including our repo URL!
=> docs: minor fix to contrib docs and template

contributing.md, docs/.vuepress/config.js, readme.md
custom invite URL - http://discord.gg/starport
=> fix: update Discord invite URL 

starport/templates/app/stargate/.gitignore
=> fix: extend initial .gitignore file content

docs/guide/install.md
=> feat(docs): Fix the link to OS in docs

docs/kb/frontend.md, docs/kb/serve.md
=> docs: update the frontend section

go.mod, go.sum, starport/cmd/generate_dart.go, starport/pkg/cosmosclient/cosmosclient.go, starport/pkg/sdkerror/error.go, starport/services/network/join.go, starport/services/network/launch.go, starport/services/network/publish.go, starport/services/network/queries.go, starport/services/network/request.go
close #1770
Parse the GRPC chain errors and unwrap the SDK errors to have better error messages.
```shell
starport n --nightly request show 1 99
```
=> refactor(network): unwrap and parse the chain errors

starport/pkg/cosmoserror/error.go, starport/services/network/join.go, starport/services/network/launch.go, starport/services/network/publish.go, starport/services/network/queries.go, starport/services/network/request.go
=> refactor(network): fix the package name according to guidelines

docs/README.md
=> fix(docs): minor grammar fix

readme.md
=> fix(README): minor grammar fix

.github/workflows/release-binary.yml, .github/workflows/release-docker.yml, .github/workflows/test-lint.yml, .github/workflows/test-semantic.yml
=> feat(ci): release the starport binary only on releases

.github/workflows/release-nightly.yml, .goreleaser.nightly.yml
`curl https://get.starport.network/starport@nightly! | bash`
=> feat(ci): add workflow to deploy `nightly` releases

starport/pkg/cosmosgen/templates/js/index.ts.tpl, starport/pkg/cosmosgen/templates/vuex/root/index.ts.tpl
Reverts tendermint/starport#2037
=> fix(revert): #2037

starport/cmd/network_chain_show.go, starport/cmd/network_request_list.go, starport/services/network/networkchain/prepare.go, starport/services/network/peer.go, starport/services/network/peer_test.go
a part of https://github.com/tendermint/starport/issues/2091.
=> fix(cmd/network): fix the spn network peer object printing

starport/pkg/cosmosclient/cosmosclient.go
Reference: [cosmos-sdk:client/tx/tx.go#L131](https://github.com/cosmos/cosmos-sdk/blob/2646b474c7beb0c93d4fafd395ef345f41afc251/client/tx/tx.go#L131)
=> fix: Missing fee granter 

contributing.md, docs/.vuepress/config.js, readme.md
closes part of https://github.com/tendermint/starport/issues/2116
=> fix: use new Discord invite link discord.gg/ignt

readme.md
=> fix: update readme to change Tendermint to Ignite

starport/pkg/cosmosclient/cosmosclient.go
close #2103
If the `BroadcastTx` methods return an `ErrInsufficientFunds` we should ask more tokens to the faucet
=> feat(network): ask token from faucet if have no enough funds

docs/guide/scavenge/07-keeper.md
=> docs(scavenge): remove scavenge creator

starport/services/network/queries.go
close #2200
fix the table sort for the network chain list command.
```shell
starport network --nightly chain list
```
=> fix(network): fix order when listing chains

go.mod, go.sum, starport/cmd/network_campaign_update.go, starport/cmd/network_chain_publish.go, starport/services/network/campaign.go, starport/services/network/publish.go
close #2226
https://github.com/tendermint/spn/pull/654
=> feat(network): remove total shares flags and dynamic shares

docs/guide/hello.md
Thanks @ChrisValle for identifying first use blockers, small edits for making this doc better
=> docs(hello.md): improve hello language to reduce first use friction

docs/guide/blog/comment-blog.md
Added 'import' to line 392 to reflect code @barriebyron @soniasingla
=> (Docs) Added 'import' to code snippet

docs/guide/blog/comment-blog.md
@barriebyron @soniasingla want you use the word 'replace' rather than 'add' to avoid confusion. How does the wording look to you?
=> docs(blog): Added clarity to line 192-193

Dockerfile, docs/guide/nameservice/02-messages.md, ignite/chainconfig/config.go, ignite/internal/tools/gen-cli-docs/main.go
rebranding URLs and product names in the code
=> fix(docs): update comments

docs/.vuepress/config.js
=> docs: linkedin update

docs/guide/blog/index.md
Update Ignite CLI version to 0.20.0
Update `cosmonaut` to `username`
=> docs: blog-minor-update

docs/guide/blog/connect-blockchain.md
As I run this tutorial I am making minor changes to grammar, to better reflect code, style etc.
=> docs(tutorials/blog): fix grammar and styling

docs/guide/blog/comment-blog.md
Update `cosmonaut` to `username`
=> docs:blog-comment-minor-update

readme.md
Fixed the Discord URL in the readme file
updated the Cosmos SDK compatibility table, please review carefully for versions and IBC
=> fix(readme.md): Discord URL invite in readme

ignite/templates/app/stargate/readme.md.plush
Updated the default readme.md.
=> docs: update readme with Ignite

ignite/cmd/network_chain_publish.go, ignite/pkg/cosmosutil/coins.go, ignite/pkg/cosmosutil/coins_test.go, ignite/services/network/publish.go, ignite/services/network/publish_test.go
Current format:
`--shares 20foo,50staking`
Should we require % in the the coins like below?
`--shares 20%foo,50%staking`
=> feat(network/chain): add --shares to the publish cmd

.github/CODEOWNERS
=> chore: add @jeronimoalbi to CODEOWNERS

ignite/templates/module/module.go, ignite/templates/module/module_test.go
=> fix: format proto package names to be valid

ignite/cmd/network_chain_prepare.go, ignite/cmd/network_chain_show_genesis.go, ignite/services/network/queries.go
Fetch the chain ID from the network status API instead use flags for a different chain id.
=> feat(network): fetch spn chain id from status

ignite/cmd/network_chain_join.go, ignite/cmd/network_chain_publish.go, ignite/services/network/join.go, ignite/services/network/publish.go
close #2509
```ssh
ignite n --local chain publish https://github.com/Pantani/mars --reward.coins 333uspn --reward.height 300 --from bob --amount 9999uspn
```
=> feat(network/publish): add `--amount` flag to chain publish 

docs/guide/hello.md
* Replaced the project name with `hello` (instead of `github.com/username/hello`)
* Replaced `Posts` with `Hello`. Initially, I thought the blog tutorial will be a continuation of the hello tutorial, but we've since realized that having them separate is the way to go, so it doesn't make sense to have a `Posts` query in the hello tutorial.
* Added a note about committing changes to a VCS.
=> docs: update the hello tutorial

readme.md
update URLs in project readme and use short-form chain name
=> docs(readme.md): update link URLs

docs/guide/loan.md
change longform github chain name to short form chain name
=> docs(loan.md): add headings for structure and simple edits

docs/docusaurus.config.js, docs/package-lock.json, docs/package.json, docs/src/css/base.css, docs/src/css/custom.css
In the documentation, swap the local search system by Algolia search engine.
=> feat: Replace local searchbar by Algolia

docs/docs/guide/03-blog/00-build-blog.md
Documented command to start the chain before using the CLI to create a post.
=> docs: added command to start chain

Makefile
Some improvements to the `Makefile`
- Adds `make mocks` target to `Makefile`
- `.PHONY` targets to prevent aliasing
=> chore(`Makefile`): add `make mocks` target

ignite/services/chain/chain.go
Set the default chain ID as `<name>-1` whatever if a chain ID is defined or not in `config.yml`
=> fix(network): fix default chain ID for publish

docs/docs/guide/06-loan.md
close https://github.com/ignite/cli/issues/2151
=> docs(loan): avoid using the reserved error code 1

docs/docs/guide/03-blog/00-build-blog.md
close https://github.com/ignite/cli/issues/2418
=> docs: make the blog tutorial a bit clearer

ignite/cmd/chain_init.go
=> docs: inline docs for `chain init`

ignite/cmd/scaffold_map.go
=> docs: inline docs for `scaffold map`

ignite/cmd/scaffold_message.go
=> docs: inline docs for `scaffold messsage`

scripts/data/gen-nodetime/package-lock.json
Update package-lock so `scripts/gen-nodetime` can run.
Works again locally for me.  We will need to run CI action to verify.
=> fix: update package-lock

changelog.md, scripts/data/gen-nodetime/package-lock.json, scripts/data/gen-nodetime/package.json
=> fix: Downgrade pkg to 5.6.0. Upgrade ts-proto to highest possible

docs/docs/guide/02-hello.md, docs/docs/guide/03-blog/00-build-blog.md
Proposed updated to documentation files to reference the latest cli version v0.25.1 in the hello and blog tutorials.
=> docs: updates to reference latest cli version v0.25.1

docs/docs/guide/02-hello.md, docs/docs/guide/04-nameservice/00-tutorial.md, docs/docs/guide/04-nameservice/04-keeper.md, docs/docs/guide/07-ibc.md, docs/docs/kb/02-serve.md, docs/docs/kb/11-simapp.md, docs/docs/kb/12-params.md
=> docs: Updates Cosmos docs links

ignite/pkg/events/events_test.go
=> chore: change `pkg/events` test to use event factory function

changelog.md, go.mod, go.sum, ignite/templates/app/stargate/go.mod.plush
=> chore: `ibc-go` bump

.github/workflows/release-docker.yml
fixes typo in workflow from https://github.com/ignite/cli/pull/3061
=> fix: fix broken docker release workflow

ignite/pkg/chaincmd/runner/runner.go, ignite/pkg/cosmoscmd/root.go, ignite/pkg/cosmosutil/gentx.go, ignite/pkg/tendermintrpc/rpc.go, ignite/services/network/networktypes/request.go
=> chore: remaining `stargate` removal

ignite/cmd/network_chain_publish.go, ignite/services/network/publish.go
Remove the option `NoCheck` that was no longer used
=> refactor(`network`): remove unused `NoCheck` for publish

ignite/cmd/network_request_reject.go
=> docs: network request reject

.gitpod/readme.md
* Replace `github.com/example/repo` with `example`
* Fix Discord URL
=> docs: update Gitpod's readme

ignite/cmd/network_request_list.go, ignite/cmd/network_request_remove_account.go, ignite/cmd/network_request_remove_validator.go, ignite/cmd/network_request_show.go, ignite/cmd/network_request_verify.go
One paragraph for `verify`, the rest I don't think need a long description.
=> docs: network request verify

ignite/cmd/network_chain_publish.go
* `--branch`, `--tag`, `--hash`
* `--chain-id`
* `--account-balance`
=> docs: network chain publish, added chain id and account balance

docs/docusaurus.config.js, docs/yarn.lock
We also have this in the footer, probably better to update the emails.
```
{
label: "Media Inquiries",
href: "mailto:media@tendermint.com",
},
{
label: "Business Inquiries",
href: "mailto:business@tendermint.com",
},
```
=> docs: remove Emeris and Ventures from the footer

readme.md
Specify Cosmos SDK, IBC & Tendermint versions
=> docs: update `readme.md`

go.mod, go.sum, ignite/pkg/cliui/cliui.go, ignite/pkg/cliui/colors/colors.go, ignite/pkg/cliui/icons/icon.go, ignite/pkg/cliui/log/output.go, ignite/pkg/cliui/prefixgen/prefixgen.go, ignite/services/chain/chain.go
=> refactor(`cliui`): terminal colors

ignite/cmd/network.go
Update with the new proper urls
Should be the last PR before considering merge `spn` update
=> refactor(`network`): update alpha testnet endpoints

changelog.md, ignite/pkg/relayer/relayer.go
=> fix: change relayer to work with multiple paths

.github/codecov.yml
Create a codecov file with the coverage rules
=> feat: add codecov file with coverage configs

.github/workflows/md-link-checker-config.json, .github/workflows/md-link-checker.yml, .gitpod/readme.md, contributing.md, docs/docs/clients/01-typescript.md, docs/docs/contributing/02-technical-setup.md, docs/docs/contributing/templates/02-tutorial-template.md, docs/docs/guide/02-getting-started.md, docs/docs/guide/05-nameservice/00-tutorial.md, docs/docs/guide/05-nameservice/01-init.md, docs/docs/guide/05-nameservice/02-messages.md, docs/docs/guide/05-nameservice/03-types.md, docs/docs/guide/08-loan.md, docs/docs/kb/07-frontend.md, docs/docs/migration/v0.20.0.md, docs/readme.md, docs/versioned_docs/version-v0.25.2/clients/01-typescript.md, docs/versioned_docs/version-v0.25.2/contributing/02-technical-setup.md, docs/versioned_docs/version-v0.25.2/contributing/templates/02-tutorial-template.md, docs/versioned_docs/version-v0.25.2/guide/04-nameservice/00-tutorial.md, docs/versioned_docs/version-v0.25.2/guide/04-nameservice/01-init.md, docs/versioned_docs/version-v0.25.2/guide/04-nameservice/02-messages.md, docs/versioned_docs/version-v0.25.2/guide/04-nameservice/03-types.md, docs/versioned_docs/version-v0.25.2/guide/06-loan.md, docs/versioned_docs/version-v0.25.2/index.md, docs/versioned_docs/version-v0.25.2/kb/00-kb.md, docs/versioned_docs/version-v0.25.2/kb/07-frontend.md, ignite/cmd/cmd.go, readme.md
based on the discussion: https://github.com/ignite/cli/pull/3192#issuecomment-1343117020
- Append the base project URL for local files link (`/`)
- Use the local URL instead the full URL
- Check all markdowns and not only the docs folder
- Fix some broken links
=> chore(CI): not check local urls for the md files

go.mod, ignite/services/plugin/template/go.mod.plush, ignite/templates/app/files/go.mod.plush
Update go version in `go.mod` and in template `go.mod` files.
=> chore: update `go version`

ignite/cmd/plugin.go
=> fix: return error for not found in `ignite plugin remove`

.github/CODEOWNERS
Add @jeronimoalbi and @tbruyelle
=> chore: add users to docs `CODEOWNERS`

docs/docs/guide/07-ibc.md
=> docs: update the IBC Hello, World! tutorial to v0.26

.gitpod.Dockerfile, readme.md
=> chore: update gitpod to use `main` branch

.github/workflows/release-nightly.yml
Fix #3366
The error was related to the upload part, which sometimes works and sometimes fails. Using a higher retry value might solve the issue.
=> fix: nightly release

changelog.md
- Changelog title moved back to top
- Corrected tag version to match released version
=> chore: fix changelog

docs/docs/02-guide/05-loan/05-repay.md
=> chore(docs): improve `05-repay.md` doc

docs/docs/02-guide/05-loan/06-liquidate.md
=> chore(docs): improve `06-liquidate.md` docs

ignite/templates/module/create/files/msgserver/x/{{moduleName}}/keeper/msg_server_test.go.plush
=> fix: correct missing template import

docs/docs/02-guide/03-hello/00-express.md
=> fix: fix typo on `00-express.md` docs

.github/workflows/release-nightly.yml
=> fix: nightly release workflow

changelog.md, ignite/templates/app/files/go.mod.plush
These libraries were out of date, so I patched them:
* cometbft
* cometbft-db
=> fix: update cometbft and cometbft-db

ignite/cmd/account.go, ignite/cmd/chain.go, ignite/cmd/cmd.go, ignite/cmd/node.go, ignite/cmd/node_query.go, ignite/cmd/plugin.go, ignite/cmd/scaffold.go, ignite/cmd/tools.go
find right the app path for the migration pre handler
=> fix(cmd): fix wrong app path for migrations

.github/labeler.yml, .github/labels.json, .github/workflows/auto-author-assign.yml, .github/workflows/labeler.yml, .github/workflows/md-link-checker.yml, .github/workflows/release-binary.yml, .github/workflows/release-docker.yml, .github/workflows/release-nightly.yml, .github/workflows/test-integration.yml, .github/workflows/test-lint.yml, .github/workflows/test-semantic.yml, .github/workflows/test.yml
- Add GitHub action to add labels to issues;
- Add GitHub action to auto-assign the author'
- Add workflow concurrencies;
=> feat(ci): add repo organization actions

docs/docs/02-guide/04-blog/06-show.md
Added reference to post object
=> fix: Update 06-show.md

readme.md
=> chore: add badges to the readme

.github/CODEOWNERS
As suggested by @ilgooz - changing owners of the docs to @salmad3 @toschdev
=> docs: change docs owner

.github/workflows/test-integration.yml
Track `.tpl` files change to run the integration tests. The `.tpl` files are used for the typescript templates.
=> chore: track `.tpl` files changes in the integration tests

docs/versioned_docs/version-v0.27.2/03-clients/01-go-client.md
to create a post and store the response in txResp
=> docs: Update 01-go-client.md comments on broadcasting a transaction

ignite/config/chain/base/config.go
=> chore: remove unused parameters from the config yaml

ignite/templates/app/files/app/app_config.go.plush, ignite/templates/app/files/app/ibc.go.plush
Based on: https://github.com/ignite/cli/pull/3659
ref: https://github.com/ignite/cli/pull/3659#issuecomment-1811221770
=> fix: fix ibc registration in 0.50

docs/docs/01-welcome/01-index.md
Trying to make the welcome page more exciting for newcomers.
=> docs: Try to make the welcome page more exciting

docs/docs/02-guide/00-introduction.md
Fix missing bullet point in Introduction
=> docs: Fix missing bullet point in Introduction

.github/labeler.yml, .github/workflows/release-binary.yml, .github/workflows/test-integration.yml, .github/workflows/test-lint.yml, .github/workflows/test.yml
- Updates the labeler script to reflect the latest changes with the repo's labels.
- Updates workflows to run both in linux and mac-os environments; resolves #868.
=> chore: ci workflow enhancements

go.mod, go.sum
This is a companion to #3785 && #3725 
Still won't work properly due to the Paginated bug mentioned here: https://github.com/ignite/cli/pull/3785#issuecomment-1838022791
Should work fine once that's fixed.
=> feat: Update vue/react web templates for SDK >= 0.50.0

changelog.md, ignite/cmd/plugin_default.go
=> chore: bump network app version to `v0.2.1`

ignite/pkg/cosmosgen/templates/root/package.json.tpl
This commit was accidentally not pushed to #3785 as it should...adding it here
=> feat: Update ts client deps

.github/workflows/release-docker.yml, .gitpod.Dockerfile, Dockerfile, scripts/indocker
=> fix: bump go version for docker files

.github/CODEOWNERS
Just a proposal to not gate keep the changelog, as most PRs need a changelog.
=> chore: losen changelog gatekeeping

changelog.md, ignite/templates/app/files/cmd/{{binaryNamePrefix}}d/cmd/commands.go.plush
Add mission querry and tx commands for IBC modules
=> fix: add missing IBC commands for scaffolded chain

readme.md
Please make sure to check the following for your PR:
Ignite CLI team only:
=> docs: add v28 to README

changelog.md, ignite/templates/app/files/cmd/{{binaryNamePrefix}}d/cmd/root.go.plush
Closes: https://github.com/ignite/cli/issues/3865
=> fix(templates): fix genesis export for ibc modules

docs/docs/02-guide/05-loan.md, docs/docs/02-guide/06-tokenfactory/01-tokenfactory.md, docs/docs/04-network/04-validator.md, docs/docs/apps/02-developing-apps.md
Caught few typos and errors while reading the docs. Corrected them.
Doesn't require testing or changelog entry I believe.
Have a nice evening.
=> chore(docs): proofreading

changelog.md, ignite/services/plugin/plugin.go
=> chore: change Ignite App extension to "ign"

.github/dependabot.yml, .github/workflows/docs-deploy-preview.yml, .github/workflows/docs-deploy.yml, .github/workflows/gen-docs-version.yml
ref: https://github.com/ignite/cli/actions/runs/7531671146/job/20520165874
=> ci: bump node version

.github/workflows/release-docker.yml, .github/workflows/release-nightly.yml, .github/workflows/snapcraft.yml, Makefile, packaging/flatpak/com.ignite.Ignite.yml, packaging/snap/snapcraft.yaml
Closes: https://github.com/ignite/cli/issues/3821
Once Canonical allowed us to publish the snap, then we are all good: https://forum.snapcraft.io/t/request-for-classic-confinement-ignite/38581.
However, this can already be merged.
=> ci: configure snapcraft

ignite/internal/analytics/analytics.go, ignite/pkg/gacli/gacli.go
=> refactor(analytics): flag CI in analytics

ignite/templates/app/files/cmd/{{binaryNamePrefix}}d/cmd/commands.go.plush
ref: https://github.com/ignite/cli/pull/3820/files/69a5f692d9d5a4c568b7dc98b847bd1a42d929b9#r1472738852
cc @Pantani
=> chore(templates): revert unneeded template addition

readme.md
Resolving issue #2249 by adding installation command to the readme.md file.
[#2249 ](https://github.com/orgs/ignite/projects/7/views/4?pane=issue&itemId=51561336)
=> docs(readme): add installation commands

.gitpod/readme.md, docs/docs/01-welcome/02-install.md, readme.md
ref: https://github.com/ignite/cli/pull/3923/files#r1477097621
[rendered](https://github.com/ignite/cli/blob/c3107fc262a5d386158808b8e822a6c6dc104348/readme.md)
=> chore: update installation instructions

changelog.md
Follow-up of https://github.com/ignite/cli/pull/3939
=> chore: add v28.2.0 changelog to main

ignite/templates/app/files/app/export.go.plush, ignite/templates/app/files/cmd/{{binaryNamePrefix}}d/cmd/root.go.plush, ignite/templates/app/files/docs/docs.go.plush, ignite/templates/module/create/files/base/testutil/keeper/{{moduleName}}.go.plush, ignite/templates/module/create/files/base/x/{{moduleName}}/module/genesis.go.plush, ignite/templates/module/create/files/base/x/{{moduleName}}/module/simulation.go.plush, ignite/templates/module/create/files/ibc/testutil/keeper/{{moduleName}}.go.plush
ref: https://github.com/ignite/cli/issues/3288
=> fix(templates): fix lint errors in scaffolded chain

readme.md
=> docs: Change plugins to Ignite Apps on Readme

changelog.md, ignite/templates/typed/list/files/messages/x/{{moduleName}}/keeper/msg_server_{{typeName}}.go.plush
Found while hardening: https://github.com/ignite/cli/pull/3707
` ignite s list testlist title body --signer author` will scaffold the wrong signer.
=> fix(templates): set correct signer

changelog.md, ignite/cmd/plugin_default.go
Closes: https://github.com/ignite/cli/issues/4020
=> build(deps): bump `cli-plugin-network`

changelog.md, ignite/templates/ibc/files/packet/component/x/{{moduleName}}/keeper/{{packetName}}.go.plush
ref: https://github.com/ignite/cli/pull/4058#discussion_r1543115941
=> fix(templates): avoid nil `scopedKeeper`

docs/docs/02-guide/06-tokenfactory/01-tokenfactory.md
Replaced sdkerrors.Wrapf with errorsmod.Wrapf for both tickerLength and msg.MaxSupply
=> docs: Update 01-tokenfactory.md

.github/workflows/docs-deploy-preview.yml, .github/workflows/docs-deploy.yml, .github/workflows/gen-docs-cli.yml, .github/workflows/gen-docs-version.yml, .github/workflows/go-formatting.yml, .github/workflows/md-link-checker.yml, .github/workflows/proto-checker.yml, .github/workflows/release-binary.yml, .github/workflows/release-docker.yml, .github/workflows/release-nightly.yml, .github/workflows/release-snapcraft.yml, .github/workflows/test-integration.yml, .github/workflows/test-lint.yml, .github/workflows/test.yml, ignite/templates/app/files/.github/workflows/release.yml
- use the Golang stable version in the CI;
- bump some Github default actions;
=> chore: use golang stable version into the CI

.github/workflows/test-integration.yml
=> ci: don't fail fast

docs/docusaurus.config.js, docs/package.json
=> chore: update telemetry

Dockerfile, changelog.md, go.mod
Please make sure to check the following for your PR:
Ignite CLI team only:
sure that the change doesn't need to be reflected in the
`ignite/templates/files-*` folders.
=> chore: update go

docs/docs/08-references/03-config.md, ignite/config/chain/base/config.go, ignite/config/chain/v0/config.go, ignite/config/chain/v1/config.go, ignite/config/chain/v1/validator.go, ignite/internal/tools/gen-config-doc/cmd/root.go, ignite/internal/tools/gen-config-doc/go.mod, ignite/internal/tools/gen-config-doc/go.sum, ignite/internal/tools/gen-config-doc/templates/doc/files/{{Name}}.plush, ignite/pkg/clidoc/struct.go, ignite/pkg/clidoc/struct_test.go, scripts/gen-config-doc
- Improve the document generation;
- Improve text based on change made by @toschdev;
Based on the document created by @toschdev. Thanks!!!
=> feat(internal/tools): improve config doc

ignite/templates/app/files-consumer/app/app.go.plush, ignite/templates/app/files-minimal/app/app.go.plush, ignite/templates/app/files/app/app.go.plush, ignite/templates/app/files/cmd/{{binaryNamePrefix}}d/main.go.plush, ignite/templates/app/files/go.mod.plush
Wire https://github.com/cosmos/cosmos-sdk/pull/20970
=> chore: wire client/v2 fix

ignite/cmd/cmd.go
Closes: https://github.com/ignite/cli/issues/4260
=> fix: improve formatting upgrade message

docs/docusaurus.config.js
- Add an additional Matomo container in order to get a more detailed telemetry view (micro/macro)
- Fully remove GTM
=> chore: matomo update

changelog.md, ignite/pkg/cosmosclient/cosmosclient.go, ignite/pkg/cosmosclient/rpc.go, ignite/pkg/cosmosclient/signer.go, ignite/pkg/cosmosclient/tx_options.go
Closes: https://github.com/ignite/cli/issues/3997
=> feat(cosmosclient): add tx options (incl memo setting)

.github/workflows/md-link-checker.yml, .github/workflows/test-integration.yml, .github/workflows/test-lint.yml, .github/workflows/test.yml
This may fix PR hanging like this: https://github.com/ignite/cli/pull/4196.
The drawback is that docs PRs will take longer to have CI pass, but may unblock us.
=> ci: always run ci

readme.md
Update Discord invitation link in the Readme
=> docs: Update Discord invitation link

ignite/templates/app/files/go.mod.plush
Not targeting main because https://github.com/ignite/cli/pull/4289 should be hopefully merged today there :D
=> chore: use tagged ibc version

changelog.md, ignite/templates/app/files/go.mod.plush
https://github.com/cosmos/cosmos-sdk/releases/tag/v0.50.10
=> chore: bump sdk

ignite/templates/module/create/files/base/x/{{moduleName}}/types/expected_keepers.go.plush
Fixes https://github.com/ignite/cli/actions/runs/11969497436/job/33370371627?pr=4409
=> chore: fix expected keepers

ignite/templates/app/files/go.mod.plush
Closes: https://github.com/ignite/cli/issues/4499
=> fix(templates): replace broken vanity url

docs/docs/02-guide/04-blog.md, docs/docs/02-guide/05-loan.md
ref: https://github.com/ignite/cli/pull/4535/files
=> chore: sync docs

ignite/templates/app/files/go.mod.plush
ref: https://github.com/cosmos/ibc-go/releases/tag/v10.1.0
=> build(deps): bump to ibc-go v10.1.0

ignite/internal/tools/gen-mig-diffs/pkg/url/url.go, ignite/pkg/goanalysis/goanalysis.go
make function comment match function name
=> chore: make function comment match function name

ignite/cmd/doctor.go, ignite/pkg/cosmosbuf/buf.go, ignite/pkg/xos/files.go, ignite/pkg/xos/files_test.go, ignite/services/doctor/doctor.go
Fixes `ignite doctor` issue in latest v29.
We need to add the tools before proceeding to any check.
=> fix(doctor): fix `ignite doctor` tool

changelog.md, ignite/templates/module/create/files/base/x/{{moduleName}}/keeper/query_params.go.plush
small pr, fixing the error not found, when a chain a empty params.
=> fix(templates): fix default params

.github/workflows/labeler.yml
ref: https://github.com/ignite/cli/pull/4590
=> revert(ci): revert labeler action bump

docs/docs/01-welcome/01-index.md
ref: https://github.com/ignite/cli/pull/4576 / https://github.com/ignite/cli/pull/4576#issuecomment-2773055674
I'll tell mergify to backport to v27 and v26 afterwards too.
=> docs: update default url

changelog.md, ignite/pkg/xast/function.go, ignite/pkg/xast/function_test.go, ignite/pkg/xast/global.go, ignite/pkg/xast/global_test.go, ignite/pkg/xast/import.go, ignite/pkg/xast/import_test.go, ignite/templates/ibc/packet.go, ignite/templates/message/message.go, ignite/templates/module/create/base.go, ignite/templates/module/create/ibc.go, ignite/templates/typed/list/genesis.go, ignite/templates/typed/list/list.go, ignite/templates/typed/map/map.go, ignite/templates/typed/simulation.go, ignite/templates/typed/singleton/singleton.go
=> fix: xast misplacing comments

contributing.md
Closes: https://github.com/ignite/cli/issues/2591
=> docs: add coding style

.github/CODEOWNERS, changelog.md
After this PR i'll tag v29 rc.1.
=> chore: prepare v29 rc.1 + update codeowners

changelog.md, ignite/templates/module/create/files/base/x/{{moduleName}}/module/module.go.plush
Closes: https://github.com/ignite/cli/issues/4688
=> fix(templates): correctly implement `HasGenesis` interface

ignite/pkg/cosmosgen/templates/rest/rest.ts.tpl, ignite/pkg/cosmosgen/templates/root/index.ts.tpl, ignite/pkg/cosmosgen/templates/root/package.json.tpl
ref: https://github.com/ignite/cli/issues/4690
=> fix(templates): fix .tpl and bump ts-client deps

readme.md
=> chore: add v29, remove dead link, add marketplace link in readme

changelog.md, ignite/pkg/cosmosanalysis/module/module.go, ignite/pkg/cosmosanalysis/module/module_test.go, ignite/pkg/cosmosgen/template.go, ignite/pkg/cosmosgen/templates/rest/rest.ts.tpl, ignite/pkg/cosmosgen/testdata/expected_files/ts-client/mars/rest.ts, ignite/pkg/cosmosgen/testdata/testchain/proto/planet/mars/mars.proto, ignite/pkg/cosmosgen/testdata/testchain/ts-client/mars/rest.ts
ref: https://github.com/ignite/cli/issues/4690
Follow-up of https://github.com/ignite/cli/pull/4706
=> refactor(cosmosgen): wire ts generic template

ignite/pkg/cosmosgen/templates/composable/index.ts.tpl
Final fixes for composables template
=> fix: ensure correct typings
